// Калькуляторы для кирпичной кладки, блоков и декоративного камня
// Часть walls_calculators, разделенного для улучшения поддержки

import '../../../../core/enums/calculator_category.dart';
import '../../../../core/enums/field_input_type.dart';
import '../../../../core/enums/unit_type.dart';
import '../../../models/calculator_definition_v2.dart';
import '../../../models/calculator_field.dart';
import '../../../models/calculator_hint.dart';
import '../../calculator_constants.dart';
import '../../../usecases/canonical_bridge.dart';
import '../../../usecases/partitions_canonical_adapter.dart';
import '../../../usecases/brickwork_canonical_adapter.dart';
import '../../../usecases/decor_stone_canonical_adapter.dart';

final List<CalculatorDefinitionV2> wallsMasonryCalculators = [
  // 1. partitions_blocks - Перегородки из блоков
  const CalculatorDefinitionV2(
      id: 'partitions_blocks',
      titleKey: 'calculator.partitions_blocks.title',
      descriptionKey: 'calculator.partitions_blocks.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.partitions',
      fields: [
        CalculatorField(
          key: 'length',
          labelKey: 'input.length',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 5.0,
          minValue: 1.0,
          maxValue: 20.0,
          step: 1.0,
          iconName: 'straighten',
          group: 'dimensions',
          required: true,
          order: 1,
        ),
        CalculatorField(
          key: 'height',
          labelKey: 'input.height',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 2.7,
          minValue: 2.0,
          maxValue: 4.0,
          step: 1.0,
          iconName: 'height',
          group: 'dimensions',
          required: true,
          order: 2,
        ),
        CalculatorField(
          key: 'thickness',
          labelKey: 'input.thickness',
          hintKey: 'input.block_thickness.hint',
          unitType: UnitType.millimeters,
          inputType: FieldInputType.slider,
          defaultValue: 100.0,
          minValue: 50.0,
          maxValue: 400.0,
          step: 10.0,
          iconName: 'width_normal',
          group: 'material',
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_spetsialnyy_kley_dlya'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.armiruyte_kazhdyy_3_4'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.pervyy_ryad_ukladyvayte_na'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.proveryayte_geometriyu_urovnem'),
      ],
      afterHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_spetsialnyy_kley_dlya'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.armiruyte_kazhdyy_3_4'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.pervyy_ryad_ukladyvayte_na'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.proveryayte_geometriyu_urovnem'),
      ],
      useCase: CanonicalBridgeUseCase(calculateCanonicalPartitions),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'tag.peregorodki',
        'partitions',
        'blocks',
        'partitions_blocks',
      ],
    ),

  // 2. partitions_brick - Перегородки из кирпича
  const CalculatorDefinitionV2(
      id: 'partitions_brick',
      titleKey: 'calculator.partitions_brick.title',
      descriptionKey: 'calculator.partitions_brick.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.partitions',
      fields: [
        CalculatorField(
          key: 'length',
          labelKey: 'input.length',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 5.0,
          minValue: 1.0,
          maxValue: 20.0,
          step: 1.0,
          iconName: 'straighten',
          group: 'dimensions',
          required: true,
          order: 1,
        ),
        CalculatorField(
          key: 'height',
          labelKey: 'input.height',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 2.7,
          minValue: 2.0,
          maxValue: 4.0,
          step: 1.0,
          iconName: 'height',
          group: 'dimensions',
          required: true,
          order: 2,
        ),
        CalculatorField(
          key: 'brickType',
          labelKey: 'input.type',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 0.5,
          minValue: 0.5,
          maxValue: 1.0,
          iconName: 'category',
          group: 'material',
          required: true,
          order: 3,
        ),
        CalculatorField(
          key: 'workingConditions',
          labelKey: 'input.workingConditions',
          unitType: UnitType.pieces,
          inputType: FieldInputType.select,
          defaultValue: 1.0,
          iconName: 'thermostat',
          group: 'conditions',
          required: false,
          order: 10,
          options: [
            FieldOption(value: 1.0, labelKey: 'input.workingConditions.normal'),
            FieldOption(value: 2.0, labelKey: 'input.workingConditions.windy'),
            FieldOption(value: 3.0, labelKey: 'input.workingConditions.cold'),
            FieldOption(value: 4.0, labelKey: 'input.workingConditions.hot'),
          ],
        ),
      ],
      beforeHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.kladku_v_polkirpicha_armiruyte'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_tsementno_peschanyy_rastvor'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.proveryayte_vertikalnost_otvesom'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.svyazyvayte_s_nesuschimi_stenami'),
      ],
      afterHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.kladku_v_polkirpicha_armiruyte'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_tsementno_peschanyy_rastvor'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.proveryayte_vertikalnost_otvesom'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.svyazyvayte_s_nesuschimi_stenami'),
        CalculatorHint(
          type: HintType.warning,
          messageKey: 'hint.brick.cold_weather_warning',
          condition: HintCondition(
            type: HintConditionType.equals,
            fieldKey: 'workingConditions',
            value: 3,
          ),
        ),
      ],
      useCase: CanonicalBridgeUseCase(calculateCanonicalBrickwork),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'tag.peregorodki',
        'partitions',
        'partitions_brick',
        'brick',
      ],
    ),

  // 3. walls_decor_stone - Декоративный камень
  const CalculatorDefinitionV2(
      id: 'walls_decor_stone',
      titleKey: 'calculator.walls_decor_stone.title',
      descriptionKey: 'calculator.walls_decor_stone.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.walls',
      fields: [
        CalculatorField(
          key: 'area',
          labelKey: 'input.wallArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.slider,
          defaultValue: 10.0,
          minValue: 1.0,
          maxValue: 200.0,
          step: 1.0,
          iconName: 'square_foot',
          group: 'dimensions',
          required: true,
          order: 1,
        ),
        CalculatorField(
          key: 'stoneType',
          labelKey: 'input.stoneType',
          unitType: UnitType.pieces,
          inputType: FieldInputType.select,
          defaultValue: 0.0,
          iconName: 'texture',
          group: 'material',
          required: true,
          order: 2,
          options: [
            FieldOption(value: 0.0, labelKey: 'input.stoneType.gypsum'),
            FieldOption(value: 1.0, labelKey: 'input.stoneType.concrete'),
            FieldOption(value: 2.0, labelKey: 'input.stoneType.natural'),
          ],
        ),
        CalculatorField(
          key: 'jointWidth',
          labelKey: 'input.jointWidth',
          unitType: UnitType.millimeters,
          inputType: FieldInputType.slider,
          defaultValue: 10.0,
          minValue: 0.0,
          maxValue: 20.0,
          step: 1.0,
          iconName: 'space_bar',
          group: 'material',
          required: false,
          order: 3,
        ),
      ],
      beforeHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.dobavte_10_zapas_na'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_spetsialnyy_kley_dlya_3'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.obrabotayte_kamen_gidrofobizatorom'),
      ],
      afterHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.dobavte_10_zapas_na'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_spetsialnyy_kley_dlya_3'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.obrabotayte_kamen_gidrofobizatorom'),
      ],
      useCase: CanonicalBridgeUseCase(calculateCanonicalDecorStone),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'decor',
        'stone',
        'walls',
        'tag.steny',
        'walls_decor_stone',
      ],
    ),
];
