// Калькуляторы для штукатурки, грунтовки, шпатлёвки и смесей
// Часть walls_calculators, разделенного для улучшения поддержки

import '../../../../core/enums/calculator_category.dart';
import '../../../../core/enums/field_input_type.dart';
import '../../../../core/enums/unit_type.dart';
import '../../../models/calculator_definition_v2.dart';
import '../../../models/calculator_field.dart';
import '../../../models/calculator_hint.dart';
import '../../../models/calculator_link.dart';
import '../../calculator_constants.dart';
import '../../../usecases/canonical_bridge.dart';
import '../../../usecases/plaster_canonical_adapter.dart';
import '../../../usecases/primer_canonical_adapter.dart';
import '../../../usecases/putty_canonical_adapter.dart';
import '../../../usecases/tile_adhesive_canonical_adapter.dart';
import '../../../usecases/decor_plaster_canonical_adapter.dart';
// calculate_wall_paint.dart больше не используется - walls_paint заменён на paint_universal

final List<CalculatorDefinitionV2> wallsPlasterCalculators = [
  // 1. mixes_plaster - Штукатурка
  const CalculatorDefinitionV2(
      id: 'mixes_plaster',
      titleKey: 'calculator.mixes_plaster.title',
      descriptionKey: 'calculator.mixes_plaster.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.leveling_mix',
      fields: [
        CalculatorField(
          key: 'area',
          labelKey: 'input.wallArea',
          hintKey: 'input.wallArea.hint',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.slider,
          defaultValue: 20.0,
          minValue: 1.0,
          maxValue: 1000.0,
          step: 1.0,
          iconName: 'square_foot',
          group: 'dimensions',
          required: true,
          order: 1,
        ),
        CalculatorField(
          key: 'thickness',
          labelKey: 'input.plaster_thickness',
          hintKey: 'input.plaster_thickness.hint',
          unitType: UnitType.millimeters,
          inputType: FieldInputType.slider,
          defaultValue: 10.0,
          minValue: 5.0,
          maxValue: 50.0,
          step: 1.0,
          iconName: 'height',
          group: 'material',
          required: true,
          order: 2,
        ),
        CalculatorField(
          key: 'type',
          labelKey: 'input.plaster_type',
          unitType: UnitType.pieces,
          inputType: FieldInputType.select,
          defaultValue: 1.0,
          iconName: 'category',
          group: 'material',
          required: true,
          order: 3,
          options: [
            FieldOption(value: 1.0, labelKey: 'input.plaster_type.gypsum'),
            FieldOption(value: 2.0, labelKey: 'input.plaster_type.cement'),
          ],
        ),
        CalculatorField(
          key: 'substrateType',
          labelKey: 'input.substrateType',
          hintKey: 'input.substrateType.hint',
          unitType: UnitType.pieces,
          inputType: FieldInputType.select,
          defaultValue: 1.0,
          iconName: 'wall',
          group: 'conditions',
          required: true,
          order: 4,
          options: [
            FieldOption(value: 1.0, labelKey: 'input.substrateType.concrete'),
            FieldOption(value: 2.0, labelKey: 'input.substrateType.new_brick'),
            FieldOption(value: 3.0, labelKey: 'input.substrateType.old_brick'),
            FieldOption(value: 4.0, labelKey: 'input.substrateType.gas_block'),
            FieldOption(value: 5.0, labelKey: 'input.substrateType.foam_concrete'),
          ],
        ),
        CalculatorField(
          key: 'wallEvenness',
          labelKey: 'input.wallEvenness',
          hintKey: 'input.wallEvenness.hint',
          unitType: UnitType.pieces,
          inputType: FieldInputType.select,
          defaultValue: 1.0,
          iconName: 'straighten',
          group: 'conditions',
          required: true,
          order: 5,
          options: [
            FieldOption(value: 1.0, labelKey: 'input.wallEvenness.even'),
            FieldOption(value: 2.0, labelKey: 'input.wallEvenness.uneven'),
            FieldOption(value: 3.0, labelKey: 'input.wallEvenness.very_uneven'),
          ],
        ),
      ],
      beforeHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.plaster.measure_walls'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.plaster.gypsum_for_interior'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.plaster.cement_for_wet'),
      ],
      afterHints: [
        CalculatorHint(
          type: HintType.warning,
          messageKey: 'hint.plaster.thick_layer',
          condition: HintCondition(
            type: HintConditionType.equals,
            resultKey: 'warningThickLayer',
            value: 1,
          ),
        ),
        CalculatorHint(
          type: HintType.tip,
          messageKey: 'hint.plaster.obryzg_recommended',
          condition: HintCondition(
            type: HintConditionType.equals,
            resultKey: 'tipObryzg',
            value: 1,
          ),
        ),
      ],
      useCase: CanonicalBridgeUseCase(calculateCanonicalPlaster),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      showToolsSection: false,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'tag.rovniteli_smesi',
        'plaster',
        'mixes',
        'mixes_plaster',
      ],
      relatedLinks: [
        CalculatorLink(
          targetId: 'mixes_putty',
          labelKey: 'link.calculate_putty',
          iconName: 'layers',
          inputMapping: {'area': 'area'},
        ),
        CalculatorLink(
          targetId: 'mixes_primer',
          labelKey: 'link.calculate_primer',
          iconName: 'format_paint',
          inputMapping: {'area': 'area'},
        ),
      ],
    ),

  // 2. mixes_primer - Грунтовка
  const CalculatorDefinitionV2(
      id: 'mixes_primer',
      titleKey: 'calculator.mixes_primer.title',
      descriptionKey: 'calculator.mixes_primer.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.leveling_mix',
      fields: [
        CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.slider,
          defaultValue: 20.0,
          minValue: 1.0,
          maxValue: 500.0,
          step: 1.0,
          iconName: 'square_foot',
          group: 'dimensions',
          required: true,
          order: 1,
        ),
        CalculatorField(
          key: 'layers',
          labelKey: 'input.layers',
          unitType: UnitType.pieces,
          inputType: FieldInputType.slider,
          defaultValue: 1.0,
          minValue: 1.0,
          maxValue: 3.0,
          step: 1.0,
          iconName: 'filter_none',
          group: 'options',
          required: true,
          order: 2,
        ),
        CalculatorField(
          key: 'type',
          labelKey: 'input.type',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          minValue: 1.0,
          maxValue: 3.0,
          iconName: 'category',
          group: 'material',
          required: true,
          order: 3,
        ),
        CalculatorField(
          key: 'canSize',
          labelKey: 'input.canSize',
          hintKey: 'input.canSize.hint',
          unitType: UnitType.liters,
          inputType: FieldInputType.select,
          defaultValue: 10.0,
          iconName: 'local_drink',
          group: 'material',
          required: false,
          order: 4,
          options: [
            FieldOption(value: 5, labelKey: 'input.canSize.5l'),
            FieldOption(value: 10, labelKey: 'input.canSize.10l'),
            FieldOption(value: 15, labelKey: 'input.canSize.15l'),
            FieldOption(value: 20, labelKey: 'input.canSize.20l'),
          ],
        ),
      ],
      beforeHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.gruntovka_uluchshaet_adgeziyu_materialov'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.gruntovka_glubokogo_proniknoveniya_dlya'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.nanosite_ravnomernym_sloem'),
      ],
      afterHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.gruntovka_uluchshaet_adgeziyu_materialov'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.gruntovka_glubokogo_proniknoveniya_dlya'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.nanosite_ravnomernym_sloem'),
      ],
      useCase: CanonicalBridgeUseCase(calculateCanonicalPrimer),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'mixes_primer',
        'tag.rovniteli_smesi',
        'mixes',
        'primer',
      ],
    ),

  // 3. mixes_putty - Шпатлёвка
  const CalculatorDefinitionV2(
      id: 'mixes_putty',
      titleKey: 'calculator.mixes_putty.title',
      descriptionKey: 'calculator.mixes_putty.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.leveling_mix',
      fields: [
        CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.slider,
          defaultValue: 20.0,
          minValue: 1.0,
          maxValue: 500.0,
          step: 1.0,
          iconName: 'square_foot',
          group: 'dimensions',
          required: true,
          order: 1,
        ),
        CalculatorField(
          key: 'type',
          labelKey: 'input.putty_type',
          unitType: UnitType.pieces,
          inputType: FieldInputType.select,
          defaultValue: 1.0,
          iconName: 'category',
          group: 'material',
          required: true,
          order: 2,
          options: [
            FieldOption(value: 1.0, labelKey: 'input.putty_type.start'),
            FieldOption(value: 2.0, labelKey: 'input.putty_type.finish'),
          ],
        ),
        CalculatorField(
          key: 'qualityClass',
          labelKey: 'input.qualityClass',
          unitType: UnitType.pieces,
          inputType: FieldInputType.select,
          defaultValue: 2.0,
          iconName: 'star',
          group: 'material',
          required: true,
          order: 3,
          options: [
            FieldOption(value: 1.0, labelKey: 'input.qualityClass.economy'),
            FieldOption(value: 2.0, labelKey: 'input.qualityClass.standard'),
            FieldOption(value: 3.0, labelKey: 'input.qualityClass.premium'),
          ],
        ),
        CalculatorField(
          key: 'layers',
          labelKey: 'input.layers',
          unitType: UnitType.pieces,
          inputType: FieldInputType.slider,
          defaultValue: 2.0,
          minValue: 1.0,
          maxValue: 3.0,
          step: 1.0,
          iconName: 'filter_none',
          group: 'options',
          required: false,
          order: 4,
        ),
      ],
      beforeHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.startovaya_shpaklevka_dlya_vyravnivaniya'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.nanosite_tonkimi_sloyami'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.shlifuyte_mezhdu_sloyami'),
      ],
      afterHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.startovaya_shpaklevka_dlya_vyravnivaniya'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.nanosite_tonkimi_sloyami'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.shlifuyte_mezhdu_sloyami'),
      ],
      useCase: CanonicalBridgeUseCase(calculateCanonicalPutty),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'tag.rovniteli_smesi',
        'putty',
        'mixes',
        'mixes_putty',
      ],
      relatedLinks: [
        CalculatorLink(
          targetId: 'paint_universal',
          labelKey: 'link.calculate_paint',
          iconName: 'brush',
          inputMapping: {'area': 'wallArea'},
          staticInputs: {'paintType': 0, 'inputMode': 0},
        ),
        CalculatorLink(
          targetId: 'walls_wallpaper',
          labelKey: 'link.calculate_wallpaper',
          iconName: 'wallpaper',
          inputMapping: {'area': 'area'},
          staticInputs: {'inputMode': 1},
        ),
        CalculatorLink(
          targetId: 'mixes_primer',
          labelKey: 'link.calculate_primer',
          iconName: 'format_paint',
          inputMapping: {'area': 'area'},
        ),
      ],
    ),

  // 4. mixes_tile_glue - Плиточный клей
  const CalculatorDefinitionV2(
      id: 'mixes_tile_glue',
      titleKey: 'calculator.mixes_tile_glue.title',
      descriptionKey: 'calculator.mixes_tile_glue.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.leveling_mix',
      fields: [
        CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.slider,
          defaultValue: 20.0,
          minValue: 1.0,
          maxValue: 500.0,
          step: 1.0,
          iconName: 'square_foot',
          group: 'dimensions',
          required: true,
          order: 1,
        ),
        CalculatorField(
          key: 'tileSize',
          labelKey: 'input.tileSize',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 30.0,
          minValue: 10.0,
          maxValue: 120.0,
          step: 5.0,
          iconName: 'grid_view',
          group: 'material',
          required: true,
          order: 2,
        ),
        CalculatorField(
          key: 'layerThickness',
          labelKey: 'input.layerThickness',
          hintKey: 'input.glue_thickness.hint',
          unitType: UnitType.millimeters,
          inputType: FieldInputType.slider,
          defaultValue: 5.0,
          minValue: 2.0,
          maxValue: 15.0,
          step: 1.0,
          iconName: 'height',
          group: 'material',
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.rashod_zavisit_ot_razmera'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_zubchatyy_shpatel'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.nanosite_kley_na_osnovanie'),
      ],
      afterHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.rashod_zavisit_ot_razmera'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_zubchatyy_shpatel'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.nanosite_kley_na_osnovanie'),
      ],
      useCase: CanonicalBridgeUseCase(calculateCanonicalTileAdhesive),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'tile',
        'tag.rovniteli_smesi',
        'mixes_tile_glue',
        'mixes',
        'glue',
      ],
    ),

  // 5. walls_decor_plaster - Декоративная штукатурка
  const CalculatorDefinitionV2(
      id: 'walls_decor_plaster',
      titleKey: 'calculator.walls_decor_plaster.title',
      descriptionKey: 'calculator.walls_decor_plaster.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.walls',
      fields: [
        CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.slider,
          defaultValue: 20.0,
          minValue: 1.0,
          maxValue: 500.0,
          step: 1.0,
          iconName: 'square_foot',
          group: 'dimensions',
          required: true,
          order: 1,
        ),
        CalculatorField(
          key: 'thickness',
          labelKey: 'input.thickness',
          unitType: UnitType.millimeters,
          inputType: FieldInputType.slider,
          defaultValue: 2.0,
          minValue: 0.5,
          maxValue: 10.0,
          step: 1.0,
          iconName: 'height',
          group: 'material',
          required: true,
          order: 2,
        ),
        CalculatorField(
          key: 'windowsArea',
          labelKey: 'input.windowsArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.slider,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 100.0,
          step: 1.0,
          iconName: 'window',
          group: 'openings',
          required: false,
          order: 3,
        ),
        CalculatorField(
          key: 'doorsArea',
          labelKey: 'input.doorsArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.slider,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 50.0,
          step: 1.0,
          iconName: 'door_front',
          group: 'openings',
          required: false,
          order: 4,
        ),
        CalculatorField(
          key: 'plasterType',
          labelKey: 'input.plasterType',
          unitType: UnitType.pieces,
          inputType: FieldInputType.select,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 2.0,
          step: 1.0,
          iconName: 'texture',
          group: 'material',
          required: false,
          order: 5,
          options: [
            FieldOption(value: 0, labelKey: 'input.plasterType.textured'),
            FieldOption(value: 1, labelKey: 'input.plasterType.structural'),
            FieldOption(value: 2, labelKey: 'input.plasterType.venetian'),
          ],
        ),
      ],
      beforeHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_gruntovku_glubokogo_proniknoveniya'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.vozmite_shpateli_i_kelmy'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.dlya_venetsianskoy_shtukaturki_nuzhna'),
      ],
      afterHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_gruntovku_glubokogo_proniknoveniya'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.vozmite_shpateli_i_kelmy'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.dlya_venetsianskoy_shtukaturki_nuzhna'),
      ],
      useCase: CanonicalBridgeUseCase(calculateCanonicalDecorPlaster),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'decor',
        'walls',
        'walls_decor_plaster',
        'plaster',
        'tag.steny',
      ],
    ),

  // walls_paint удалён - используйте paint_universal (см. calculator_id_migration.dart)
];
