// Калькуляторы для ГКЛ (гипсокартона), панелей, обоев и деревянной отделки
// Часть walls_calculators, разделенного для улучшения поддержки

import '../../../../core/enums/calculator_category.dart';
import '../../../../core/enums/field_input_type.dart';
import '../../../../core/enums/unit_type.dart';
import '../../../models/calculator_definition_v2.dart';
import '../../../models/calculator_field.dart';
import '../../../models/calculator_hint.dart';
import '../../calculator_constants.dart';
import '../../../usecases/calculate_gypsum.dart';
import '../../../usecases/calculate_3d_panels.dart';
import '../../../usecases/calculate_mdf_panels.dart';
import '../../../usecases/calculate_pvc_panels.dart';
import '../../../usecases/calculate_wallpaper.dart';
import '../../../usecases/calculate_wood_wall.dart';

final List<CalculatorDefinitionV2> wallsDrywallCalculators = [
  // 1. gypsum_board - Гипсокартон (ГКЛ)
  CalculatorDefinitionV2(
      id: 'gypsum_board',
      titleKey: 'calculator.gypsum_board.title',
      descriptionKey: 'calculator.gypsum_board.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.walls',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 20.0,
          minValue: 1.0,
          maxValue: 1000.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'construction_type',
          labelKey: 'input.construction_type',
          unitType: UnitType.pieces,
          inputType: FieldInputType.select,
          defaultValue: 1.0,
          required: true,
          order: 2,
          options: [
            FieldOption(value: 1.0, labelKey: 'input.construction_type.wall_lining'),
            FieldOption(value: 2.0, labelKey: 'input.construction_type.partition'),
            FieldOption(value: 3.0, labelKey: 'input.construction_type.ceiling'),
          ],
        ),
        const CalculatorField(
          key: 'layers',
          labelKey: 'input.layers',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          minValue: 1.0,
          maxValue: 2.0,
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'gkl_type',
          labelKey: 'input.gkl_type',
          unitType: UnitType.pieces,
          inputType: FieldInputType.select,
          defaultValue: 1.0,
          required: true,
          order: 4,
          options: [
            FieldOption(value: 1.0, labelKey: 'input.gkl_type.standard'),
            FieldOption(value: 2.0, labelKey: 'input.gkl_type.moisture'),
            FieldOption(value: 3.0, labelKey: 'input.gkl_type.fire'),
          ],
        ),
        const CalculatorField(
          key: 'use_insulation',
          labelKey: 'input.use_insulation',
          unitType: UnitType.pieces,
          inputType: FieldInputType.checkbox,
          defaultValue: 0.0,
          required: false,
          order: 5,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.gypsum.choose_gklv_for_wet'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.gypsum.step_profiles_60cm'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.gypsum.use_sealing_tape'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.gypsum.screw_depth_1mm'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.gypsum.joints_offset'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.gypsum.gap_from_floor'),
      ],
      useCase: CalculateGypsum(),
      accentColor: kCalculatorAccentColor,
      complexity: 3,
      popularity: 9,
      showToolsSection: false,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'tag.steny',
        'gypsum',
        'gkl',
        'drywall',
        'gypsum_board',
      ],
    ),

  // 2. walls_3d_panels - 3D панели
  CalculatorDefinitionV2(
      id: 'walls_3d_panels',
      titleKey: 'calculator.walls_3d_panels.title',
      descriptionKey: 'calculator.walls_3d_panels.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.walls',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.wallArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 10.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'panelSize',
          labelKey: 'input.packArea',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.5,
          required: true,
          order: 2,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.proverte_rovnost_sten_pered'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_spetsialnyy_kley_dlya_2'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.nachinayte_montazh_ot_tsentra'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.proverte_rovnost_sten_pered'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_spetsialnyy_kley_dlya_2'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.nachinayte_montazh_ot_tsentra'),
      ],
      useCase: Calculate3dPanels(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'walls_3d_panels',
        'tag.vnutrennyaya_otdelka',
        'walls',
        'tag.steny',
        'panels',
        '3d',
      ],
    ),

  // 3. walls_mdf_panels - MDF панели
  CalculatorDefinitionV2(
      id: 'walls_mdf_panels',
      titleKey: 'calculator.walls_mdf_panels.title',
      descriptionKey: 'calculator.walls_mdf_panels.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.walls',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.wallArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 10.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'panelWidth',
          labelKey: 'input.panelWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.2,
          required: true,
          order: 2,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.mdf_ne_dlya_vlazhnyh'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.obreshetka_s_shagom_40'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.krepite_na_klyaymery_ili'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.mdf_ne_dlya_vlazhnyh'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.obreshetka_s_shagom_40'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.krepite_na_klyaymery_ili'),
      ],
      useCase: CalculateMdfPanels(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'walls_mdf_panels',
        'walls',
        'tag.steny',
        'mdf',
        'panels',
      ],
    ),

  // 4. walls_pvc_panels - PVC панели
  CalculatorDefinitionV2(
      id: 'walls_pvc_panels',
      titleKey: 'calculator.walls_pvc_panels.title',
      descriptionKey: 'calculator.walls_pvc_panels.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.walls',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.wallArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 10.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'panelWidth',
          labelKey: 'input.panelWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.25,
          required: true,
          order: 2,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.paneli_ukladyvayte_ot_ugla'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ostavlyayte_temperaturnyy_zazor_5'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_startovyy_i_finishnyy'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.paneli_ukladyvayte_ot_ugla'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ostavlyayte_temperaturnyy_zazor_5'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_startovyy_i_finishnyy'),
      ],
      useCase: CalculatePvcPanels(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'walls',
        'tag.steny',
        'walls_pvc_panels',
        'pvc',
        'panels',
      ],
    ),

  // 5. walls_wallpaper - Обои
  CalculatorDefinitionV2(
      id: 'walls_wallpaper',
      titleKey: 'calculator.walls_wallpaper.title',
      descriptionKey: 'calculator.walls_wallpaper.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.walls',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 20.0,
          minValue: 1.0,
          maxValue: 500.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'rollWidth',
          labelKey: 'input.rollWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.53,
          minValue: 0.5,
          maxValue: 1.2,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'rollLength',
          labelKey: 'input.rollLength',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 10.05,
          minValue: 5.0,
          maxValue: 50.0,
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'rapport',
          labelKey: 'input.rapport',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 100.0,
          required: false,
          order: 4,
        ),
        const CalculatorField(
          key: 'wallHeight',
          labelKey: 'input.wallHeight',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 2.5,
          minValue: 2.0,
          maxValue: 5.0,
          required: true,
          order: 5,
        ),
        const CalculatorField(
          key: 'windowsArea',
          labelKey: 'input.windowsArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 100.0,
          required: false,
          order: 6,
        ),
        const CalculatorField(
          key: 'doorsArea',
          labelKey: 'input.doorsArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 50.0,
          required: false,
          order: 7,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.wallpaper.check_batch_number'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.wallpaper.start_from_window'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.wallpaper.temperature_humidity'),
      ],
      useCase: CalculateWallpaper(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'wallpaper',
        'walls',
        'tag.steny',
        'walls_wallpaper',
      ],
    ),

  // 6. walls_wood - Деревянная отделка (вагонка)
  CalculatorDefinitionV2(
      id: 'walls_wood',
      titleKey: 'calculator.walls_wood.title',
      descriptionKey: 'calculator.walls_wood.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.walls',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.wallArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 10.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'boardWidth',
          labelKey: 'input.boardWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.1,
          required: true,
          order: 2,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.dayte_vagonke_akklimatizirovatsya_48'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.obrabotayte_antiseptikom_pered_montazhom'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.krepite_na_klyaymery_dlya'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.dayte_vagonke_akklimatizirovatsya_48'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.obrabotayte_antiseptikom_pered_montazhom'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.krepite_na_klyaymery_dlya'),
      ],
      useCase: CalculateWoodWall(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'wood',
        'walls',
        'walls_wood',
        'tag.steny',
      ],
    ),
];
