import '../../core/enums/calculator_category.dart';
import '../../core/enums/field_input_type.dart';
import '../../core/enums/unit_type.dart';
import '../models/calculator_definition_v2.dart';
import '../models/calculator_field.dart';
import '../models/calculator_hint.dart';
import '../usecases/basement_canonical_adapter.dart';
import '../usecases/canonical_bridge.dart';
import 'calculator_constants.dart';

const _withFormwork = FieldDependency(
  fieldKey: 'wallFormworkMode',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withWaterproofing = FieldDependency(
  fieldKey: 'waterproofScope',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _massWaterproofing = FieldDependency(
  fieldKey: 'waterproofSystem',
  condition: DependencyCondition.equals,
  value: 1,
);
const _rollWaterproofing = FieldDependency(
  fieldKey: 'waterproofSystem',
  condition: DependencyCondition.equals,
  value: 2,
);
const _withInsulation = FieldDependency(
  fieldKey: 'insulationScope',
  condition: DependencyCondition.greaterThan,
  value: 0,
);

CalculatorField _number(
  String key,
  UnitType unit,
  double defaultValue,
  double min,
  double max,
  double step,
  String group,
  int order, {
  String? hint,
  FieldDependency? dependency,
  List<FieldDependency>? dependencies,
}) {
  return CalculatorField(
    key: key,
    labelKey: 'input.basement.$key',
    hintKey: hint == null ? null : 'input.basement.$key.hint',
    unitType: unit,
    defaultValue: defaultValue,
    minValue: min,
    maxValue: max,
    step: step,
    group: group,
    order: order,
    dependency: dependency,
    dependencies: dependencies,
  );
}

CalculatorField _select(
  String key,
  double defaultValue,
  String group,
  int order,
  List<FieldOption> options, {
  FieldDependency? dependency,
}) {
  return CalculatorField(
    key: key,
    labelKey: 'input.basement.$key',
    hintKey: 'input.basement.$key.hint',
    unitType: UnitType.pieces,
    inputType: FieldInputType.select,
    defaultValue: defaultValue,
    minValue: options.first.value,
    maxValue: options.last.value,
    group: group,
    order: order,
    options: options,
    dependency: dependency,
  );
}

final basementCalculatorV2 = CalculatorDefinitionV2(
  id: 'foundation_basement',
  titleKey: calculatorTitleKey('foundation_basement'),
  descriptionKey: calculatorDescriptionKey('foundation_basement'),
  category: CalculatorCategory.exterior,
  subCategoryKey: 'subcategory.basement',
  iconName: 'foundation',
  accentColor: kCalculatorAccentColor,
  complexity: 3,
  popularity: 48,
  tags: const [
    'подвал',
    'цокольный этаж',
    'бетон',
    'монолит',
    'фундамент',
    'basement',
  ],
  fields: [
    _number(
      'length',
      UnitType.meters,
      8,
      3,
      30,
      0.1,
      'basement_walls',
      10,
      hint: 'project',
    ),
    _number(
      'width',
      UnitType.meters,
      6,
      3,
      20,
      0.1,
      'basement_walls',
      11,
      hint: 'project',
    ),
    _number(
      'depth',
      UnitType.meters,
      2.5,
      1.5,
      5,
      0.1,
      'basement_walls',
      12,
      hint: 'project',
    ),
    _number(
      'wallThickness',
      UnitType.millimeters,
      200,
      100,
      1000,
      10,
      'basement_walls',
      13,
      hint: 'project',
    ),
    _number(
      'wallOpeningsAreaM2',
      UnitType.squareMeters,
      0,
      0,
      200,
      0.1,
      'basement_walls',
      14,
      hint: 'project',
    ),
    _number(
      'floorLength',
      UnitType.meters,
      8,
      3,
      35,
      0.1,
      'basement_floor',
      20,
      hint: 'project',
    ),
    _number(
      'floorWidth',
      UnitType.meters,
      6,
      3,
      25,
      0.1,
      'basement_floor',
      21,
      hint: 'project',
    ),
    _number(
      'floorThickness',
      UnitType.millimeters,
      150,
      100,
      1000,
      10,
      'basement_floor',
      22,
      hint: 'project',
    ),
    _number(
      'floorConcreteReservePercent',
      UnitType.percent,
      5,
      0,
      20,
      1,
      'basement_concrete',
      30,
    ),
    _number(
      'wallConcreteReservePercent',
      UnitType.percent,
      5,
      0,
      20,
      1,
      'basement_concrete',
      31,
    ),
    _select('readyMixOrderStepM3', 0.1, 'basement_concrete', 32, const [
      FieldOption(value: 0.1, labelKey: 'input.readyMixOrderStepM3.01'),
      FieldOption(value: 0.5, labelKey: 'input.readyMixOrderStepM3.05'),
      FieldOption(value: 1, labelKey: 'input.readyMixOrderStepM3.10'),
    ]),
    _number(
      'floorDeliveryAllowanceM3',
      UnitType.cubicMeters,
      0,
      0,
      5,
      0.1,
      'basement_concrete',
      33,
      hint: 'supplier',
    ),
    _number(
      'wallDeliveryAllowanceM3',
      UnitType.cubicMeters,
      0,
      0,
      5,
      0.1,
      'basement_concrete',
      34,
      hint: 'supplier',
    ),
    _number(
      'floorRebarProjectKg',
      UnitType.kilograms,
      0,
      0,
      100000,
      1,
      'basement_rebar',
      40,
      hint: 'project',
    ),
    _number(
      'wallRebarProjectKg',
      UnitType.kilograms,
      0,
      0,
      100000,
      1,
      'basement_rebar',
      41,
      hint: 'project',
    ),
    _number(
      'rebarReservePercent',
      UnitType.percent,
      0,
      0,
      30,
      1,
      'basement_rebar',
      42,
      hint: 'project',
    ),
    _select('rebarOrderStepKg', 1, 'basement_rebar', 43, const [
      FieldOption(value: 1, labelKey: 'input.basement.rebarOrderStepKg.1'),
      FieldOption(value: 10, labelKey: 'input.basement.rebarOrderStepKg.10'),
      FieldOption(value: 50, labelKey: 'input.basement.rebarOrderStepKg.50'),
    ]),
    _select('wallFormworkMode', 0, 'basement_formwork', 50, const [
      FieldOption(value: 0, labelKey: 'input.basement.scope.none'),
      FieldOption(value: 1, labelKey: 'input.basement.formwork.outer'),
      FieldOption(value: 2, labelKey: 'input.basement.formwork.inner'),
      FieldOption(value: 3, labelKey: 'input.basement.formwork.both'),
    ]),
    _number(
      'formworkReservePercent',
      UnitType.percent,
      10,
      0,
      30,
      1,
      'basement_formwork',
      51,
      dependency: _withFormwork,
    ),
    _number(
      'formworkSheetAreaM2',
      UnitType.squareMeters,
      2.88,
      0.1,
      20,
      0.01,
      'basement_formwork',
      52,
      hint: 'product',
      dependency: _withFormwork,
    ),
    _select('waterproofScope', 0, 'basement_waterproofing', 60, const [
      FieldOption(value: 0, labelKey: 'input.basement.scope.none'),
      FieldOption(value: 1, labelKey: 'input.basement.scope.walls'),
      FieldOption(value: 2, labelKey: 'input.basement.scope.floor'),
      FieldOption(value: 3, labelKey: 'input.basement.scope.both'),
    ]),
    _select(
      'waterproofSystem',
      1,
      'basement_waterproofing',
      61,
      const [
        FieldOption(value: 1, labelKey: 'input.basement.waterproof.mass'),
        FieldOption(value: 2, labelKey: 'input.basement.waterproof.roll'),
      ],
      dependency: _withWaterproofing,
    ),
    _number(
      'waterproofWallHeightM',
      UnitType.meters,
      2.5,
      0,
      5,
      0.1,
      'basement_waterproofing',
      62,
      dependency: _withWaterproofing,
    ),
    _number(
      'waterproofReservePercent',
      UnitType.percent,
      15,
      0,
      50,
      1,
      'basement_waterproofing',
      63,
      dependency: _withWaterproofing,
    ),
    _number(
      'waterproofConsumptionKgM2',
      UnitType.kilograms,
      0,
      0,
      20,
      0.01,
      'basement_waterproofing',
      64,
      hint: 'product',
      dependencies: const [_withWaterproofing, _massWaterproofing],
    ),
    _number(
      'waterproofPackageKg',
      UnitType.kilograms,
      0,
      0,
      200,
      0.1,
      'basement_waterproofing',
      65,
      hint: 'product',
      dependencies: const [_withWaterproofing, _massWaterproofing],
    ),
    _number(
      'waterproofLayers',
      UnitType.pieces,
      1,
      1,
      5,
      1,
      'basement_waterproofing',
      66,
      hint: 'project',
      dependencies: const [_withWaterproofing, _rollWaterproofing],
    ),
    _number(
      'waterproofRollAreaM2',
      UnitType.squareMeters,
      0,
      0,
      200,
      0.1,
      'basement_waterproofing',
      67,
      hint: 'product',
      dependencies: const [_withWaterproofing, _rollWaterproofing],
    ),
    _select('insulationScope', 0, 'basement_insulation', 70, const [
      FieldOption(value: 0, labelKey: 'input.basement.scope.none'),
      FieldOption(value: 1, labelKey: 'input.basement.scope.walls'),
      FieldOption(value: 2, labelKey: 'input.basement.scope.floor'),
      FieldOption(value: 3, labelKey: 'input.basement.scope.both'),
    ]),
    _number(
      'insulationWallHeightM',
      UnitType.meters,
      2.5,
      0,
      5,
      0.1,
      'basement_insulation',
      71,
      dependency: _withInsulation,
    ),
    _number(
      'insulationLayers',
      UnitType.pieces,
      1,
      1,
      5,
      1,
      'basement_insulation',
      72,
      hint: 'project',
      dependency: _withInsulation,
    ),
    _number(
      'insulationReservePercent',
      UnitType.percent,
      5,
      0,
      30,
      1,
      'basement_insulation',
      73,
      dependency: _withInsulation,
    ),
    _number(
      'insulationBoardAreaM2',
      UnitType.squareMeters,
      0.72,
      0.1,
      5,
      0.01,
      'basement_insulation',
      74,
      hint: 'product',
      dependency: _withInsulation,
    ),
  ],
  beforeHints: const [
    CalculatorHint(
      type: HintType.warning,
      messageKey: 'hint.foundation.basement.before.project',
    ),
    CalculatorHint(
      type: HintType.info,
      messageKey: 'hint.foundation.basement.before.separate_pours',
    ),
  ],
  afterHints: const [
    CalculatorHint(
      type: HintType.tip,
      messageKey: 'hint.foundation.basement.after.check_order',
    ),
  ],
  useCase: const CanonicalBridgeUseCase(calculateCanonicalBasement),
);
