import '../../core/enums/calculator_category.dart';
import '../../core/enums/field_input_type.dart';
import '../../core/enums/unit_type.dart';
import '../models/calculator_definition_v2.dart';
import '../models/calculator_field.dart';
import '../models/calculator_hint.dart';
import '../usecases/canonical_bridge.dart';
import '../usecases/concrete_canonical_adapter.dart';
import 'calculator_constants.dart';

const concreteUniversalCalculatorV2 = CalculatorDefinitionV2(
  id: 'concrete_universal',
  titleKey: 'calculator.concrete_universal.title',
  descriptionKey: 'calculator.concrete_universal.description',
  category: CalculatorCategory.exterior,
  subCategoryKey: 'subcategory.concrete',
  tags: ['бетон', 'замес', 'цемент', 'песок', 'щебень', 'concrete'],
  accentColor: kCalculatorAccentColor,
  useCase: CanonicalBridgeUseCase(calculateCanonicalConcrete),
  fields: [
    CalculatorField(
      key: 'inputMode',
      labelKey: 'input.concreteInputMode',
      unitType: UnitType.pieces,
      inputType: FieldInputType.select,
      defaultValue: 0,
      minValue: 0,
      maxValue: 1,
      required: true,
      order: 1,
      options: [
        FieldOption(value: 0, labelKey: 'input.concreteInputMode.volume'),
        FieldOption(value: 1, labelKey: 'input.concreteInputMode.area'),
      ],
    ),
    CalculatorField(
      key: 'concreteVolume',
      labelKey: 'input.concreteVolume',
      hintKey: 'input.concreteVolume.hint',
      unitType: UnitType.cubicMeters,
      defaultValue: 5,
      minValue: 0.1,
      maxValue: 100,
      step: 0.1,
      required: true,
      order: 2,
      dependency: FieldDependency(
        fieldKey: 'inputMode',
        condition: DependencyCondition.equals,
        value: 0,
      ),
    ),
    CalculatorField(
      key: 'area',
      labelKey: 'input.concreteArea',
      hintKey: 'input.concreteArea.hint',
      unitType: UnitType.squareMeters,
      defaultValue: 20,
      minValue: 0.1,
      maxValue: 1000,
      step: 0.1,
      required: true,
      order: 2,
      dependency: FieldDependency(
        fieldKey: 'inputMode',
        condition: DependencyCondition.equals,
        value: 1,
      ),
    ),
    CalculatorField(
      key: 'thickness',
      labelKey: 'input.concreteThickness',
      hintKey: 'input.concreteThickness.hint',
      unitType: UnitType.millimeters,
      defaultValue: 200,
      minValue: 50,
      maxValue: 1000,
      step: 10,
      required: true,
      order: 3,
      dependency: FieldDependency(
        fieldKey: 'inputMode',
        condition: DependencyCondition.equals,
        value: 1,
      ),
    ),
    CalculatorField(
      key: 'concreteGrade',
      labelKey: 'input.concreteGrade',
      hintKey: 'input.concreteGrade.hint',
      unitType: UnitType.pieces,
      inputType: FieldInputType.select,
      defaultValue: 3,
      minValue: 1,
      maxValue: 7,
      required: true,
      order: 4,
      options: [
        FieldOption(value: 1, labelKey: 'input.concreteGrade.m100'),
        FieldOption(value: 2, labelKey: 'input.concreteGrade.m150'),
        FieldOption(value: 3, labelKey: 'input.concreteGrade.m200'),
        FieldOption(value: 4, labelKey: 'input.concreteGrade.m250'),
        FieldOption(value: 5, labelKey: 'input.concreteGrade.m300'),
        FieldOption(value: 6, labelKey: 'input.concreteGrade.m350'),
        FieldOption(value: 7, labelKey: 'input.concreteGrade.m400'),
      ],
    ),
    CalculatorField(
      key: 'manualMix',
      labelKey: 'input.manualMix',
      hintKey: 'input.manualMix.hint',
      unitType: UnitType.pieces,
      inputType: FieldInputType.switch_,
      defaultValue: 0,
      minValue: 0,
      maxValue: 1,
      required: false,
      order: 5,
    ),
    CalculatorField(
      key: 'readyMixOrderStepM3',
      labelKey: 'input.readyMixOrderStepM3',
      hintKey: 'input.readyMixOrderStepM3.hint',
      unitType: UnitType.cubicMeters,
      inputType: FieldInputType.select,
      defaultValue: 0.1,
      minValue: 0.1,
      maxValue: 1,
      required: true,
      order: 6,
      options: [
        FieldOption(value: 0.1, labelKey: 'input.readyMixOrderStepM3.01'),
        FieldOption(value: 0.5, labelKey: 'input.readyMixOrderStepM3.05'),
        FieldOption(value: 1, labelKey: 'input.readyMixOrderStepM3.10'),
      ],
    ),
    CalculatorField(
      key: 'reserve',
      labelKey: 'input.reserve',
      hintKey: 'input.concreteReserve.hint',
      unitType: UnitType.percent,
      defaultValue: 5,
      minValue: 0,
      maxValue: 20,
      step: 1,
      required: false,
      order: 7,
    ),
  ],
  beforeHints: [
    CalculatorHint(
      type: HintType.info,
      messageKey: 'hint.concrete.before.grade',
    ),
    CalculatorHint(
      type: HintType.tip,
      messageKey: 'hint.concrete.before.reserve',
    ),
  ],
  afterHints: [
    CalculatorHint(
      type: HintType.important,
      messageKey: 'hint.concrete.after.curing',
    ),
    CalculatorHint(
      type: HintType.warning,
      messageKey: 'hint.concrete.after.temperature',
    ),
  ],
);
