import '../../core/enums/calculator_category.dart';
import '../../core/enums/field_input_type.dart';
import '../../core/enums/unit_type.dart';
import '../models/calculator_definition_v2.dart';
import '../models/calculator_field.dart';
import '../models/calculator_hint.dart';
import '../usecases/canonical_bridge.dart';
import '../usecases/drywall_ceiling_canonical_adapter.dart';
import 'calculator_constants.dart';

const _byDimensions = FieldDependency(
  fieldKey: 'inputMode',
  condition: DependencyCondition.equals,
  value: 0,
);
const _byArea = FieldDependency(
  fieldKey: 'inputMode',
  condition: DependencyCondition.equals,
  value: 1,
);

CalculatorField _number(
  String key,
  UnitType unit,
  double defaultValue,
  double min,
  double max,
  double step,
  String group,
  int order, {
  bool hint = false,
  FieldDependency? dependency,
}) {
  return CalculatorField(
    key: key,
    labelKey: 'input.drywallCeiling.$key',
    hintKey: hint ? 'input.drywallCeiling.$key.hint' : null,
    unitType: unit,
    inputType: FieldInputType.number,
    defaultValue: defaultValue,
    minValue: min,
    maxValue: max,
    step: step,
    group: group,
    order: order,
    required: true,
    dependency: dependency,
  );
}

CalculatorField _select(
  String key,
  double defaultValue,
  String group,
  int order,
  List<FieldOption> options, {
  bool hint = false,
  FieldInputType inputType = FieldInputType.select,
}) {
  return CalculatorField(
    key: key,
    labelKey: 'input.drywallCeiling.$key',
    hintKey: hint ? 'input.drywallCeiling.$key.hint' : null,
    unitType: UnitType.pieces,
    inputType: inputType,
    defaultValue: defaultValue,
    minValue: options.first.value,
    maxValue: options.last.value,
    group: group,
    order: order,
    required: true,
    options: options,
  );
}

final drywallCeilingCalculatorV2 = CalculatorDefinitionV2(
  id: 'drywall_ceiling',
  titleKey: 'calculator.ceilings_gkl.title',
  descriptionKey: 'calculator.ceilings_gkl.description',
  category: CalculatorCategory.interior,
  subCategoryKey: 'subcategory.ceilings',
  iconName: 'grid_view',
  accentColor: kCalculatorAccentColor,
  complexity: 3,
  popularity: 10,
  tags: const [
    'tag.vnutrennyaya_otdelka',
    'tag.potolki',
    'gkl',
    'knauf',
    'p113',
  ],
  fields: [
    _select(
      'inputMode',
      0,
      'drywall_ceiling_geometry',
      10,
      const [
        FieldOption(
          value: 0,
          labelKey: 'input.drywallCeiling.inputMode.dimensions',
        ),
        FieldOption(value: 1, labelKey: 'input.drywallCeiling.inputMode.area'),
      ],
      hint: true,
      inputType: FieldInputType.radio,
    ),
    _number(
      'length',
      UnitType.meters,
      5,
      1,
      20,
      0.1,
      'drywall_ceiling_geometry',
      11,
      dependency: _byDimensions,
    ),
    _number(
      'width',
      UnitType.meters,
      4,
      1,
      20,
      0.1,
      'drywall_ceiling_geometry',
      12,
      dependency: _byDimensions,
    ),
    _number(
      'area',
      UnitType.squareMeters,
      20,
      1,
      500,
      0.1,
      'drywall_ceiling_geometry',
      13,
      dependency: _byArea,
    ),
    _number(
      'perimeterM',
      UnitType.linearMeters,
      18,
      1,
      500,
      0.1,
      'drywall_ceiling_geometry',
      14,
      hint: true,
      dependency: _byArea,
    ),
    _select('layers', 1, 'drywall_ceiling_system', 20, const [
      FieldOption(value: 1, labelKey: 'input.drywallCeiling.layers.single'),
      FieldOption(value: 2, labelKey: 'input.drywallCeiling.layers.double'),
    ], hint: true),
    _number(
      'sheetWidthMm',
      UnitType.millimeters,
      1200,
      600,
      1500,
      50,
      'drywall_ceiling_sheets',
      30,
    ),
    _number(
      'sheetLengthMm',
      UnitType.millimeters,
      2500,
      1200,
      4000,
      100,
      'drywall_ceiling_sheets',
      31,
    ),
    _number(
      'sheetReservePercent',
      UnitType.percent,
      10,
      0,
      30,
      1,
      'drywall_ceiling_sheets',
      32,
      hint: true,
    ),
    _number(
      'profileLengthM',
      UnitType.meters,
      3,
      2,
      6,
      0.1,
      'drywall_ceiling_profile',
      40,
      hint: true,
    ),
    _number(
      'profileReservePercent',
      UnitType.percent,
      5,
      0,
      30,
      1,
      'drywall_ceiling_profile',
      41,
    ),
    _number(
      'fastenerReservePercent',
      UnitType.percent,
      5,
      0,
      30,
      1,
      'drywall_ceiling_fasteners',
      50,
    ),
    _number(
      'tnScrewPackCount',
      UnitType.pieces,
      1000,
      1,
      10000,
      1,
      'drywall_ceiling_fasteners',
      51,
      hint: true,
    ),
    _number(
      'lnScrewPackCount',
      UnitType.pieces,
      100,
      1,
      5000,
      1,
      'drywall_ceiling_fasteners',
      52,
    ),
    _number(
      'jointTapeRollM',
      UnitType.meters,
      50,
      1,
      200,
      1,
      'drywall_ceiling_finish',
      60,
    ),
    _number(
      'sealingTapeRollM',
      UnitType.meters,
      30,
      1,
      200,
      1,
      'drywall_ceiling_finish',
      61,
    ),
    _number(
      'separatingTapeRollM',
      UnitType.meters,
      50,
      1,
      200,
      1,
      'drywall_ceiling_finish',
      62,
    ),
    _number(
      'puttyBagKg',
      UnitType.kilograms,
      25,
      1,
      50,
      1,
      'drywall_ceiling_finish',
      63,
    ),
    _number(
      'primerCanL',
      UnitType.liters,
      5,
      0.5,
      20,
      0.5,
      'drywall_ceiling_finish',
      64,
    ),
    _number(
      'finishReservePercent',
      UnitType.percent,
      10,
      0,
      30,
      1,
      'drywall_ceiling_finish',
      65,
    ),
  ],
  beforeHints: const [
    CalculatorHint(
      type: HintType.warning,
      messageKey: 'hint.drywallCeiling.before.system',
    ),
    CalculatorHint(
      type: HintType.info,
      messageKey: 'hint.drywallCeiling.before.project',
    ),
  ],
  afterHints: const [
    CalculatorHint(
      type: HintType.tip,
      messageKey: 'hint.drywallCeiling.after.packages',
    ),
  ],
  useCase: const CanonicalBridgeUseCase(calculateCanonicalDrywallCeiling),
);
