import '../../core/enums/calculator_category.dart';
import '../../core/enums/field_input_type.dart';
import '../../core/enums/unit_type.dart';
import '../models/calculator_definition_v2.dart';
import '../models/calculator_field.dart';
import '../models/calculator_hint.dart';
import '../usecases/canonical_bridge.dart';
import '../usecases/frame_house_canonical_adapter.dart';
import 'calculator_constants.dart';

const _withFraming = FieldDependency(
  fieldKey: 'framingProjectLengthM',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withOuter = FieldDependency(
  fieldKey: 'outerSheathingEnabled',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withInner = FieldDependency(
  fieldKey: 'innerSheathingEnabled',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withInsulation = FieldDependency(
  fieldKey: 'insulationEnabled',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withVapor = FieldDependency(
  fieldKey: 'vaporBarrierEnabled',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withWind = FieldDependency(
  fieldKey: 'windBarrierEnabled',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withTape = FieldDependency(
  fieldKey: 'tapeProjectM',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withSheathingFasteners = FieldDependency(
  fieldKey: 'sheathingFastenersProjectPcs',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withFramingFasteners = FieldDependency(
  fieldKey: 'framingFastenersProjectPcs',
  condition: DependencyCondition.greaterThan,
  value: 0,
);

CalculatorField _number(
  String key,
  UnitType unit,
  double defaultValue,
  double min,
  double max,
  double step,
  String group,
  int order, {
  bool hint = false,
  FieldDependency? dependency,
}) {
  return CalculatorField(
    key: key,
    labelKey: 'input.frameHouse.$key',
    hintKey: hint ? 'input.frameHouse.$key.hint' : null,
    unitType: unit,
    defaultValue: defaultValue,
    minValue: min,
    maxValue: max,
    step: step,
    group: group,
    order: order,
    dependency: dependency,
  );
}

CalculatorField _select(
  String key,
  double defaultValue,
  String group,
  int order,
  List<FieldOption> options, {
  bool hint = false,
}) {
  return CalculatorField(
    key: key,
    labelKey: 'input.frameHouse.$key',
    hintKey: hint ? 'input.frameHouse.$key.hint' : null,
    unitType: UnitType.pieces,
    inputType: FieldInputType.select,
    defaultValue: defaultValue,
    minValue: options.first.value,
    maxValue: options.last.value,
    group: group,
    order: order,
    options: options,
  );
}

const _notIncluded = FieldOption(
  value: 0,
  labelKey: 'input.frameHouse.include.none',
);
const _included = FieldOption(
  value: 1,
  labelKey: 'input.frameHouse.include.project',
);

final frameHouseCalculatorV2 = CalculatorDefinitionV2(
  id: 'frame_house',
  titleKey: calculatorTitleKey('frame_house'),
  descriptionKey: calculatorDescriptionKey('frame_house'),
  category: CalculatorCategory.exterior,
  subCategoryKey: 'subcategory.walls',
  iconName: 'house',
  accentColor: kCalculatorAccentColor,
  complexity: 3,
  popularity: 65,
  tags: const [
    'каркасный дом',
    'каркасник',
    'пиломатериал',
    'обшивка',
    'утеплитель',
    'мембраны',
    'смета',
  ],
  fields: [
    _number(
      'wallLength',
      UnitType.meters,
      30,
      1,
      200,
      0.1,
      'frame_house_area',
      10,
      hint: true,
    ),
    _number(
      'wallHeight',
      UnitType.meters,
      2.7,
      1,
      8,
      0.1,
      'frame_house_area',
      11,
    ),
    _number(
      'openingsArea',
      UnitType.squareMeters,
      10,
      0,
      500,
      0.1,
      'frame_house_area',
      12,
      hint: true,
    ),
    _select('surfaceAreaBasis', 0, 'frame_house_area', 13, const [
      FieldOption(
        value: 0,
        labelKey: 'input.frameHouse.surfaceAreaBasis.gross',
      ),
      FieldOption(value: 1, labelKey: 'input.frameHouse.surfaceAreaBasis.net'),
    ], hint: true),
    _number(
      'framingProjectLengthM',
      UnitType.linearMeters,
      0,
      0,
      100000,
      0.1,
      'frame_house_lumber',
      20,
      hint: true,
    ),
    _number(
      'framingReservePercent',
      UnitType.percent,
      5,
      0,
      30,
      1,
      'frame_house_lumber',
      21,
      dependency: _withFraming,
    ),
    _number(
      'framingBoardLengthM',
      UnitType.meters,
      6,
      0.1,
      20,
      0.1,
      'frame_house_lumber',
      22,
      hint: true,
      dependency: _withFraming,
    ),
    _select('outerSheathingEnabled', 1, 'frame_house_outer', 30, const [
      _notIncluded,
      _included,
    ], hint: true),
    _number(
      'outerSheetAreaM2',
      UnitType.squareMeters,
      3.125,
      0.1,
      20,
      0.001,
      'frame_house_outer',
      31,
      hint: true,
      dependency: _withOuter,
    ),
    _number(
      'outerSheathingLayers',
      UnitType.pieces,
      1,
      1,
      4,
      1,
      'frame_house_outer',
      32,
      dependency: _withOuter,
    ),
    _number(
      'outerSheathingReservePercent',
      UnitType.percent,
      10,
      0,
      50,
      1,
      'frame_house_outer',
      33,
      dependency: _withOuter,
    ),
    _select('innerSheathingEnabled', 0, 'frame_house_inner', 40, const [
      _notIncluded,
      _included,
    ]),
    _number(
      'innerSheetAreaM2',
      UnitType.squareMeters,
      3,
      0.1,
      20,
      0.001,
      'frame_house_inner',
      41,
      hint: true,
      dependency: _withInner,
    ),
    _number(
      'innerSheathingLayers',
      UnitType.pieces,
      1,
      1,
      4,
      1,
      'frame_house_inner',
      42,
      dependency: _withInner,
    ),
    _number(
      'innerSheathingReservePercent',
      UnitType.percent,
      10,
      0,
      50,
      1,
      'frame_house_inner',
      43,
      dependency: _withInner,
    ),
    _select('insulationEnabled', 0, 'frame_house_insulation', 50, const [
      _notIncluded,
      _included,
    ]),
    _number(
      'insulationPackageAreaM2',
      UnitType.squareMeters,
      0,
      0,
      100,
      0.01,
      'frame_house_insulation',
      51,
      hint: true,
      dependency: _withInsulation,
    ),
    _number(
      'insulationLayers',
      UnitType.pieces,
      1,
      1,
      10,
      1,
      'frame_house_insulation',
      52,
      dependency: _withInsulation,
    ),
    _number(
      'insulationReservePercent',
      UnitType.percent,
      5,
      0,
      30,
      1,
      'frame_house_insulation',
      53,
      dependency: _withInsulation,
    ),
    _select('vaporBarrierEnabled', 0, 'frame_house_vapor', 60, const [
      _notIncluded,
      _included,
    ]),
    _number(
      'vaporRollAreaM2',
      UnitType.squareMeters,
      0,
      0,
      500,
      0.1,
      'frame_house_vapor',
      61,
      hint: true,
      dependency: _withVapor,
    ),
    _number(
      'vaporLayers',
      UnitType.pieces,
      1,
      1,
      5,
      1,
      'frame_house_vapor',
      62,
      dependency: _withVapor,
    ),
    _number(
      'vaporReservePercent',
      UnitType.percent,
      15,
      0,
      50,
      1,
      'frame_house_vapor',
      63,
      dependency: _withVapor,
    ),
    _select('windBarrierEnabled', 0, 'frame_house_wind', 70, const [
      _notIncluded,
      _included,
    ]),
    _number(
      'windRollAreaM2',
      UnitType.squareMeters,
      0,
      0,
      500,
      0.1,
      'frame_house_wind',
      71,
      hint: true,
      dependency: _withWind,
    ),
    _number(
      'windLayers',
      UnitType.pieces,
      1,
      1,
      5,
      1,
      'frame_house_wind',
      72,
      dependency: _withWind,
    ),
    _number(
      'windReservePercent',
      UnitType.percent,
      15,
      0,
      50,
      1,
      'frame_house_wind',
      73,
      dependency: _withWind,
    ),
    _number(
      'tapeProjectM',
      UnitType.linearMeters,
      0,
      0,
      100000,
      0.1,
      'frame_house_tape',
      80,
      hint: true,
    ),
    _number(
      'tapeReservePercent',
      UnitType.percent,
      10,
      0,
      50,
      1,
      'frame_house_tape',
      81,
      dependency: _withTape,
    ),
    _number(
      'tapeRollLengthM',
      UnitType.meters,
      0,
      0,
      1000,
      0.1,
      'frame_house_tape',
      82,
      hint: true,
      dependency: _withTape,
    ),
    _number(
      'sheathingFastenersProjectPcs',
      UnitType.pieces,
      0,
      0,
      1000000,
      1,
      'frame_house_fasteners',
      90,
      hint: true,
    ),
    _number(
      'sheathingFastenersReservePercent',
      UnitType.percent,
      5,
      0,
      30,
      1,
      'frame_house_fasteners',
      91,
      dependency: _withSheathingFasteners,
    ),
    _number(
      'sheathingFastenersPackagePcs',
      UnitType.pieces,
      0,
      0,
      100000,
      1,
      'frame_house_fasteners',
      92,
      hint: true,
      dependency: _withSheathingFasteners,
    ),
    _number(
      'framingFastenersProjectPcs',
      UnitType.pieces,
      0,
      0,
      1000000,
      1,
      'frame_house_fasteners',
      93,
      hint: true,
    ),
    _number(
      'framingFastenersReservePercent',
      UnitType.percent,
      5,
      0,
      30,
      1,
      'frame_house_fasteners',
      94,
      dependency: _withFramingFasteners,
    ),
    _number(
      'framingFastenersPackagePcs',
      UnitType.pieces,
      0,
      0,
      100000,
      1,
      'frame_house_fasteners',
      95,
      hint: true,
      dependency: _withFramingFasteners,
    ),
  ],
  beforeHints: const [
    CalculatorHint(
      type: HintType.warning,
      messageKey: 'hint.frame_house.before.project',
    ),
    CalculatorHint(
      type: HintType.info,
      messageKey: 'hint.frame_house.before.area',
    ),
  ],
  afterHints: const [
    CalculatorHint(
      type: HintType.tip,
      messageKey: 'hint.frame_house.after.split_lumber',
    ),
  ],
  useCase: const CanonicalBridgeUseCase(calculateCanonicalFrameHouse),
);
