// ignore_for_file: prefer_const_constructors

import '../../core/enums/calculator_category.dart';
import '../../core/enums/field_input_type.dart';
import '../../core/enums/unit_type.dart';
import '../models/calculator_definition_v2.dart';
import '../models/calculator_field.dart';
import 'calculator_constants.dart';
import '../usecases/canonical_bridge.dart';
import '../usecases/rebar_canonical_adapter.dart';

const _gridOnly = FieldDependency(
  fieldKey: 'structureType',
  condition: DependencyCondition.equals,
  value: 0,
);
const _frameOnly = FieldDependency(
  fieldKey: 'structureType',
  condition: DependencyCondition.equals,
  value: 1,
);

final rebarCalculatorV2 = CalculatorDefinitionV2(
  id: 'foundation_rebar',
  titleKey: calculatorTitleKey('foundation_rebar'),
  descriptionKey: calculatorDescriptionKey('foundation_rebar'),
  category: CalculatorCategory.exterior,
  subCategoryKey: 'subcategory.rebar',
  iconName: 'grid_on',
  accentColor: kCalculatorAccentColor,
  complexity: 3,
  popularity: 74,
  tags: ['арматура', 'сетка', 'каркас', 'вес', 'прутки', 'rebar'],
  fields: [
    CalculatorField(
      key: 'structureType',
      labelKey: 'input.rebar.structureType',
      hintKey: 'input.rebar.structureType.hint',
      unitType: UnitType.pieces,
      inputType: FieldInputType.radio,
      defaultValue: 0,
      minValue: 0,
      maxValue: 1,
      group: 'rebar_scheme',
      order: 0,
      options: [
        FieldOption(value: 0, labelKey: 'input.rebar.structureType.grid'),
        FieldOption(value: 1, labelKey: 'input.rebar.structureType.frame'),
      ],
    ),
    CalculatorField(
      key: 'length',
      labelKey: 'input.rebar.length',
      unitType: UnitType.meters,
      defaultValue: 10,
      minValue: 1,
      maxValue: 50,
      step: 0.1,
      dependency: _gridOnly,
      group: 'rebar_grid',
      order: 10,
    ),
    CalculatorField(
      key: 'width',
      labelKey: 'input.rebar.width',
      unitType: UnitType.meters,
      defaultValue: 8,
      minValue: 1,
      maxValue: 50,
      step: 0.1,
      dependency: _gridOnly,
      group: 'rebar_grid',
      order: 11,
    ),
    CalculatorField(
      key: 'gridLayers',
      labelKey: 'input.rebar.gridLayers',
      unitType: UnitType.pieces,
      inputType: FieldInputType.select,
      defaultValue: 2,
      minValue: 1,
      maxValue: 2,
      dependency: _gridOnly,
      group: 'rebar_grid',
      order: 12,
      options: [
        FieldOption(value: 1, labelKey: 'input.rebar.gridLayers.1'),
        FieldOption(value: 2, labelKey: 'input.rebar.gridLayers.2'),
      ],
    ),
    CalculatorField(
      key: 'gridStepMm',
      labelKey: 'input.rebar.gridStepMm',
      hintKey: 'input.rebar.gridStepMm.hint',
      unitType: UnitType.millimeters,
      defaultValue: 200,
      minValue: 100,
      maxValue: 500,
      step: 10,
      dependency: _gridOnly,
      group: 'rebar_grid',
      order: 13,
    ),
    CalculatorField(
      key: 'edgeCoverMm',
      labelKey: 'input.rebar.edgeCoverMm',
      hintKey: 'input.rebar.edgeCoverMm.hint',
      unitType: UnitType.millimeters,
      defaultValue: 50,
      minValue: 0,
      maxValue: 150,
      step: 5,
      dependency: _gridOnly,
      group: 'rebar_grid',
      order: 14,
    ),
    CalculatorField(
      key: 'frameLengthM',
      labelKey: 'input.rebar.frameLengthM',
      hintKey: 'input.rebar.frameLengthM.hint',
      unitType: UnitType.meters,
      defaultValue: 36,
      minValue: 1,
      maxValue: 500,
      step: 0.1,
      dependency: _frameOnly,
      group: 'rebar_frame',
      order: 20,
    ),
    CalculatorField(
      key: 'longitudinalBars',
      labelKey: 'input.rebar.longitudinalBars',
      unitType: UnitType.pieces,
      defaultValue: 4,
      minValue: 2,
      maxValue: 16,
      step: 1,
      dependency: _frameOnly,
      group: 'rebar_frame',
      order: 21,
    ),
    CalculatorField(
      key: 'stirrupWidthMm',
      labelKey: 'input.rebar.stirrupWidthMm',
      unitType: UnitType.millimeters,
      defaultValue: 300,
      minValue: 100,
      maxValue: 2000,
      step: 10,
      dependency: _frameOnly,
      group: 'rebar_frame',
      order: 22,
    ),
    CalculatorField(
      key: 'stirrupHeightMm',
      labelKey: 'input.rebar.stirrupHeightMm',
      unitType: UnitType.millimeters,
      defaultValue: 300,
      minValue: 100,
      maxValue: 3000,
      step: 10,
      dependency: _frameOnly,
      group: 'rebar_frame',
      order: 23,
    ),
    CalculatorField(
      key: 'stirrupStepMm',
      labelKey: 'input.rebar.stirrupStepMm',
      unitType: UnitType.millimeters,
      defaultValue: 400,
      minValue: 100,
      maxValue: 1000,
      step: 10,
      dependency: _frameOnly,
      group: 'rebar_frame',
      order: 24,
    ),
    CalculatorField(
      key: 'stirrupDiameterMm',
      labelKey: 'input.rebar.stirrupDiameterMm',
      unitType: UnitType.millimeters,
      inputType: FieldInputType.select,
      defaultValue: 8,
      minValue: 6,
      maxValue: 12,
      dependency: _frameOnly,
      group: 'rebar_frame',
      order: 25,
      options: [
        FieldOption(value: 6, labelKey: 'input.rebar.diameter.6'),
        FieldOption(value: 8, labelKey: 'input.rebar.diameter.8'),
        FieldOption(value: 10, labelKey: 'input.rebar.diameter.10'),
        FieldOption(value: 12, labelKey: 'input.rebar.diameter.12'),
      ],
    ),
    CalculatorField(
      key: 'stirrupHookAllowanceMm',
      labelKey: 'input.rebar.stirrupHookAllowanceMm',
      hintKey: 'input.rebar.stirrupHookAllowanceMm.hint',
      unitType: UnitType.millimeters,
      defaultValue: 300,
      minValue: 0,
      maxValue: 1500,
      step: 10,
      dependency: _frameOnly,
      group: 'rebar_frame',
      order: 26,
    ),
    CalculatorField(
      key: 'mainDiameter',
      labelKey: 'input.rebar.mainDiameter',
      hintKey: 'input.rebar.mainDiameter.hint',
      unitType: UnitType.millimeters,
      inputType: FieldInputType.select,
      defaultValue: 12,
      minValue: 6,
      maxValue: 16,
      group: 'rebar_purchase',
      order: 30,
      options: [
        FieldOption(value: 6, labelKey: 'input.rebar.diameter.6'),
        FieldOption(value: 8, labelKey: 'input.rebar.diameter.8'),
        FieldOption(value: 10, labelKey: 'input.rebar.diameter.10'),
        FieldOption(value: 12, labelKey: 'input.rebar.diameter.12'),
        FieldOption(value: 14, labelKey: 'input.rebar.diameter.14'),
        FieldOption(value: 16, labelKey: 'input.rebar.diameter.16'),
      ],
    ),
    CalculatorField(
      key: 'reservePercent',
      labelKey: 'input.rebar.reservePercent',
      hintKey: 'input.rebar.reservePercent.hint',
      unitType: UnitType.percent,
      defaultValue: 10,
      minValue: 0,
      maxValue: 30,
      step: 1,
      group: 'rebar_purchase',
      order: 31,
    ),
    CalculatorField(
      key: 'rodLengthM',
      labelKey: 'input.rebar.rodLengthM',
      unitType: UnitType.meters,
      inputType: FieldInputType.select,
      defaultValue: 11.7,
      minValue: 6,
      maxValue: 12,
      group: 'rebar_purchase',
      order: 32,
      options: [
        FieldOption(value: 6, labelKey: 'input.rebar.rodLengthM.6'),
        FieldOption(value: 11.7, labelKey: 'input.rebar.rodLengthM.117'),
        FieldOption(value: 12, labelKey: 'input.rebar.rodLengthM.12'),
      ],
    ),
    CalculatorField(
      key: 'tieSharePercent',
      labelKey: 'input.rebar.tieSharePercent',
      unitType: UnitType.percent,
      inputType: FieldInputType.select,
      defaultValue: 100,
      minValue: 0,
      maxValue: 100,
      group: 'rebar_wire',
      order: 40,
      options: [
        FieldOption(value: 25, labelKey: 'input.rebar.tieSharePercent.25'),
        FieldOption(value: 50, labelKey: 'input.rebar.tieSharePercent.50'),
        FieldOption(value: 100, labelKey: 'input.rebar.tieSharePercent.100'),
      ],
    ),
    CalculatorField(
      key: 'wireLengthPerTieM',
      labelKey: 'input.rebar.wireLengthPerTieM',
      unitType: UnitType.meters,
      defaultValue: 0.3,
      minValue: 0.1,
      maxValue: 1,
      step: 0.05,
      group: 'rebar_wire',
      order: 41,
    ),
    CalculatorField(
      key: 'wireReservePercent',
      labelKey: 'input.rebar.wireReservePercent',
      unitType: UnitType.percent,
      defaultValue: 10,
      minValue: 0,
      maxValue: 50,
      step: 1,
      group: 'rebar_wire',
      order: 42,
    ),
    CalculatorField(
      key: 'wirePackageKg',
      labelKey: 'input.rebar.wirePackageKg',
      unitType: UnitType.kilograms,
      inputType: FieldInputType.select,
      defaultValue: 1,
      minValue: 1,
      maxValue: 10,
      group: 'rebar_wire',
      order: 43,
      options: [
        FieldOption(value: 1, labelKey: 'input.rebar.wirePackageKg.1'),
        FieldOption(value: 5, labelKey: 'input.rebar.wirePackageKg.5'),
        FieldOption(value: 10, labelKey: 'input.rebar.wirePackageKg.10'),
      ],
    ),
  ],
  useCase: CanonicalBridgeUseCase(calculateCanonicalRebar),
);
