import '../../core/enums/calculator_category.dart';
import '../../core/enums/field_input_type.dart';
import '../../core/enums/unit_type.dart';
import '../models/calculator_definition_v2.dart';
import '../models/calculator_field.dart';
import '../models/calculator_hint.dart';
import '../usecases/canonical_bridge.dart';
import '../usecases/sewage_canonical_adapter.dart';
import 'calculator_constants.dart';

const _preliminaryOnly = FieldDependency(
  fieldKey: 'calculationMode',
  condition: DependencyCondition.equals,
  value: 0,
);

const _projectOnly = FieldDependency(
  fieldKey: 'calculationMode',
  condition: DependencyCondition.equals,
  value: 1,
);

/// Септик: минимальный рабочий объём и проверка проектных исходных данных.
final sewageCalculatorV2 = CalculatorDefinitionV2(
  id: 'sewage',
  titleKey: calculatorTitleKey('sewage'),
  descriptionKey: calculatorDescriptionKey('sewage'),
  category: CalculatorCategory.exterior,
  subCategoryKey: 'subcategory.sewage',
  iconName: 'water_drop',
  accentColor: kCalculatorAccentColor,
  complexity: 3,
  popularity: 62,
  tags: const [
    'септик',
    'объём септика',
    'автономная канализация',
    'суточный приток',
  ],
  primaryResultKeys: const [
    'dailyFlowM3',
    'minimumWorkingVolumeM3',
    'selectedWorkingVolumeM3',
  ],
  resultLabelKeys: const {
    'dailyFlowM3': 'result.sewageDailyFlow',
    'minimumWorkingVolumeM3': 'result.sewageMinimumWorkingVolume',
    'selectedWorkingVolumeM3': 'result.sewageSelectedWorkingVolume',
  },
  fields: const [
    CalculatorField(
      key: 'calculationMode',
      labelKey: 'input.sewage.calculationMode',
      hintKey: 'input.sewage.calculationMode.hint',
      unitType: UnitType.dimensionless,
      inputType: FieldInputType.radio,
      defaultValue: 0,
      minValue: 0,
      maxValue: 1,
      iconName: 'assignment',
      group: 'sewage_flow',
      order: 1,
      options: [
        FieldOption(
          value: 0,
          labelKey: 'input.sewage.calculationMode.preliminary',
        ),
        FieldOption(value: 1, labelKey: 'input.sewage.calculationMode.project'),
      ],
    ),
    CalculatorField(
      key: 'equivalentResidents',
      labelKey: 'input.sewage.equivalentResidents',
      hintKey: 'input.sewage.equivalentResidents.hint',
      unitType: UnitType.dimensionless,
      defaultValue: 4,
      minValue: 1,
      maxValue: 100,
      step: 1,
      iconName: 'people',
      group: 'sewage_flow',
      order: 2,
    ),
    CalculatorField(
      key: 'wastewaterPerResidentL',
      labelKey: 'input.sewage.wastewaterPerResidentL',
      hintKey: 'input.sewage.wastewaterPerResidentL.hint',
      unitType: UnitType.dimensionless,
      defaultValue: 200,
      minValue: 1,
      maxValue: 2000,
      step: 1,
      iconName: 'water',
      group: 'sewage_flow',
      order: 3,
      dependency: _preliminaryOnly,
    ),
    CalculatorField(
      key: 'projectDailyFlowM3',
      labelKey: 'input.sewage.projectDailyFlowM3',
      hintKey: 'input.sewage.projectDailyFlowM3.hint',
      unitType: UnitType.dimensionless,
      defaultValue: 0.8,
      minValue: 0.001,
      maxValue: 100,
      step: 0.01,
      iconName: 'calculate',
      group: 'sewage_flow',
      order: 4,
      dependency: _projectOnly,
    ),
    CalculatorField(
      key: 'selectedWorkingVolumeM3',
      labelKey: 'input.sewage.selectedWorkingVolumeM3',
      hintKey: 'input.sewage.selectedWorkingVolumeM3.hint',
      unitType: UnitType.cubicMeters,
      defaultValue: 0,
      minValue: 0,
      maxValue: 1000,
      step: 0.1,
      iconName: 'inventory_2',
      group: 'sewage_system',
      order: 5,
      required: false,
    ),
    CalculatorField(
      key: 'selectedChamberCount',
      labelKey: 'input.sewage.selectedChamberCount',
      hintKey: 'input.sewage.selectedChamberCount.hint',
      unitType: UnitType.dimensionless,
      inputType: FieldInputType.select,
      defaultValue: 0,
      minValue: 0,
      maxValue: 3,
      iconName: 'view_column',
      group: 'sewage_system',
      order: 6,
      required: false,
      options: [
        FieldOption(value: 0, labelKey: 'input.sewage.chambers.unknown'),
        FieldOption(value: 1, labelKey: 'input.sewage.chambers.one'),
        FieldOption(value: 2, labelKey: 'input.sewage.chambers.two'),
        FieldOption(value: 3, labelKey: 'input.sewage.chambers.three'),
      ],
    ),
    CalculatorField(
      key: 'naturalTreatmentStatus',
      labelKey: 'input.sewage.naturalTreatmentStatus',
      hintKey: 'input.sewage.naturalTreatmentStatus.hint',
      unitType: UnitType.dimensionless,
      inputType: FieldInputType.select,
      defaultValue: 0,
      minValue: 0,
      maxValue: 2,
      iconName: 'landscape',
      group: 'sewage_site',
      order: 7,
      options: [
        FieldOption(value: 0, labelKey: 'input.sewage.status.unchecked'),
        FieldOption(value: 1, labelKey: 'input.sewage.treatment.confirmed'),
        FieldOption(value: 2, labelKey: 'input.sewage.treatment.engineered'),
      ],
    ),
    CalculatorField(
      key: 'groundwaterStatus',
      labelKey: 'input.sewage.groundwaterStatus',
      hintKey: 'input.sewage.groundwaterStatus.hint',
      unitType: UnitType.dimensionless,
      inputType: FieldInputType.select,
      defaultValue: 0,
      minValue: 0,
      maxValue: 2,
      iconName: 'waves',
      group: 'sewage_site',
      order: 8,
      options: [
        FieldOption(value: 0, labelKey: 'input.sewage.status.unchecked'),
        FieldOption(value: 1, labelKey: 'input.sewage.groundwater.confirmed'),
        FieldOption(value: 2, labelKey: 'input.sewage.groundwater.high'),
      ],
    ),
    CalculatorField(
      key: 'pipeLengthM',
      labelKey: 'input.sewage.pipeLengthM',
      hintKey: 'input.sewage.pipeLengthM.hint',
      unitType: UnitType.meters,
      defaultValue: 0,
      minValue: 0,
      maxValue: 1000,
      step: 0.1,
      iconName: 'route',
      group: 'sewage_purchase',
      order: 9,
      required: false,
    ),
    CalculatorField(
      key: 'pipeSectionLengthM',
      labelKey: 'input.sewage.pipeSectionLengthM',
      hintKey: 'input.sewage.pipeSectionLengthM.hint',
      unitType: UnitType.meters,
      defaultValue: 0,
      minValue: 0,
      maxValue: 30,
      step: 0.1,
      iconName: 'straighten',
      group: 'sewage_purchase',
      order: 10,
      required: false,
    ),
    CalculatorField(
      key: 'inspectionWellCount',
      labelKey: 'input.sewage.inspectionWellCount',
      unitType: UnitType.pieces,
      defaultValue: 0,
      minValue: 0,
      maxValue: 100,
      step: 1,
      iconName: 'plumbing',
      group: 'sewage_purchase',
      order: 11,
      required: false,
    ),
    CalculatorField(
      key: 'fittingCount',
      labelKey: 'input.sewage.fittingCount',
      hintKey: 'input.sewage.fittingCount.hint',
      unitType: UnitType.pieces,
      defaultValue: 0,
      minValue: 0,
      maxValue: 1000,
      step: 1,
      iconName: 'account_tree',
      group: 'sewage_purchase',
      order: 12,
      required: false,
    ),
  ],
  beforeHints: const [
    CalculatorHint(
      type: HintType.warning,
      messageKey: 'hint.sewage.preliminaryBoundary',
    ),
  ],
  afterHints: const [
    CalculatorHint(
      type: HintType.important,
      messageKey: 'hint.sewage.postTreatment',
    ),
    CalculatorHint(
      type: HintType.warning,
      messageKey: 'hint.sewage.noSitingDesign',
    ),
  ],
  useCase: const CanonicalBridgeUseCase(calculateCanonicalSewage),
);
