// ignore_for_file: prefer_const_constructors

import '../../core/enums/calculator_category.dart';
import '../../core/enums/field_input_type.dart';
import '../../core/enums/unit_type.dart';
import '../models/calculator_definition_v2.dart';
import '../models/calculator_field.dart';
import '../models/calculator_hint.dart';
import 'calculator_constants.dart';
import '../usecases/canonical_bridge.dart';
import '../usecases/foundation_slab_canonical_adapter.dart';

const _withSand = FieldDependency(
  fieldKey: 'sandLayerMm',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withGravel = FieldDependency(
  fieldKey: 'gravelLayerMm',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withGeotextile = FieldDependency(
  fieldKey: 'includeGeotextile',
  condition: DependencyCondition.equals,
  value: 1,
);
const _withInsulation = FieldDependency(
  fieldKey: 'insulationThickness',
  condition: DependencyCondition.greaterThan,
  value: 0,
);

final slabFoundationCalculatorV2 = CalculatorDefinitionV2(
  id: 'foundation_slab',
  titleKey: calculatorTitleKey('foundation_slab'),
  descriptionKey: calculatorDescriptionKey('foundation_slab'),
  category: CalculatorCategory.exterior,
  subCategoryKey: 'subcategory.slab',
  iconName: 'foundation',
  accentColor: kCalculatorAccentColor,
  complexity: 3,
  popularity: 85,
  tags: ['фундамент', 'плита', 'монолит', 'бетон', 'арматура', 'foundation'],
  fields: [
    CalculatorField(
      key: 'length',
      labelKey: 'input.foundationSlab.length',
      hintKey: 'input.foundationSlab.length.hint',
      unitType: UnitType.meters,
      defaultValue: 10,
      minValue: 1,
      maxValue: 50,
      step: 0.1,
      group: 'slab_geometry',
      order: 10,
    ),
    CalculatorField(
      key: 'width',
      labelKey: 'input.foundationSlab.width',
      hintKey: 'input.foundationSlab.width.hint',
      unitType: UnitType.meters,
      defaultValue: 6,
      minValue: 1,
      maxValue: 50,
      step: 0.1,
      group: 'slab_geometry',
      order: 11,
    ),
    CalculatorField(
      key: 'thickness',
      labelKey: 'input.foundationSlab.thickness',
      hintKey: 'input.foundationSlab.thickness.hint',
      unitType: UnitType.millimeters,
      defaultValue: 200,
      minValue: 100,
      maxValue: 500,
      step: 10,
      group: 'slab_geometry',
      order: 12,
    ),
    CalculatorField(
      key: 'concreteReservePercent',
      labelKey: 'input.foundationSlab.concreteReservePercent',
      hintKey: 'input.foundationSlab.concreteReservePercent.hint',
      unitType: UnitType.percent,
      defaultValue: 5,
      minValue: 0,
      maxValue: 20,
      step: 1,
      group: 'slab_concrete',
      order: 20,
    ),
    CalculatorField(
      key: 'readyMixOrderStepM3',
      labelKey: 'input.readyMixOrderStepM3',
      hintKey: 'input.readyMixOrderStepM3.hint',
      unitType: UnitType.cubicMeters,
      inputType: FieldInputType.select,
      defaultValue: 0.1,
      minValue: 0.1,
      maxValue: 1,
      group: 'slab_concrete',
      order: 21,
      options: [
        FieldOption(value: 0.1, labelKey: 'input.readyMixOrderStepM3.01'),
        FieldOption(value: 0.5, labelKey: 'input.readyMixOrderStepM3.05'),
        FieldOption(value: 1, labelKey: 'input.readyMixOrderStepM3.10'),
      ],
    ),
    CalculatorField(
      key: 'deliveryAllowanceM3',
      labelKey: 'input.stripFoundation.deliveryAllowanceM3',
      hintKey: 'input.stripFoundation.deliveryAllowanceM3.hint',
      unitType: UnitType.cubicMeters,
      defaultValue: 0,
      minValue: 0,
      maxValue: 5,
      step: 0.1,
      required: false,
      group: 'slab_concrete',
      order: 22,
    ),
    CalculatorField(
      key: 'gridLayers',
      labelKey: 'input.rebar.gridLayers',
      unitType: UnitType.pieces,
      inputType: FieldInputType.select,
      defaultValue: 2,
      minValue: 1,
      maxValue: 2,
      group: 'slab_rebar',
      order: 30,
      options: [
        FieldOption(value: 1, labelKey: 'input.rebar.gridLayers.1'),
        FieldOption(value: 2, labelKey: 'input.rebar.gridLayers.2'),
      ],
    ),
    CalculatorField(
      key: 'rebarDiam',
      labelKey: 'input.rebar.mainDiameter',
      hintKey: 'input.rebar.mainDiameter.hint',
      unitType: UnitType.millimeters,
      inputType: FieldInputType.select,
      defaultValue: 12,
      minValue: 6,
      maxValue: 16,
      group: 'slab_rebar',
      order: 31,
      options: [
        FieldOption(value: 6, labelKey: 'input.rebar.diameter.6'),
        FieldOption(value: 8, labelKey: 'input.rebar.diameter.8'),
        FieldOption(value: 10, labelKey: 'input.rebar.diameter.10'),
        FieldOption(value: 12, labelKey: 'input.rebar.diameter.12'),
        FieldOption(value: 14, labelKey: 'input.rebar.diameter.14'),
        FieldOption(value: 16, labelKey: 'input.rebar.diameter.16'),
      ],
    ),
    CalculatorField(
      key: 'rebarStep',
      labelKey: 'input.rebar.gridStepMm',
      hintKey: 'input.rebar.gridStepMm.hint',
      unitType: UnitType.millimeters,
      defaultValue: 200,
      minValue: 100,
      maxValue: 500,
      step: 10,
      group: 'slab_rebar',
      order: 32,
    ),
    CalculatorField(
      key: 'edgeCoverMm',
      labelKey: 'input.rebar.edgeCoverMm',
      hintKey: 'input.rebar.edgeCoverMm.hint',
      unitType: UnitType.millimeters,
      defaultValue: 50,
      minValue: 0,
      maxValue: 150,
      step: 5,
      group: 'slab_rebar',
      order: 33,
    ),
    CalculatorField(
      key: 'rebarReservePercent',
      labelKey: 'input.rebar.reservePercent',
      hintKey: 'input.rebar.reservePercent.hint',
      unitType: UnitType.percent,
      defaultValue: 10,
      minValue: 0,
      maxValue: 30,
      step: 1,
      group: 'slab_rebar_purchase',
      order: 40,
    ),
    CalculatorField(
      key: 'rodLengthM',
      labelKey: 'input.rebar.rodLengthM',
      unitType: UnitType.meters,
      inputType: FieldInputType.select,
      defaultValue: 11.7,
      minValue: 6,
      maxValue: 12,
      group: 'slab_rebar_purchase',
      order: 41,
      options: [
        FieldOption(value: 6, labelKey: 'input.rebar.rodLengthM.6'),
        FieldOption(value: 11.7, labelKey: 'input.rebar.rodLengthM.117'),
        FieldOption(value: 12, labelKey: 'input.rebar.rodLengthM.12'),
      ],
    ),
    CalculatorField(
      key: 'tieSharePercent',
      labelKey: 'input.rebar.tieSharePercent',
      unitType: UnitType.percent,
      inputType: FieldInputType.select,
      defaultValue: 100,
      minValue: 0,
      maxValue: 100,
      group: 'slab_wire',
      order: 50,
      options: [
        FieldOption(value: 25, labelKey: 'input.rebar.tieSharePercent.25'),
        FieldOption(value: 50, labelKey: 'input.rebar.tieSharePercent.50'),
        FieldOption(value: 100, labelKey: 'input.rebar.tieSharePercent.100'),
      ],
    ),
    CalculatorField(
      key: 'wireLengthPerTieM',
      labelKey: 'input.rebar.wireLengthPerTieM',
      unitType: UnitType.meters,
      defaultValue: 0.3,
      minValue: 0.1,
      maxValue: 1,
      step: 0.05,
      group: 'slab_wire',
      order: 51,
    ),
    CalculatorField(
      key: 'wireReservePercent',
      labelKey: 'input.rebar.wireReservePercent',
      unitType: UnitType.percent,
      defaultValue: 10,
      minValue: 0,
      maxValue: 50,
      step: 1,
      group: 'slab_wire',
      order: 52,
    ),
    CalculatorField(
      key: 'wirePackageKg',
      labelKey: 'input.rebar.wirePackageKg',
      unitType: UnitType.kilograms,
      inputType: FieldInputType.select,
      defaultValue: 1,
      minValue: 1,
      maxValue: 10,
      group: 'slab_wire',
      order: 53,
      options: [
        FieldOption(value: 1, labelKey: 'input.rebar.wirePackageKg.1'),
        FieldOption(value: 5, labelKey: 'input.rebar.wirePackageKg.5'),
        FieldOption(value: 10, labelKey: 'input.rebar.wirePackageKg.10'),
      ],
    ),
    CalculatorField(
      key: 'formworkHeightMm',
      labelKey: 'input.stripFoundation.formworkHeight',
      hintKey: 'input.foundationSlab.formworkHeightMm.hint',
      unitType: UnitType.millimeters,
      defaultValue: 200,
      minValue: 0,
      maxValue: 1000,
      step: 10,
      group: 'slab_formwork',
      order: 60,
    ),
    CalculatorField(
      key: 'formworkReservePercent',
      labelKey: 'input.foundationSlab.formworkReservePercent',
      unitType: UnitType.percent,
      defaultValue: 10,
      minValue: 0,
      maxValue: 30,
      step: 1,
      group: 'slab_formwork',
      order: 61,
    ),
    CalculatorField(
      key: 'sandLayerMm',
      labelKey: 'input.foundationSlab.sandLayerMm',
      hintKey: 'input.foundationSlab.compactedLayer.hint',
      unitType: UnitType.millimeters,
      defaultValue: 100,
      minValue: 0,
      maxValue: 500,
      step: 10,
      group: 'slab_preparation',
      order: 70,
    ),
    CalculatorField(
      key: 'sandOrderExtraPercent',
      labelKey: 'input.foundationSlab.sandOrderExtraPercent',
      hintKey: 'input.foundationSlab.orderExtraPercent.hint',
      unitType: UnitType.percent,
      defaultValue: 0,
      minValue: 0,
      maxValue: 50,
      step: 1,
      dependency: _withSand,
      group: 'slab_preparation',
      order: 71,
    ),
    CalculatorField(
      key: 'gravelLayerMm',
      labelKey: 'input.foundationSlab.gravelLayerMm',
      hintKey: 'input.foundationSlab.compactedLayer.hint',
      unitType: UnitType.millimeters,
      defaultValue: 150,
      minValue: 0,
      maxValue: 500,
      step: 10,
      group: 'slab_preparation',
      order: 72,
    ),
    CalculatorField(
      key: 'gravelOrderExtraPercent',
      labelKey: 'input.foundationSlab.gravelOrderExtraPercent',
      hintKey: 'input.foundationSlab.orderExtraPercent.hint',
      unitType: UnitType.percent,
      defaultValue: 0,
      minValue: 0,
      maxValue: 50,
      step: 1,
      dependency: _withGravel,
      group: 'slab_preparation',
      order: 73,
    ),
    CalculatorField(
      key: 'aggregateOrderStepM3',
      labelKey: 'input.foundationSlab.aggregateOrderStepM3',
      unitType: UnitType.cubicMeters,
      inputType: FieldInputType.select,
      defaultValue: 0.1,
      minValue: 0.1,
      maxValue: 1,
      group: 'slab_preparation',
      order: 74,
      options: [
        FieldOption(value: 0.1, labelKey: 'input.readyMixOrderStepM3.01'),
        FieldOption(value: 0.5, labelKey: 'input.readyMixOrderStepM3.05'),
        FieldOption(value: 1, labelKey: 'input.readyMixOrderStepM3.10'),
      ],
    ),
    CalculatorField(
      key: 'includeGeotextile',
      labelKey: 'input.foundationSlab.includeGeotextile',
      hintKey: 'input.foundationSlab.includeGeotextile.hint',
      unitType: UnitType.pieces,
      inputType: FieldInputType.switch_,
      defaultValue: 1,
      minValue: 0,
      maxValue: 1,
      group: 'slab_geotextile',
      order: 80,
    ),
    CalculatorField(
      key: 'geotextileReservePercent',
      labelKey: 'input.foundationSlab.geotextileReservePercent',
      unitType: UnitType.percent,
      defaultValue: 20,
      minValue: 0,
      maxValue: 50,
      step: 1,
      dependency: _withGeotextile,
      group: 'slab_geotextile',
      order: 81,
    ),
    CalculatorField(
      key: 'geotextileRollAreaM2',
      labelKey: 'input.foundationSlab.geotextileRollAreaM2',
      hintKey: 'input.foundationSlab.packageArea.hint',
      unitType: UnitType.squareMeters,
      defaultValue: 50,
      minValue: 10,
      maxValue: 500,
      step: 1,
      dependency: _withGeotextile,
      group: 'slab_geotextile',
      order: 82,
    ),
    CalculatorField(
      key: 'insulationThickness',
      labelKey: 'input.foundationSlab.insulationThickness',
      hintKey: 'input.foundationSlab.insulationThickness.hint',
      unitType: UnitType.millimeters,
      inputType: FieldInputType.select,
      defaultValue: 0,
      minValue: 0,
      maxValue: 200,
      required: false,
      group: 'slab_insulation',
      order: 90,
      options: [
        FieldOption(value: 0, labelKey: 'input.foundationSlab.insulation.none'),
        FieldOption(value: 50, labelKey: 'input.foundationSlab.insulation.50'),
        FieldOption(
          value: 100,
          labelKey: 'input.foundationSlab.insulation.100',
        ),
        FieldOption(
          value: 150,
          labelKey: 'input.foundationSlab.insulation.150',
        ),
        FieldOption(
          value: 200,
          labelKey: 'input.foundationSlab.insulation.200',
        ),
      ],
    ),
    CalculatorField(
      key: 'insulationReservePercent',
      labelKey: 'input.foundationSlab.insulationReservePercent',
      unitType: UnitType.percent,
      defaultValue: 5,
      minValue: 0,
      maxValue: 30,
      step: 1,
      dependency: _withInsulation,
      group: 'slab_insulation',
      order: 91,
    ),
    CalculatorField(
      key: 'eppsBoardAreaM2',
      labelKey: 'input.foundationSlab.eppsBoardAreaM2',
      hintKey: 'input.foundationSlab.packageArea.hint',
      unitType: UnitType.squareMeters,
      defaultValue: 0.72,
      minValue: 0.2,
      maxValue: 3,
      step: 0.01,
      dependency: _withInsulation,
      group: 'slab_insulation',
      order: 92,
    ),
  ],
  beforeHints: [
    CalculatorHint(
      type: HintType.info,
      messageKey: 'hint.foundation.slab.before.min_thickness',
    ),
    CalculatorHint(
      type: HintType.tip,
      messageKey: 'hint.foundation.slab.before.preparation',
    ),
  ],
  afterHints: [
    CalculatorHint(
      type: HintType.tip,
      messageKey: 'hint.foundation.slab.after.reinforcement',
    ),
  ],
  useCase: CanonicalBridgeUseCase(calculateCanonicalFoundationSlab),
);
