import '../../core/enums/calculator_category.dart';
import '../../core/enums/field_input_type.dart';
import '../../core/enums/unit_type.dart';
import '../models/calculator_definition_v2.dart';
import '../models/calculator_field.dart';
import '../models/calculator_hint.dart';
import '../usecases/canonical_bridge.dart';
import '../usecases/stairs_canonical_adapter.dart';
import 'calculator_constants.dart';

const _targetMode = FieldDependency(
  fieldKey: 'geometryMode',
  condition: DependencyCondition.equals,
  value: 0,
);
const _projectMode = FieldDependency(
  fieldKey: 'geometryMode',
  condition: DependencyCondition.equals,
  value: 1,
);
const _withOpening = FieldDependency(
  fieldKey: 'openingLengthM',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withTreads = FieldDependency(
  fieldKey: 'includeTreadBlanks',
  condition: DependencyCondition.equals,
  value: 1,
);
const _withRisers = FieldDependency(
  fieldKey: 'riserProjectPcs',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withStringers = FieldDependency(
  fieldKey: 'stringerProjectPcs',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withConcrete = FieldDependency(
  fieldKey: 'concreteProjectM3',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withRebar = FieldDependency(
  fieldKey: 'rebarProjectKg',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withHandrail = FieldDependency(
  fieldKey: 'handrailProjectM',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withRailingInfill = FieldDependency(
  fieldKey: 'railingInfillProjectPcs',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withFasteners = FieldDependency(
  fieldKey: 'fastenersProjectPcs',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withLandingFinish = FieldDependency(
  fieldKey: 'landingFinishProjectM2',
  condition: DependencyCondition.greaterThan,
  value: 0,
);

CalculatorField _number(
  String key,
  UnitType unit,
  double defaultValue,
  double min,
  double max,
  double step,
  String group,
  int order, {
  bool hint = false,
  FieldDependency? dependency,
}) {
  return CalculatorField(
    key: key,
    labelKey: 'input.stairs.$key',
    hintKey: hint ? 'input.stairs.$key.hint' : null,
    unitType: unit,
    defaultValue: defaultValue,
    minValue: min,
    maxValue: max,
    step: step,
    group: group,
    order: order,
    dependency: dependency,
  );
}

CalculatorField _select(
  String key,
  double defaultValue,
  String group,
  int order,
  List<FieldOption> options, {
  bool hint = false,
}) {
  return CalculatorField(
    key: key,
    labelKey: 'input.stairs.$key',
    hintKey: hint ? 'input.stairs.$key.hint' : null,
    unitType: UnitType.pieces,
    inputType: FieldInputType.select,
    defaultValue: defaultValue,
    minValue: options.first.value,
    maxValue: options.last.value,
    group: group,
    order: order,
    options: options,
  );
}

final stairsCalculatorV2 = CalculatorDefinitionV2(
  id: 'stairs',
  titleKey: 'calculator.stairs.title',
  descriptionKey: 'calculator.stairs.description',
  category: CalculatorCategory.exterior,
  subCategoryKey: 'subcategory.stairs',
  iconName: 'stairs',
  accentColor: kCalculatorAccentColor,
  complexity: 3,
  popularity: 10,
  tags: const ['tag.konstruktsii', 'stairs', 'tag.lestnitsy'],
  fields: [
    _select('geometryMode', 0, 'stairs_geometry', 10, const [
      FieldOption(value: 0, labelKey: 'input.stairs.geometryMode.target'),
      FieldOption(value: 1, labelKey: 'input.stairs.geometryMode.project'),
    ], hint: true),
    _number(
      'floorRiseM',
      UnitType.meters,
      2.8,
      1,
      6,
      0.001,
      'stairs_geometry',
      11,
      hint: true,
    ),
    _number(
      'targetRiserHeightMm',
      UnitType.millimeters,
      175,
      100,
      250,
      1,
      'stairs_geometry',
      12,
      hint: true,
      dependency: _targetMode,
    ),
    _number(
      'projectRiserCount',
      UnitType.pieces,
      16,
      1,
      50,
      1,
      'stairs_geometry',
      13,
      dependency: _projectMode,
    ),
    _number(
      'treadDepthMm',
      UnitType.millimeters,
      280,
      100,
      500,
      1,
      'stairs_geometry',
      14,
      hint: true,
    ),
    _select('topFloorActsAsTread', 1, 'stairs_geometry', 15, const [
      FieldOption(value: 1, labelKey: 'input.stairs.topFloorActsAsTread.yes'),
      FieldOption(value: 0, labelKey: 'input.stairs.topFloorActsAsTread.no'),
    ]),
    _number(
      'stairWidthM',
      UnitType.meters,
      1,
      0.5,
      3,
      0.01,
      'stairs_geometry',
      16,
      hint: true,
    ),
    _number(
      'openingLengthM',
      UnitType.meters,
      0,
      0,
      20,
      0.01,
      'stairs_headroom',
      20,
      hint: true,
    ),
    _number(
      'floorStructureThicknessM',
      UnitType.meters,
      0.3,
      0,
      2,
      0.01,
      'stairs_headroom',
      21,
      hint: true,
      dependency: _withOpening,
    ),
    _select('includeTreadBlanks', 1, 'stairs_treads', 30, const [
      FieldOption(value: 1, labelKey: 'input.stairs.includeTreadBlanks.yes'),
      FieldOption(value: 0, labelKey: 'input.stairs.includeTreadBlanks.no'),
    ], hint: true),
    _number(
      'treadReservePercent',
      UnitType.percent,
      0,
      0,
      50,
      1,
      'stairs_treads',
      31,
      dependency: _withTreads,
    ),
    _number(
      'treadsPerPackagePcs',
      UnitType.pieces,
      1,
      0,
      1000,
      1,
      'stairs_treads',
      32,
      hint: true,
      dependency: _withTreads,
    ),
    _number(
      'riserProjectPcs',
      UnitType.pieces,
      0,
      0,
      1000,
      1,
      'stairs_treads',
      33,
      hint: true,
    ),
    _number(
      'riserReservePercent',
      UnitType.percent,
      0,
      0,
      50,
      1,
      'stairs_treads',
      34,
      dependency: _withRisers,
    ),
    _number(
      'risersPerPackagePcs',
      UnitType.pieces,
      1,
      0,
      1000,
      1,
      'stairs_treads',
      35,
      dependency: _withRisers,
    ),
    _number(
      'stringerProjectPcs',
      UnitType.pieces,
      0,
      0,
      100,
      1,
      'stairs_stringers',
      40,
      hint: true,
    ),
    _number(
      'stringerBlankLengthM',
      UnitType.meters,
      0,
      0,
      30,
      0.01,
      'stairs_stringers',
      41,
      dependency: _withStringers,
    ),
    _number(
      'stringerReservePercent',
      UnitType.percent,
      0,
      0,
      50,
      1,
      'stairs_stringers',
      42,
      dependency: _withStringers,
    ),
    _number(
      'stringerStockLengthM',
      UnitType.meters,
      0,
      0,
      30,
      0.01,
      'stairs_stringers',
      43,
      hint: true,
      dependency: _withStringers,
    ),
    _number(
      'concreteProjectM3',
      UnitType.cubicMeters,
      0,
      0,
      100,
      0.001,
      'stairs_concrete',
      50,
      hint: true,
    ),
    _number(
      'concreteReservePercent',
      UnitType.percent,
      5,
      0,
      30,
      1,
      'stairs_concrete',
      51,
      dependency: _withConcrete,
    ),
    _number(
      'concreteOrderStepM3',
      UnitType.cubicMeters,
      0.1,
      0,
      10,
      0.001,
      'stairs_concrete',
      52,
      dependency: _withConcrete,
    ),
    _number(
      'rebarProjectKg',
      UnitType.kilograms,
      0,
      0,
      100000,
      0.1,
      'stairs_concrete',
      53,
      hint: true,
    ),
    _number(
      'rebarReservePercent',
      UnitType.percent,
      5,
      0,
      30,
      1,
      'stairs_concrete',
      54,
      dependency: _withRebar,
    ),
    _number(
      'rebarPackageKg',
      UnitType.kilograms,
      1,
      0,
      10000,
      0.1,
      'stairs_concrete',
      55,
      dependency: _withRebar,
    ),
    _number(
      'handrailProjectM',
      UnitType.linearMeters,
      0,
      0,
      1000,
      0.01,
      'stairs_railing',
      60,
      hint: true,
    ),
    _number(
      'handrailReservePercent',
      UnitType.percent,
      5,
      0,
      30,
      1,
      'stairs_railing',
      61,
      dependency: _withHandrail,
    ),
    _number(
      'handrailStockLengthM',
      UnitType.meters,
      0,
      0,
      30,
      0.01,
      'stairs_railing',
      62,
      dependency: _withHandrail,
    ),
    _number(
      'railingInfillProjectPcs',
      UnitType.pieces,
      0,
      0,
      10000,
      1,
      'stairs_railing',
      63,
      hint: true,
    ),
    _number(
      'railingInfillReservePercent',
      UnitType.percent,
      0,
      0,
      30,
      1,
      'stairs_railing',
      64,
      dependency: _withRailingInfill,
    ),
    _number(
      'railingInfillPackagePcs',
      UnitType.pieces,
      1,
      0,
      10000,
      1,
      'stairs_railing',
      65,
      dependency: _withRailingInfill,
    ),
    _number(
      'fastenersProjectPcs',
      UnitType.pieces,
      0,
      0,
      1000000,
      1,
      'stairs_other',
      70,
      hint: true,
    ),
    _number(
      'fastenersReservePercent',
      UnitType.percent,
      5,
      0,
      30,
      1,
      'stairs_other',
      71,
      dependency: _withFasteners,
    ),
    _number(
      'fastenersPackagePcs',
      UnitType.pieces,
      0,
      0,
      100000,
      1,
      'stairs_other',
      72,
      dependency: _withFasteners,
    ),
    _number(
      'landingFinishProjectM2',
      UnitType.squareMeters,
      0,
      0,
      1000,
      0.01,
      'stairs_other',
      73,
      hint: true,
    ),
    _number(
      'landingFinishReservePercent',
      UnitType.percent,
      10,
      0,
      50,
      1,
      'stairs_other',
      74,
      dependency: _withLandingFinish,
    ),
    _number(
      'landingFinishPackageM2',
      UnitType.squareMeters,
      0,
      0,
      1000,
      0.001,
      'stairs_other',
      75,
      dependency: _withLandingFinish,
    ),
  ],
  beforeHints: const [
    CalculatorHint(
      type: HintType.warning,
      messageKey: 'hint.stairs.before.project',
    ),
    CalculatorHint(
      type: HintType.info,
      messageKey: 'hint.stairs.before.headroom',
    ),
  ],
  afterHints: const [
    CalculatorHint(
      type: HintType.tip,
      messageKey: 'hint.stairs.after.split_positions',
    ),
  ],
  useCase: const CanonicalBridgeUseCase(calculateCanonicalStairs),
);
