// ignore_for_file: prefer_const_constructors
import '../../core/enums/calculator_category.dart';
import '../../core/enums/field_input_type.dart';
import '../../core/enums/unit_type.dart';
import '../models/calculator_definition_v2.dart';
import '../models/calculator_field.dart';
import '../models/calculator_hint.dart';
import 'calculator_constants.dart';
import '../usecases/canonical_bridge.dart';
import '../usecases/strip_foundation_canonical_adapter.dart';

/// Калькулятор ленточного фундамента V2.
final stripFoundationCalculatorV2 = CalculatorDefinitionV2(
  id: 'foundation_strip',
  titleKey: calculatorTitleKey('foundation_strip'),
  descriptionKey: calculatorDescriptionKey('foundation_strip'),
  category: CalculatorCategory.exterior,
  subCategoryKey: 'subcategory.strip',
  iconName: 'foundation',
  accentColor: kCalculatorAccentColor,
  complexity: 2,
  popularity: 90,
  tags: ['фундамент', 'ленточный', 'бетон', 'арматура', 'foundation', 'strip'],

  // Поля ввода
  fields: [
    CalculatorField(
      key: 'perimeter',
      labelKey: 'input.stripFoundation.perimeter',
      hintKey: 'input.stripFoundation.perimeter.hint',
      unitType: UnitType.meters,
      defaultValue: 40,
      minValue: 10,
      maxValue: 200,
      required: true,
      step: 1.0,
      iconName: 'straighten',
      group: 'foundation_geometry',
      order: 0,
    ),
    CalculatorField(
      key: 'width',
      labelKey: 'input.stripFoundation.width',
      hintKey: 'input.stripFoundation.width.hint',
      unitType: UnitType.millimeters,
      defaultValue: 400,
      minValue: 200,
      maxValue: 600,
      step: 50,
      iconName: 'straighten',
      group: 'foundation_geometry',
      order: 2,
    ),
    CalculatorField(
      key: 'depth',
      labelKey: 'input.stripFoundation.depth',
      hintKey: 'input.stripFoundation.depth.hint',
      unitType: UnitType.millimeters,
      defaultValue: 700,
      minValue: 300,
      maxValue: 2000,
      step: 50,
      iconName: 'height',
      group: 'foundation_geometry',
      order: 3,
    ),
    CalculatorField(
      key: 'aboveGround',
      labelKey: 'input.stripFoundation.aboveGround',
      unitType: UnitType.millimeters,
      defaultValue: 300,
      minValue: 0,
      maxValue: 600,
      step: 50,
      iconName: 'height',
      group: 'foundation_geometry',
      order: 4,
    ),
    CalculatorField(
      key: 'formworkHeight',
      labelKey: 'input.stripFoundation.formworkHeight',
      hintKey: 'input.stripFoundation.formworkHeight.hint',
      unitType: UnitType.millimeters,
      defaultValue: 300,
      minValue: 0,
      maxValue: 2000,
      step: 50,
      group: 'foundation_geometry',
      order: 5,
    ),
    CalculatorField(
      key: 'reserve',
      labelKey: 'input.stripFoundation.reserve',
      hintKey: 'input.stripFoundation.reserve.hint',
      unitType: UnitType.percent,
      defaultValue: 5,
      minValue: 0,
      maxValue: 20,
      step: 1,
      group: 'concrete_order',
      order: 10,
    ),
    CalculatorField(
      key: 'readyMixOrderStepM3',
      labelKey: 'input.readyMixOrderStepM3',
      hintKey: 'input.readyMixOrderStepM3.hint',
      unitType: UnitType.cubicMeters,
      inputType: FieldInputType.select,
      defaultValue: 0.1,
      minValue: 0.1,
      maxValue: 1,
      group: 'concrete_order',
      order: 11,
      options: [
        FieldOption(value: 0.1, labelKey: 'input.readyMixOrderStepM3.01'),
        FieldOption(value: 0.5, labelKey: 'input.readyMixOrderStepM3.05'),
        FieldOption(value: 1, labelKey: 'input.readyMixOrderStepM3.10'),
      ],
    ),
    CalculatorField(
      key: 'deliveryAllowanceM3',
      labelKey: 'input.stripFoundation.deliveryAllowanceM3',
      hintKey: 'input.stripFoundation.deliveryAllowanceM3.hint',
      unitType: UnitType.cubicMeters,
      defaultValue: 0,
      minValue: 0,
      maxValue: 5,
      step: 0.05,
      group: 'concrete_order',
      order: 12,
    ),
    CalculatorField(
      key: 'reinforcement',
      labelKey: 'input.stripFoundation.reinforcement',
      hintKey: 'input.stripFoundation.reinforcement.hint',
      unitType: UnitType.pieces,
      inputType: FieldInputType.select,
      defaultValue: 1,
      minValue: 0,
      maxValue: 3,
      group: 'reinforcement',
      order: 20,
      options: [
        FieldOption(
          value: 0,
          labelKey: 'input.stripFoundation.reinforcement.2x12',
        ),
        FieldOption(
          value: 1,
          labelKey: 'input.stripFoundation.reinforcement.4x12',
        ),
        FieldOption(
          value: 2,
          labelKey: 'input.stripFoundation.reinforcement.4x14',
        ),
        FieldOption(
          value: 3,
          labelKey: 'input.stripFoundation.reinforcement.6x12',
        ),
      ],
    ),
    CalculatorField(
      key: 'clampStepMm',
      labelKey: 'input.stripFoundation.clampStepMm',
      hintKey: 'input.stripFoundation.clampStepMm.hint',
      unitType: UnitType.millimeters,
      defaultValue: 400,
      minValue: 100,
      maxValue: 1000,
      step: 50,
      group: 'reinforcement',
      order: 21,
    ),
    CalculatorField(
      key: 'concreteCoverMm',
      labelKey: 'input.stripFoundation.concreteCoverMm',
      hintKey: 'input.stripFoundation.concreteCoverMm.hint',
      unitType: UnitType.millimeters,
      defaultValue: 50,
      minValue: 20,
      maxValue: 100,
      step: 5,
      group: 'reinforcement',
      order: 22,
    ),
    CalculatorField(
      key: 'clampHookAllowanceMm',
      labelKey: 'input.stripFoundation.clampHookAllowanceMm',
      hintKey: 'input.stripFoundation.clampHookAllowanceMm.hint',
      unitType: UnitType.millimeters,
      defaultValue: 300,
      minValue: 0,
      maxValue: 1000,
      step: 50,
      group: 'reinforcement',
      order: 23,
    ),
    CalculatorField(
      key: 'rebarReserve',
      labelKey: 'input.stripFoundation.rebarReserve',
      hintKey: 'input.stripFoundation.rebarReserve.hint',
      unitType: UnitType.percent,
      defaultValue: 12,
      minValue: 0,
      maxValue: 30,
      step: 1,
      group: 'reinforcement',
      order: 24,
    ),
    CalculatorField(
      key: 'rodLengthM',
      labelKey: 'input.stripFoundation.rodLengthM',
      hintKey: 'input.stripFoundation.rodLengthM.hint',
      unitType: UnitType.meters,
      inputType: FieldInputType.select,
      defaultValue: 11.7,
      minValue: 6,
      maxValue: 12,
      group: 'reinforcement',
      order: 25,
      options: [
        FieldOption(value: 6, labelKey: 'input.stripFoundation.rodLengthM.6'),
        FieldOption(
          value: 11.7,
          labelKey: 'input.stripFoundation.rodLengthM.117',
        ),
        FieldOption(value: 12, labelKey: 'input.stripFoundation.rodLengthM.12'),
      ],
    ),
    CalculatorField(
      key: 'formworkReserve',
      labelKey: 'input.stripFoundation.formworkReserve',
      unitType: UnitType.percent,
      defaultValue: 10,
      minValue: 0,
      maxValue: 30,
      step: 1,
      group: 'formwork',
      order: 30,
    ),
  ],

  // Подсказки перед расчётом
  beforeHints: [
    CalculatorHint(
      type: HintType.info,
      messageKey: 'hint.foundation.strip.before.preparation',
    ),
    CalculatorHint(
      type: HintType.tip,
      messageKey: 'hint.foundation.strip.before.cushion',
    ),
    CalculatorHint(
      type: HintType.warning,
      messageKey: 'hint.foundation.strip.before.formwork',
      condition: HintCondition(
        type: HintConditionType.greaterThan,
        fieldKey: 'perimeter',
        value: 50,
      ),
    ),
  ],

  // Подсказки после расчёта
  afterHints: [
    CalculatorHint(
      type: HintType.tip,
      messageKey: 'hint.foundation.strip.after.reinforcement',
    ),
    CalculatorHint(
      type: HintType.important,
      messageKey: 'hint.foundation.strip.after.curing',
    ),
    CalculatorHint(
      type: HintType.warning,
      messageKey: 'hint.foundation.strip.after.large_volume',
      condition: HintCondition(
        type: HintConditionType.greaterThan,
        resultKey: 'concreteVolume',
        value: 20,
      ),
    ),
  ],

  // UseCase для расчёта
  useCase: CanonicalBridgeUseCase(calculateCanonicalStripFoundation),
);
