import '../../core/enums/calculator_category.dart';
import '../../core/enums/field_input_type.dart';
import '../../core/enums/unit_type.dart';
import '../models/calculator_definition_v2.dart';
import '../models/calculator_field.dart';
import '../models/calculator_hint.dart';
import '../usecases/canonical_bridge.dart';
import '../usecases/roofing_canonical_adapter.dart';
import 'calculator_constants.dart';

const _projectAreaMode = FieldDependency(
  fieldKey: 'roofAreaMode',
  condition: DependencyCondition.equals,
  value: 0,
);
const _projectionAreaMode = FieldDependency(
  fieldKey: 'roofAreaMode',
  condition: DependencyCondition.equals,
  value: 1,
);
const _withRidge = FieldDependency(
  fieldKey: 'ridgeProjectM',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withValley = FieldDependency(
  fieldKey: 'valleyProjectM',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withEaves = FieldDependency(
  fieldKey: 'eavesProjectM',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withMembrane = FieldDependency(
  fieldKey: 'membraneProjectAreaM2',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withDeck = FieldDependency(
  fieldKey: 'deckProjectAreaM2',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withBatten = FieldDependency(
  fieldKey: 'battenProjectLengthM',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withCounterBatten = FieldDependency(
  fieldKey: 'counterBattenProjectLengthM',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withFasteners = FieldDependency(
  fieldKey: 'fastenersProjectPcs',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withSnowGuard = FieldDependency(
  fieldKey: 'snowGuardProjectM',
  condition: DependencyCondition.greaterThan,
  value: 0,
);
const _withTape = FieldDependency(
  fieldKey: 'sealingTapeProjectM',
  condition: DependencyCondition.greaterThan,
  value: 0,
);

CalculatorField _number(
  String key,
  UnitType unit,
  double defaultValue,
  double min,
  double max,
  double step,
  String group,
  int order, {
  bool hint = false,
  FieldDependency? dependency,
}) {
  return CalculatorField(
    key: key,
    labelKey: 'input.roofing.$key',
    hintKey: hint ? 'input.roofing.$key.hint' : null,
    unitType: unit,
    defaultValue: defaultValue,
    minValue: min,
    maxValue: max,
    step: step,
    group: group,
    order: order,
    dependency: dependency,
  );
}

CalculatorField _select(
  String key,
  double defaultValue,
  String group,
  int order,
  List<FieldOption> options, {
  bool hint = false,
}) {
  return CalculatorField(
    key: key,
    labelKey: 'input.roofing.$key',
    hintKey: hint ? 'input.roofing.$key.hint' : null,
    unitType: UnitType.pieces,
    inputType: FieldInputType.select,
    defaultValue: defaultValue,
    minValue: options.first.value,
    maxValue: options.last.value,
    group: group,
    order: order,
    options: options,
  );
}

final unifiedRoofingCalculatorV2 = CalculatorDefinitionV2(
  id: 'roofing_unified',
  titleKey: calculatorTitleKey('roofing_unified'),
  descriptionKey: calculatorDescriptionKey('roofing_unified'),
  category: CalculatorCategory.exterior,
  subCategoryKey: 'subcategory.roofing',
  iconName: 'roofing',
  accentColor: kCalculatorAccentColor,
  complexity: 3,
  popularity: 85,
  tags: const [
    'кровля',
    'крыша',
    'металлочерепица',
    'профнастил',
    'битумная черепица',
    'смета',
  ],
  fields: [
    _select('roofAreaMode', 0, 'roofing_area', 10, const [
      FieldOption(value: 0, labelKey: 'input.roofing.roofAreaMode.project'),
      FieldOption(value: 1, labelKey: 'input.roofing.roofAreaMode.simple'),
    ], hint: true),
    _number(
      'projectSlopeAreaM2',
      UnitType.squareMeters,
      100,
      1,
      10000,
      0.1,
      'roofing_area',
      11,
      hint: true,
      dependency: _projectAreaMode,
    ),
    _number(
      'planProjectionAreaM2',
      UnitType.squareMeters,
      80,
      1,
      10000,
      0.1,
      'roofing_area',
      12,
      hint: true,
      dependency: _projectionAreaMode,
    ),
    _number(
      'slopeDeg',
      UnitType.degrees,
      30,
      1,
      75,
      1,
      'roofing_area',
      13,
      dependency: _projectionAreaMode,
    ),
    _select('roofingType', 0, 'roofing_primary', 20, const [
      FieldOption(value: 0, labelKey: 'input.roofing.roofingType.metalTile'),
      FieldOption(value: 1, labelKey: 'input.roofing.roofingType.soft'),
      FieldOption(value: 2, labelKey: 'input.roofing.roofingType.profnastil'),
      FieldOption(value: 3, labelKey: 'input.roofing.roofingType.bitumenSheet'),
      FieldOption(
        value: 4,
        labelKey: 'input.roofing.roofingType.chrysotileSheet',
      ),
      FieldOption(value: 5, labelKey: 'input.roofing.roofingType.ceramic'),
    ], hint: true),
    _number(
      'primaryCoverageM2',
      UnitType.squareMeters,
      0,
      0,
      1000,
      0.001,
      'roofing_primary',
      21,
      hint: true,
    ),
    _number(
      'primaryReservePercent',
      UnitType.percent,
      10,
      0,
      50,
      1,
      'roofing_primary',
      22,
      hint: true,
    ),
    _number(
      'ridgeProjectM',
      UnitType.linearMeters,
      0,
      0,
      10000,
      0.1,
      'roofing_details',
      30,
      hint: true,
    ),
    _number(
      'ridgeReservePercent',
      UnitType.percent,
      5,
      0,
      30,
      1,
      'roofing_details',
      31,
      dependency: _withRidge,
    ),
    _number(
      'ridgeElementUsefulLengthM',
      UnitType.meters,
      0,
      0,
      100,
      0.01,
      'roofing_details',
      32,
      hint: true,
      dependency: _withRidge,
    ),
    _number(
      'valleyProjectM',
      UnitType.linearMeters,
      0,
      0,
      10000,
      0.1,
      'roofing_details',
      33,
    ),
    _number(
      'valleyReservePercent',
      UnitType.percent,
      10,
      0,
      50,
      1,
      'roofing_details',
      34,
      dependency: _withValley,
    ),
    _number(
      'valleyElementUsefulLengthM',
      UnitType.meters,
      0,
      0,
      100,
      0.01,
      'roofing_details',
      35,
      dependency: _withValley,
    ),
    _number(
      'eavesProjectM',
      UnitType.linearMeters,
      0,
      0,
      10000,
      0.1,
      'roofing_details',
      36,
    ),
    _number(
      'eavesReservePercent',
      UnitType.percent,
      5,
      0,
      30,
      1,
      'roofing_details',
      37,
      dependency: _withEaves,
    ),
    _number(
      'eavesElementUsefulLengthM',
      UnitType.meters,
      0,
      0,
      100,
      0.01,
      'roofing_details',
      38,
      dependency: _withEaves,
    ),
    _number(
      'membraneProjectAreaM2',
      UnitType.squareMeters,
      0,
      0,
      10000,
      0.1,
      'roofing_membrane',
      40,
      hint: true,
    ),
    _number(
      'membraneReservePercent',
      UnitType.percent,
      15,
      0,
      50,
      1,
      'roofing_membrane',
      41,
      dependency: _withMembrane,
    ),
    _number(
      'membraneRollCoverageM2',
      UnitType.squareMeters,
      0,
      0,
      1000,
      0.1,
      'roofing_membrane',
      42,
      hint: true,
      dependency: _withMembrane,
    ),
    _number(
      'deckProjectAreaM2',
      UnitType.squareMeters,
      0,
      0,
      10000,
      0.1,
      'roofing_membrane',
      43,
      hint: true,
    ),
    _number(
      'deckReservePercent',
      UnitType.percent,
      10,
      0,
      50,
      1,
      'roofing_membrane',
      44,
      dependency: _withDeck,
    ),
    _number(
      'deckSheetAreaM2',
      UnitType.squareMeters,
      0,
      0,
      100,
      0.001,
      'roofing_membrane',
      45,
      dependency: _withDeck,
    ),
    _number(
      'battenProjectLengthM',
      UnitType.linearMeters,
      0,
      0,
      100000,
      0.1,
      'roofing_lumber',
      50,
      hint: true,
    ),
    _number(
      'battenReservePercent',
      UnitType.percent,
      5,
      0,
      30,
      1,
      'roofing_lumber',
      51,
      dependency: _withBatten,
    ),
    _number(
      'battenBoardLengthM',
      UnitType.meters,
      0,
      0,
      20,
      0.1,
      'roofing_lumber',
      52,
      hint: true,
      dependency: _withBatten,
    ),
    _number(
      'counterBattenProjectLengthM',
      UnitType.linearMeters,
      0,
      0,
      100000,
      0.1,
      'roofing_lumber',
      53,
    ),
    _number(
      'counterBattenReservePercent',
      UnitType.percent,
      5,
      0,
      30,
      1,
      'roofing_lumber',
      54,
      dependency: _withCounterBatten,
    ),
    _number(
      'counterBattenBoardLengthM',
      UnitType.meters,
      0,
      0,
      20,
      0.1,
      'roofing_lumber',
      55,
      dependency: _withCounterBatten,
    ),
    _number(
      'fastenersProjectPcs',
      UnitType.pieces,
      0,
      0,
      1000000,
      1,
      'roofing_safety',
      60,
      hint: true,
    ),
    _number(
      'fastenersReservePercent',
      UnitType.percent,
      5,
      0,
      30,
      1,
      'roofing_safety',
      61,
      dependency: _withFasteners,
    ),
    _number(
      'fastenersPackagePcs',
      UnitType.pieces,
      0,
      0,
      100000,
      1,
      'roofing_safety',
      62,
      dependency: _withFasteners,
    ),
    _number(
      'snowGuardProjectM',
      UnitType.linearMeters,
      0,
      0,
      10000,
      0.1,
      'roofing_safety',
      63,
      hint: true,
    ),
    _number(
      'snowGuardReservePercent',
      UnitType.percent,
      5,
      0,
      30,
      1,
      'roofing_safety',
      64,
      dependency: _withSnowGuard,
    ),
    _number(
      'snowGuardSectionUsefulLengthM',
      UnitType.meters,
      0,
      0,
      100,
      0.01,
      'roofing_safety',
      65,
      dependency: _withSnowGuard,
    ),
    _number(
      'sealingTapeProjectM',
      UnitType.linearMeters,
      0,
      0,
      100000,
      0.1,
      'roofing_tape',
      70,
      hint: true,
    ),
    _number(
      'sealingTapeReservePercent',
      UnitType.percent,
      10,
      0,
      50,
      1,
      'roofing_tape',
      71,
      dependency: _withTape,
    ),
    _number(
      'sealingTapeRollLengthM',
      UnitType.meters,
      0,
      0,
      1000,
      0.1,
      'roofing_tape',
      72,
      dependency: _withTape,
    ),
  ],
  beforeHints: const [
    CalculatorHint(
      type: HintType.warning,
      messageKey: 'hint.roofing.before.project',
    ),
    CalculatorHint(
      type: HintType.info,
      messageKey: 'hint.roofing.before.coverage',
    ),
  ],
  afterHints: const [
    CalculatorHint(
      type: HintType.tip,
      messageKey: 'hint.roofing.after.split_positions',
    ),
  ],
  useCase: const CanonicalBridgeUseCase(calculateCanonicalRoofing),
);
