import '../../core/enums/calculator_category.dart';
import '../../core/enums/field_input_type.dart';
import '../../core/enums/unit_type.dart';
import '../models/calculator_definition_v2.dart';
import '../models/calculator_field.dart';
import '../models/calculator_hint.dart';
import '../usecases/canonical_bridge.dart';
import '../usecases/warm_floor_pipes_canonical_adapter.dart';
import 'calculator_constants.dart';

const _preliminaryOnly = FieldDependency(
  fieldKey: 'calculationMode',
  condition: DependencyCondition.equals,
  value: 0,
);

const _projectOnly = FieldDependency(
  fieldKey: 'calculationMode',
  condition: DependencyCondition.equals,
  value: 1,
);

/// Водяной тёплый пол: геометрическая оценка и проверка ведомости контуров.
final warmFloorPipesCalculatorV2 = CalculatorDefinitionV2(
  id: 'engineering_warm_floor',
  titleKey: calculatorTitleKey('engineering_warm_floor'),
  descriptionKey: calculatorDescriptionKey('engineering_warm_floor'),
  category: CalculatorCategory.interior,
  subCategoryKey: 'subcategory.heating',
  iconName: 'waves',
  accentColor: kCalculatorAccentColor,
  complexity: 3,
  popularity: 68,
  tags: const [
    'водяной тёплый пол',
    'труба',
    'контуры',
    'коллектор',
    'бухта трубы',
  ],
  primaryResultKeys: const [
    'exactPipeLengthM',
    'purchasePipeLengthM',
    'circuitCount',
  ],
  resultLabelKeys: const {
    'exactPipeLengthM': 'result.waterFloorExactPipeLength',
    'purchasePipeLengthM': 'result.waterFloorPurchasePipeLength',
    'circuitCount': 'result.waterFloorCircuitCount',
  },
  fields: const [
    CalculatorField(
      key: 'calculationMode',
      labelKey: 'input.waterFloor.calculationMode',
      hintKey: 'input.waterFloor.calculationMode.hint',
      unitType: UnitType.dimensionless,
      inputType: FieldInputType.radio,
      defaultValue: 0,
      minValue: 0,
      maxValue: 1,
      iconName: 'assignment',
      group: 'water_floor_source',
      order: 1,
      options: [
        FieldOption(
          value: 0,
          labelKey: 'input.waterFloor.calculationMode.preliminary',
        ),
        FieldOption(
          value: 1,
          labelKey: 'input.waterFloor.calculationMode.project',
        ),
      ],
    ),
    CalculatorField(
      key: 'layoutAreaM2',
      labelKey: 'input.waterFloor.layoutAreaM2',
      hintKey: 'input.waterFloor.layoutAreaM2.hint',
      unitType: UnitType.squareMeters,
      defaultValue: 15,
      minValue: 0.1,
      maxValue: 500,
      step: 0.1,
      iconName: 'grid_on',
      group: 'water_floor_source',
      order: 2,
      dependency: _preliminaryOnly,
    ),
    CalculatorField(
      key: 'pipeSpacingMm',
      labelKey: 'input.waterFloor.pipeSpacingMm',
      hintKey: 'input.waterFloor.pipeSpacingMm.hint',
      unitType: UnitType.millimeters,
      defaultValue: 150,
      minValue: 50,
      maxValue: 500,
      step: 10,
      iconName: 'straighten',
      group: 'water_floor_source',
      order: 3,
      dependency: _preliminaryOnly,
    ),
    CalculatorField(
      key: 'connectionLengthM',
      labelKey: 'input.waterFloor.connectionLengthM',
      hintKey: 'input.waterFloor.connectionLengthM.hint',
      unitType: UnitType.meters,
      defaultValue: 0,
      minValue: 0,
      maxValue: 1000,
      step: 0.1,
      iconName: 'route',
      group: 'water_floor_source',
      order: 4,
      required: false,
      dependency: _preliminaryOnly,
    ),
    CalculatorField(
      key: 'projectTotalPipeLengthM',
      labelKey: 'input.waterFloor.projectTotalPipeLengthM',
      hintKey: 'input.waterFloor.projectTotalPipeLengthM.hint',
      unitType: UnitType.meters,
      defaultValue: 0,
      minValue: 0,
      maxValue: 10000,
      step: 0.1,
      iconName: 'format_list_numbered',
      group: 'water_floor_source',
      order: 5,
      dependency: _projectOnly,
    ),
    CalculatorField(
      key: 'circuitCount',
      labelKey: 'input.waterFloor.circuitCount',
      hintKey: 'input.waterFloor.circuitCount.hint',
      unitType: UnitType.pieces,
      defaultValue: 0,
      minValue: 0,
      maxValue: 100,
      step: 1,
      iconName: 'repeat',
      group: 'water_floor_project',
      order: 6,
      required: false,
    ),
    CalculatorField(
      key: 'longestCircuitLengthM',
      labelKey: 'input.waterFloor.longestCircuitLengthM',
      hintKey: 'input.waterFloor.longestCircuitLengthM.hint',
      unitType: UnitType.meters,
      defaultValue: 0,
      minValue: 0,
      maxValue: 1000,
      step: 0.1,
      iconName: 'timeline',
      group: 'water_floor_project',
      order: 7,
      required: false,
    ),
    CalculatorField(
      key: 'maxCircuitLengthM',
      labelKey: 'input.waterFloor.maxCircuitLengthM',
      hintKey: 'input.waterFloor.maxCircuitLengthM.hint',
      unitType: UnitType.meters,
      defaultValue: 0,
      minValue: 0,
      maxValue: 1000,
      step: 0.1,
      iconName: 'rule',
      group: 'water_floor_project',
      order: 8,
      required: false,
    ),
    CalculatorField(
      key: 'coilLengthM',
      labelKey: 'input.waterFloor.coilLengthM',
      hintKey: 'input.waterFloor.coilLengthM.hint',
      unitType: UnitType.meters,
      defaultValue: 0,
      minValue: 0,
      maxValue: 5000,
      step: 1,
      iconName: 'inventory_2',
      group: 'water_floor_purchase',
      order: 9,
      required: false,
    ),
    CalculatorField(
      key: 'collectorCount',
      labelKey: 'input.waterFloor.collectorCount',
      unitType: UnitType.pieces,
      defaultValue: 0,
      minValue: 0,
      maxValue: 20,
      step: 1,
      iconName: 'device_hub',
      group: 'water_floor_purchase',
      order: 10,
      required: false,
    ),
    CalculatorField(
      key: 'manifoldOutletCount',
      labelKey: 'input.waterFloor.manifoldOutletCount',
      hintKey: 'input.waterFloor.manifoldOutletCount.hint',
      unitType: UnitType.pieces,
      defaultValue: 0,
      minValue: 0,
      maxValue: 200,
      step: 1,
      iconName: 'account_tree',
      group: 'water_floor_purchase',
      order: 11,
      required: false,
    ),
  ],
  beforeHints: const [
    CalculatorHint(
      type: HintType.warning,
      messageKey: 'hint.water_floor.projectBoundary',
    ),
    CalculatorHint(
      type: HintType.tip,
      messageKey: 'hint.water_floor.actualLayoutArea',
    ),
  ],
  afterHints: const [
    CalculatorHint(
      type: HintType.important,
      messageKey: 'hint.water_floor.noHydraulics',
    ),
    CalculatorHint(
      type: HintType.warning,
      messageKey: 'hint.water_floor.coilCutPlan',
    ),
  ],
  useCase: const CanonicalBridgeUseCase(calculateCanonicalWarmFloorPipes),
);
