import '../../core/enums/calculator_category.dart';
import '../../core/enums/field_input_type.dart';
import '../../core/enums/unit_type.dart';
import '../models/calculator_definition_v2.dart';
import '../models/calculator_field.dart';
import '../models/calculator_hint.dart';
import '../usecases/canonical_bridge.dart';
import '../usecases/warm_floor_canonical_adapter.dart';
import 'calculator_constants.dart';

const _cableOnly = FieldDependency(
  fieldKey: 'systemType',
  condition: DependencyCondition.equals,
  value: 1,
);

const _conduitOnly = FieldDependency(
  fieldKey: 'sensorConduitLengthM',
  condition: DependencyCondition.greaterThan,
  value: 0,
);

/// Проверка выбранного заводского комплекта электрического тёплого пола.
final warmFloorCalculatorV2 = CalculatorDefinitionV2(
  id: 'floors_warm',
  titleKey: calculatorTitleKey('floors_warm'),
  descriptionKey: calculatorDescriptionKey('floors_warm'),
  category: CalculatorCategory.interior,
  subCategoryKey: 'subcategory.heating',
  iconName: 'electric_bolt',
  accentColor: kCalculatorAccentColor,
  complexity: 3,
  popularity: 90,
  tags: const [
    'электрический тёплый пол',
    'нагревательный мат',
    'нагревательный кабель',
    'терморегулятор',
  ],
  primaryResultKeys: const ['heatingArea', 'totalPowerW', 'circuitCurrentA'],
  resultLabelKeys: const {
    'heatingArea': 'result.warmFloorLayoutArea',
    'totalPowerW': 'result.warmFloorInstalledPower',
    'circuitCurrentA': 'result.warmFloorCircuitCurrent',
  },
  fields: const [
    CalculatorField(
      key: 'roomAreaM2',
      labelKey: 'input.warm_floor.roomAreaM2',
      unitType: UnitType.squareMeters,
      defaultValue: 10,
      minValue: 1,
      maxValue: 500,
      step: 0.5,
      iconName: 'square_foot',
      group: 'warm_floor_layout',
      order: 1,
    ),
    CalculatorField(
      key: 'excludedAreaM2',
      labelKey: 'input.warm_floor.excludedAreaM2',
      hintKey: 'input.warm_floor.excludedAreaM2.hint',
      unitType: UnitType.squareMeters,
      defaultValue: 2,
      minValue: 0,
      maxValue: 500,
      step: 0.5,
      iconName: 'block',
      group: 'warm_floor_layout',
      order: 2,
    ),
    CalculatorField(
      key: 'layoutAreaM2',
      labelKey: 'input.warm_floor.layoutAreaM2',
      hintKey: 'input.warm_floor.layoutAreaM2.hint',
      unitType: UnitType.squareMeters,
      defaultValue: 8,
      minValue: 0.1,
      maxValue: 500,
      step: 0.1,
      iconName: 'grid_on',
      group: 'warm_floor_layout',
      order: 3,
    ),
    CalculatorField(
      key: 'systemType',
      labelKey: 'input.warm_floor.systemType',
      unitType: UnitType.dimensionless,
      inputType: FieldInputType.radio,
      defaultValue: 0,
      minValue: 0,
      maxValue: 1,
      iconName: 'electric_bolt',
      group: 'warm_floor_product',
      order: 4,
      options: [
        FieldOption(value: 0, labelKey: 'input.warm_floor.systemType.mat'),
        FieldOption(value: 1, labelKey: 'input.warm_floor.systemType.cable'),
      ],
    ),
    CalculatorField(
      key: 'kitCount',
      labelKey: 'input.warm_floor.kitCount',
      hintKey: 'input.warm_floor.kitCount.hint',
      unitType: UnitType.pieces,
      defaultValue: 1,
      minValue: 1,
      maxValue: 100,
      step: 1,
      iconName: 'inventory_2',
      group: 'warm_floor_product',
      order: 5,
    ),
    CalculatorField(
      key: 'kitCoverageAreaM2',
      labelKey: 'input.warm_floor.kitCoverageAreaM2',
      hintKey: 'input.warm_floor.kitCoverageAreaM2.hint',
      unitType: UnitType.squareMeters,
      defaultValue: 8,
      minValue: 0.1,
      maxValue: 500,
      step: 0.1,
      iconName: 'crop_square',
      group: 'warm_floor_product',
      order: 6,
    ),
    CalculatorField(
      key: 'kitRatedPowerW',
      labelKey: 'input.warm_floor.kitRatedPowerW',
      unitType: UnitType.watts,
      defaultValue: 1200,
      minValue: 10,
      maxValue: 50000,
      step: 10,
      iconName: 'bolt',
      group: 'warm_floor_product',
      order: 7,
    ),
    CalculatorField(
      key: 'cableLengthPerKitM',
      labelKey: 'input.warm_floor.cableLengthPerKitM',
      hintKey: 'input.warm_floor.cableLengthPerKitM.hint',
      unitType: UnitType.meters,
      defaultValue: 60,
      minValue: 0.1,
      maxValue: 5000,
      step: 0.1,
      iconName: 'cable',
      group: 'warm_floor_product',
      order: 8,
      dependency: _cableOnly,
    ),
    CalculatorField(
      key: 'designHeatLoadW',
      labelKey: 'input.warm_floor.designHeatLoadW',
      hintKey: 'input.warm_floor.designHeatLoadW.hint',
      unitType: UnitType.watts,
      defaultValue: 0,
      minValue: 0,
      maxValue: 500000,
      step: 10,
      iconName: 'assignment',
      group: 'warm_floor_electric',
      order: 9,
      required: false,
    ),
    CalculatorField(
      key: 'supplyVoltageV',
      labelKey: 'input.warm_floor.supplyVoltageV',
      unitType: UnitType.volts,
      defaultValue: 230,
      minValue: 100,
      maxValue: 500,
      step: 1,
      iconName: 'electrical_services',
      group: 'warm_floor_electric',
      order: 10,
    ),
    CalculatorField(
      key: 'thermostatRatedCurrentA',
      labelKey: 'input.warm_floor.thermostatRatedCurrentA',
      hintKey: 'input.warm_floor.thermostatRatedCurrentA.hint',
      unitType: UnitType.amperes,
      defaultValue: 0,
      minValue: 0,
      maxValue: 100,
      step: 0.1,
      iconName: 'thermostat',
      group: 'warm_floor_electric',
      order: 11,
      required: false,
    ),
    CalculatorField(
      key: 'thermostatCount',
      labelKey: 'input.warm_floor.thermostatCount',
      unitType: UnitType.pieces,
      defaultValue: 0,
      minValue: 0,
      maxValue: 100,
      step: 1,
      iconName: 'thermostat',
      group: 'warm_floor_purchase',
      order: 12,
      required: false,
    ),
    CalculatorField(
      key: 'floorSensorCount',
      labelKey: 'input.warm_floor.floorSensorCount',
      unitType: UnitType.pieces,
      defaultValue: 0,
      minValue: 0,
      maxValue: 100,
      step: 1,
      iconName: 'sensors',
      group: 'warm_floor_purchase',
      order: 13,
      required: false,
    ),
    CalculatorField(
      key: 'sensorConduitLengthM',
      labelKey: 'input.warm_floor.sensorConduitLengthM',
      unitType: UnitType.meters,
      defaultValue: 0,
      minValue: 0,
      maxValue: 1000,
      step: 0.1,
      iconName: 'route',
      group: 'warm_floor_purchase',
      order: 14,
      required: false,
    ),
    CalculatorField(
      key: 'sensorConduitStockLengthM',
      labelKey: 'input.warm_floor.sensorConduitStockLengthM',
      unitType: UnitType.meters,
      defaultValue: 1,
      minValue: 0.1,
      maxValue: 100,
      step: 0.1,
      iconName: 'straighten',
      group: 'warm_floor_purchase',
      order: 15,
      dependency: _conduitOnly,
    ),
  ],
  beforeHints: const [
    CalculatorHint(
      type: HintType.warning,
      messageKey: 'hint.warm_floor.v3.factoryKit',
    ),
    CalculatorHint(
      type: HintType.tip,
      messageKey: 'hint.warm_floor.v3.noHeatZones',
    ),
  ],
  afterHints: const [
    CalculatorHint(
      type: HintType.important,
      messageKey: 'hint.warm_floor.v3.rcd',
    ),
    CalculatorHint(
      type: HintType.warning,
      messageKey: 'hint.warm_floor.v3.noElectricalDesign',
    ),
  ],
  useCase: const CanonicalBridgeUseCase(calculateCanonicalWarmFloor),
);
