// GENERATED FILE - do not edit by hand.
// CalculatorDefinitionV2 entries used by the app.

import '../../../core/enums/calculator_category.dart';
import '../../../core/enums/field_input_type.dart';
import '../../../core/enums/unit_type.dart';
import '../../models/calculator_definition_v2.dart';
import '../../models/calculator_field.dart';
import '../../models/calculator_hint.dart';
import '../calculator_constants.dart';
import '../../usecases/calculate_cassette_ceiling_v2.dart';
import '../../usecases/calculate_ceiling_insulation.dart';
import '../../usecases/calculate_rail_ceiling.dart';
import '../../usecases/calculate_stretch_ceiling.dart';
// calculate_ceiling_paint.dart больше не используется - ceilings_paint заменён на paint_universal

final List<CalculatorDefinitionV2> ceilingCalculators = [
  CalculatorDefinitionV2(
      id: 'ceilings_cassette',
      titleKey: 'calculator.ceilings_cassette.title',
      descriptionKey: 'calculator.ceilings_cassette.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.ceilings',
      fields: [
        const CalculatorField(
          key: 'inputMode',
          labelKey: 'input.inputMode',
          unitType: UnitType.pieces,
          inputType: FieldInputType.radio,
          defaultValue: 1.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'roomWidth',
          labelKey: 'input.roomWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 4.0,
          minValue: 1.0,
          maxValue: 30.0,
          step: 0.1,
          iconName: 'width_normal',
          group: 'dimensions',
          required: false,
          order: 2,
        ),
        const CalculatorField(
          key: 'roomLength',
          labelKey: 'input.roomLength',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 5.0,
          minValue: 1.0,
          maxValue: 50.0,
          step: 0.1,
          iconName: 'straighten',
          group: 'dimensions',
          required: false,
          order: 3,
        ),
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 20.0,
          minValue: 1.0,
          maxValue: 500.0,
          step: 0.5,
          iconName: 'square_foot',
          group: 'dimensions',
          required: false,
          order: 4,
        ),
        const CalculatorField(
          key: 'cassetteSize',
          labelKey: 'input.cassetteSize',
          unitType: UnitType.pieces,
          inputType: FieldInputType.radio,
          defaultValue: 0.0,
          iconName: 'grid_view',
          group: 'material',
          required: true,
          order: 5,
        ),
        const CalculatorField(
          key: 'ceilingType',
          labelKey: 'input.ceilingType',
          unitType: UnitType.pieces,
          inputType: FieldInputType.radio,
          defaultValue: 0.0,
          iconName: 'category',
          group: 'options',
          required: true,
          order: 6,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.kassety_legko_zamenyayutsya_pri'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.obespechte_dostup_k_kommunikatsiyam'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.ispolzuyte_uroven_dlya_montazha'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.kassety_legko_zamenyayutsya_pri'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.obespechte_dostup_k_kommunikatsiyam'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.ispolzuyte_uroven_dlya_montazha'),
      ],
      useCase: CalculateCassetteCeilingV2(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'cassette',
        'tag.vnutrennyaya_otdelka',
        'tag.potolki',
        'ceilings',
        'ceilings_cassette',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'ceilings_insulation',
      titleKey: 'calculator.ceilings_insulation.title',
      descriptionKey: 'calculator.ceilings_insulation.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.ceilings',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 20.0,
          minValue: 1.0,
          maxValue: 500.0,
          step: 0.5,
          iconName: 'square_foot',
          group: 'dimensions',
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'insulationThickness',
          labelKey: 'input.insulationThickness',
          hintKey: 'input.insulation_thickness.hint',
          unitType: UnitType.millimeters,
          inputType: FieldInputType.number,
          defaultValue: 100.0,
          minValue: 50.0,
          maxValue: 300.0,
          step: 10.0,
          iconName: 'height',
          group: 'material',
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'insulationType',
          labelKey: 'input.insulationType',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          minValue: 1.0,
          maxValue: 3.0,
          iconName: 'category',
          group: 'material',
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.ispolzuyte_paroizolyatsiyu_s_vnutrenney'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.ne_szhimayte_uteplitel_pri'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.obespechte_ventilyatsiyu_podkrovelnogo_prostranstva'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.ispolzuyte_paroizolyatsiyu_s_vnutrenney'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.ne_szhimayte_uteplitel_pri'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.obespechte_ventilyatsiyu_podkrovelnogo_prostranstva'),
      ],
      useCase: CalculateCeilingInsulation(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'tag.potolki',
        'ceilings',
        'insulation',
        'ceilings_insulation',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'ceilings_rail',
      titleKey: 'calculator.ceilings_rail.title',
      descriptionKey: 'calculator.ceilings_rail.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.ceilings',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 20.0,
          minValue: 1.0,
          maxValue: 200.0,
          step: 0.5,
          iconName: 'square_foot',
          group: 'dimensions',
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'railWidth',
          labelKey: 'input.railWidth',
          unitType: UnitType.centimeters,
          inputType: FieldInputType.number,
          defaultValue: 10.0,
          minValue: 5.0,
          maxValue: 30.0,
          step: 1.0,
          iconName: 'width_normal',
          group: 'material',
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'railLength',
          labelKey: 'input.railLength',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 300.0,
          minValue: 200.0,
          maxValue: 400.0,
          step: 10.0,
          iconName: 'straighten',
          group: 'material',
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.montiruyte_reyki_perpendikulyarno_napravlyayuschim'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.ostavlyayte_zazor_dlya_ventilyatsii'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.ispolzuyte_uroven_dlya_kontrolya'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.montiruyte_reyki_perpendikulyarno_napravlyayuschim'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.ostavlyayte_zazor_dlya_ventilyatsii'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.ispolzuyte_uroven_dlya_kontrolya'),
      ],
      useCase: CalculateRailCeiling(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'tag.potolki',
        'ceilings',
        'rail',
        'ceilings_rail',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'ceilings_stretch',
      titleKey: 'calculator.ceilings_stretch.title',
      descriptionKey: 'calculator.ceilings_stretch.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.ceilings',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 20.0,
          minValue: 1.0,
          maxValue: 500.0,
          step: 0.5,
          iconName: 'square_foot',
          group: 'dimensions',
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'corners',
          labelKey: 'input.corners',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 4.0,
          minValue: 3.0,
          maxValue: 20.0,
          step: 1.0,
          iconName: 'crop_square',
          group: 'dimensions',
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'fixtures',
          labelKey: 'input.fixtures',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          minValue: 0.0,
          maxValue: 50.0,
          step: 1.0,
          iconName: 'lightbulb',
          group: 'options',
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.montazh_vypolnyayut_spetsialisty_s'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.zaranee_opredelite_mesta_dlya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.uchityvayte_vysotu_potolka_natyazhnoy'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.montazh_vypolnyayut_spetsialisty_s'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.zaranee_opredelite_mesta_dlya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.uchityvayte_vysotu_potolka_natyazhnoy'),
      ],
      useCase: CalculateStretchCeiling(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'tag.potolki',
        'ceilings',
        'stretch',
        'ceilings_stretch',
      ],
    ),
  // ceilings_paint удалён - используйте paint_universal (поддерживает потолки)
];
