// GENERATED FILE - do not edit by hand.
// CalculatorDefinitionV2 entries used by the app.

import '../../../core/enums/calculator_category.dart';
import '../../../core/enums/field_input_type.dart';
import '../../../core/enums/unit_type.dart';
import '../../models/calculator_definition_v2.dart';
import '../../models/calculator_field.dart';
import '../../models/calculator_hint.dart';
import '../calculator_constants.dart';
import '../../usecases/calculate_cassette_ceiling.dart';
import '../../usecases/calculate_ceiling_insulation.dart';
import '../../usecases/calculate_rail_ceiling.dart';
import '../../usecases/calculate_stretch_ceiling.dart';
import '../../usecases/calculate_ceiling_paint.dart';

final List<CalculatorDefinitionV2> ceilingCalculators = [
  CalculatorDefinitionV2(
      id: 'ceilings_cassette',
      titleKey: 'calculator.ceilings_cassette.title',
      descriptionKey: 'calculator.ceilings_cassette.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.ceilings',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'cassetteSize',
          labelKey: 'input.tileSize',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 60.0,
          required: true,
          order: 2,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.kassety_legko_zamenyayutsya_pri'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.obespechte_dostup_k_kommunikatsiyam'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.ispolzuyte_uroven_dlya_montazha'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.kassety_legko_zamenyayutsya_pri'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.obespechte_dostup_k_kommunikatsiyam'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.ispolzuyte_uroven_dlya_montazha'),
      ],
      useCase: CalculateCassetteCeiling(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'cassette',
        'tag.vnutrennyaya_otdelka',
        'tag.potolki',
        'ceilings',
        'ceilings_cassette',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'ceilings_insulation',
      titleKey: 'calculator.ceilings_insulation.title',
      descriptionKey: 'calculator.ceilings_insulation.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.ceilings',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'insulationThickness',
          labelKey: 'input.insulationThickness',
          unitType: UnitType.millimeters,
          inputType: FieldInputType.number,
          defaultValue: 100.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'insulationType',
          labelKey: 'input.insulationType',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.ispolzuyte_paroizolyatsiyu_s_vnutrenney'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.ne_szhimayte_uteplitel_pri'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.obespechte_ventilyatsiyu_podkrovelnogo_prostranstva'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.ispolzuyte_paroizolyatsiyu_s_vnutrenney'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.ne_szhimayte_uteplitel_pri'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.obespechte_ventilyatsiyu_podkrovelnogo_prostranstva'),
      ],
      useCase: CalculateCeilingInsulation(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'tag.potolki',
        'ceilings',
        'insulation',
        'ceilings_insulation',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'ceilings_rail',
      titleKey: 'calculator.ceilings_rail.title',
      descriptionKey: 'calculator.ceilings_rail.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.ceilings',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'railWidth',
          labelKey: 'input.railWidth',
          unitType: UnitType.centimeters,
          inputType: FieldInputType.number,
          defaultValue: 10.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'railLength',
          labelKey: 'input.railLength',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 300.0,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.montiruyte_reyki_perpendikulyarno_napravlyayuschim'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.ostavlyayte_zazor_dlya_ventilyatsii'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.ispolzuyte_uroven_dlya_kontrolya'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.montiruyte_reyki_perpendikulyarno_napravlyayuschim'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.ostavlyayte_zazor_dlya_ventilyatsii'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.ispolzuyte_uroven_dlya_kontrolya'),
      ],
      useCase: CalculateRailCeiling(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'tag.potolki',
        'ceilings',
        'rail',
        'ceilings_rail',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'ceilings_stretch',
      titleKey: 'calculator.ceilings_stretch.title',
      descriptionKey: 'calculator.ceilings_stretch.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.ceilings',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'corners',
          labelKey: 'input.corners',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 4.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'fixtures',
          labelKey: 'input.fixtures',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.montazh_vypolnyayut_spetsialisty_s'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.zaranee_opredelite_mesta_dlya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.uchityvayte_vysotu_potolka_natyazhnoy'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.montazh_vypolnyayut_spetsialisty_s'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.zaranee_opredelite_mesta_dlya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.uchityvayte_vysotu_potolka_natyazhnoy'),
      ],
      useCase: CalculateStretchCeiling(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'tag.potolki',
        'ceilings',
        'stretch',
        'ceilings_stretch',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'ceilings_paint',
      titleKey: 'calculator.ceilings_paint.title',
      descriptionKey: 'calculator.ceilings_paint.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.ceilings',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 1.0,
          maxValue: 500.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'layers',
          labelKey: 'input.layers',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 2.0,
          minValue: 1.0,
          maxValue: 4.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'consumption',
          labelKey: 'input.paint_consumption',
          hintKey: 'input.paint_consumption.hint',
          unitType: UnitType.liters,
          inputType: FieldInputType.number,
          defaultValue: 0.12,
          minValue: 0.08,
          maxValue: 0.2,
          required: false,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.podgotovte_poverhnost_zagruntuite'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.ispolzuyte_valik_s_korotkim'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.kraste_ot_okna_k'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.dayte_vysohnut_mezhdu_sloyami'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.ceiling.proverte_osveschenie_dlya_kontrolya'),
      ],
      useCase: CalculateCeilingPaint(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 9,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'tag.potolki',
        'ceilings',
        'paint',
        'ceilings_paint',
      ],
    ),
];
