// GENERATED FILE - do not edit by hand.
// CalculatorDefinitionV2 entries used by the app.

import '../../../core/enums/calculator_category.dart';
import '../../../core/enums/field_input_type.dart';
import '../../../core/enums/unit_type.dart';
import '../../models/calculator_definition_v2.dart';
import '../../models/calculator_field.dart';
import '../../models/calculator_hint.dart';
import '../calculator_constants.dart';
import '../../usecases/calculate_cassette_ceiling.dart';
import '../../usecases/calculate_ceiling_insulation.dart';
import '../../usecases/calculate_ceiling_tiles.dart';
import '../../usecases/calculate_gkl_ceiling.dart';
import '../../usecases/calculate_rail_ceiling.dart';
import '../../usecases/calculate_stretch_ceiling.dart';

final List<CalculatorDefinitionV2> ceilingCalculators = [
  CalculatorDefinitionV2(
      id: 'ceilings_cassette',
      titleKey: 'calculator.ceilings_cassette.title',
      descriptionKey: 'calculator.ceilings_cassette.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.ceilings',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'cassetteSize',
          labelKey: 'input.tileSize',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 60.0,
          required: true,
          order: 2,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Кассеты легко заменяются при повреждении.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Обеспечьте доступ к коммуникациям над потолком.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте уровень для монтажа направляющих.'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Кассеты легко заменяются при повреждении.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Обеспечьте доступ к коммуникациям над потолком.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте уровень для монтажа направляющих.'),
      ],
      useCase: CalculateCassetteCeiling(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'cassette',
        'Внутренняя отделка',
        'Потолки',
        'ceilings',
        'ceilings_cassette',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'ceilings_gkl',
      titleKey: 'calculator.ceilings_gkl.title',
      descriptionKey: 'calculator.ceilings_gkl.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.ceilings',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'layers',
          labelKey: 'input.layers',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'ceilingHeight',
          labelKey: 'input.ceilingHeight',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 2.5,
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'dropHeight',
          labelKey: 'input.dropHeight',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.1,
          required: true,
          order: 4,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Шаг подвесов — 60 см для надёжности.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Проверьте уровень всех профилей.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте армирующую ленту на стыках листов.'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Шаг подвесов — 60 см для надёжности.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Проверьте уровень всех профилей.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте армирующую ленту на стыках листов.'),
      ],
      useCase: CalculateGklCeiling(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'Внутренняя отделка',
        'Потолки',
        'ceilings',
        'ceilings_gkl',
        'gkl',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'ceilings_insulation',
      titleKey: 'calculator.ceilings_insulation.title',
      descriptionKey: 'calculator.ceilings_insulation.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.ceilings',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'insulationThickness',
          labelKey: 'input.insulationThickness',
          unitType: UnitType.millimeters,
          inputType: FieldInputType.number,
          defaultValue: 100.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'insulationType',
          labelKey: 'input.insulationType',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте пароизоляцию с внутренней стороны.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Не сжимайте утеплитель при укладке.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Обеспечьте вентиляцию подкровельного пространства.'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте пароизоляцию с внутренней стороны.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Не сжимайте утеплитель при укладке.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Обеспечьте вентиляцию подкровельного пространства.'),
      ],
      useCase: CalculateCeilingInsulation(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'Внутренняя отделка',
        'Потолки',
        'ceilings',
        'insulation',
        'ceilings_insulation',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'ceilings_rail',
      titleKey: 'calculator.ceilings_rail.title',
      descriptionKey: 'calculator.ceilings_rail.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.ceilings',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'railWidth',
          labelKey: 'input.railWidth',
          unitType: UnitType.centimeters,
          inputType: FieldInputType.number,
          defaultValue: 10.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'railLength',
          labelKey: 'input.railLength',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 300.0,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Монтируйте рейки перпендикулярно направляющим.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Оставляйте зазор для вентиляции.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте уровень для контроля плоскости.'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Монтируйте рейки перпендикулярно направляющим.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Оставляйте зазор для вентиляции.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте уровень для контроля плоскости.'),
      ],
      useCase: CalculateRailCeiling(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'Внутренняя отделка',
        'Потолки',
        'ceilings',
        'rail',
        'ceilings_rail',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'ceilings_stretch',
      titleKey: 'calculator.ceilings_stretch.title',
      descriptionKey: 'calculator.ceilings_stretch.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.ceilings',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'corners',
          labelKey: 'input.corners',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 4.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'fixtures',
          labelKey: 'input.fixtures',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Монтаж выполняют специалисты с опытом.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Заранее определите места для светильников.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Учитывайте высоту потолка — натяжной потолок опускает его на 3–5 см.'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Монтаж выполняют специалисты с опытом.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Заранее определите места для светильников.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Учитывайте высоту потолка — натяжной потолок опускает его на 3–5 см.'),
      ],
      useCase: CalculateStretchCeiling(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'Внутренняя отделка',
        'Потолки',
        'ceilings',
        'stretch',
        'ceilings_stretch',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'ceilings_tiles',
      titleKey: 'calculator.ceilings_tiles.title',
      descriptionKey: 'calculator.ceilings_tiles.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.ceilings',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'tileSize',
          labelKey: 'input.tileSize',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 50.0,
          required: true,
          order: 2,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Проверьте ровность потолка перед укладкой.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте специальный клей для потолочной плитки.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Начинайте укладку от центра комнаты.'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Проверьте ровность потолка перед укладкой.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте специальный клей для потолочной плитки.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Начинайте укладку от центра комнаты.'),
      ],
      useCase: CalculateCeilingTiles(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'Внутренняя отделка',
        'Потолки',
        'ceilings_tiles',
        'ceilings',
        'tiles',
      ],
    ),
];
