// GENERATED FILE - do not edit by hand.
// CalculatorDefinitionV2 entries used by the app.

import '../../../core/enums/calculator_category.dart';
import '../../../core/enums/field_input_type.dart';
import '../../../core/enums/unit_type.dart';
import '../../models/calculator_definition_v2.dart';
import '../../models/calculator_field.dart';
import '../../models/calculator_hint.dart';
import '../calculator_constants.dart';
import '../../usecases/calculate_electrics.dart';
import '../../usecases/calculate_heating.dart';
import '../../usecases/calculate_plumbing.dart';
import '../../usecases/calculate_ventilation.dart';

final List<CalculatorDefinitionV2> engineeringCalculators = [
  CalculatorDefinitionV2(
      id: 'engineering_electrics',
      titleKey: 'calculator.engineering_electrics.title',
      descriptionKey: 'calculator.engineering_electrics.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.electrics',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 5.0,
          maxValue: 1000.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'rooms',
          labelKey: 'input.rooms',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          minValue: 1.0,
          maxValue: 50.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'sockets',
          labelKey: 'input.sockets',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 200.0,
          required: false,
          order: 3,
        ),
        const CalculatorField(
          key: 'switches',
          labelKey: 'input.switches',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 100.0,
          required: false,
          order: 4,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Работы должен выполнять квалифицированный электрик.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте кабель сечением не менее 2.5 мм² для розеток.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Установите УЗО для защиты от утечек тока.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Проверьте все соединения перед включением.'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Работы должен выполнять квалифицированный электрик.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте кабель сечением не менее 2.5 мм² для розеток.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Установите УЗО для защиты от утечек тока.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Проверьте все соединения перед включением.'),
      ],
      useCase: CalculateElectrics(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'engineering_electrics',
        'engineering',
        'Инженерные работы',
        'Электрика',
        'electrics',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'engineering_heating',
      titleKey: 'calculator.engineering_heating.title',
      descriptionKey: 'calculator.engineering_heating.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.heating',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 10.0,
          maxValue: 1000.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'rooms',
          labelKey: 'input.rooms',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          minValue: 1.0,
          maxValue: 50.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'ceilingHeight',
          labelKey: 'input.ceilingHeight',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 2.5,
          minValue: 2.2,
          maxValue: 5.0,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Расчёт мощности: 100 Вт на м² для средней полосы.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Установите терморегуляторы для экономии.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте балансировочные краны.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Работы должен выполнять квалифицированный специалист.'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Расчёт мощности: 100 Вт на м² для средней полосы.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Установите терморегуляторы для экономии.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте балансировочные краны.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Работы должен выполнять квалифицированный специалист.'),
      ],
      useCase: CalculateHeating(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'heating',
        'Отопление',
        'engineering',
        'engineering_heating',
        'Инженерные работы',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'engineering_plumbing',
      titleKey: 'calculator.engineering_plumbing.title',
      descriptionKey: 'calculator.engineering_plumbing.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.plumbing',
      fields: [
        const CalculatorField(
          key: 'rooms',
          labelKey: 'input.rooms',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'points',
          labelKey: 'input.points',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'pipeLength',
          labelKey: 'input.pipeLength',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте качественные фитинги для надёжности.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Проверьте все соединения на герметичность.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Установите запорные краны на каждую точку.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Работы должен выполнять квалифицированный сантехник.'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте качественные фитинги для надёжности.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Проверьте все соединения на герметичность.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Установите запорные краны на каждую точку.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Работы должен выполнять квалифицированный сантехник.'),
      ],
      useCase: CalculatePlumbing(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'plumbing',
        'Сантехника',
        'engineering',
        'Инженерные работы',
        'engineering_plumbing',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'engineering_ventilation',
      titleKey: 'calculator.engineering_ventilation.title',
      descriptionKey: 'calculator.engineering_ventilation.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.ventilation',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'rooms',
          labelKey: 'input.rooms',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'ceilingHeight',
          labelKey: 'input.ceilingHeight',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 2.5,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Воздухообмен: минимум 3 м³/ч на м².'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Устанавливайте решётки вверху для вытяжки, внизу для притока.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Проверьте тягу перед монтажом вентиляторов.'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Воздухообмен: минимум 3 м³/ч на м².'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Устанавливайте решётки вверху для вытяжки, внизу для притока.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Проверьте тягу перед монтажом вентиляторов.'),
      ],
      useCase: CalculateVentilation(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'ventilation',
        'engineering',
        'Инженерные работы',
        'Вентиляция',
        'engineering_ventilation',
      ],
    ),
];
