// GENERATED FILE - do not edit by hand.
// CalculatorDefinitionV2 entries used by the app.

import '../../../core/enums/calculator_category.dart';
import '../../../core/enums/field_input_type.dart';
import '../../../core/enums/unit_type.dart';
import '../../models/calculator_definition_v2.dart';
import '../../models/calculator_field.dart';
import '../../models/calculator_hint.dart';
import '../calculator_constants.dart';
import '../../usecases/calculate_electrics.dart';
import '../../usecases/calculate_heating.dart';
// calculate_plumbing.dart - удалён (engineering_plumbing не востребован)
import '../../usecases/calculate_ventilation.dart';

final List<CalculatorDefinitionV2> engineeringCalculators = [
  CalculatorDefinitionV2(
      id: 'engineering_electrics',
      titleKey: 'calculator.engineering_electrics.title',
      descriptionKey: 'calculator.engineering_electrics.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.electrics',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.slider,
          defaultValue: 50.0,
          minValue: 5.0,
          maxValue: 1000.0,
          step: 1.0,
          iconName: 'square_foot',
          group: 'dimensions',
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'rooms',
          labelKey: 'input.rooms',
          unitType: UnitType.pieces,
          inputType: FieldInputType.slider,
          defaultValue: 1.0,
          minValue: 1.0,
          maxValue: 50.0,
          step: 1.0,
          iconName: 'meeting_room',
          group: 'dimensions',
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'sockets',
          labelKey: 'input.sockets',
          unitType: UnitType.pieces,
          inputType: FieldInputType.slider,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 200.0,
          step: 1.0,
          iconName: 'electrical_services',
          group: 'options',
          required: false,
          order: 3,
        ),
        const CalculatorField(
          key: 'switches',
          labelKey: 'input.switches',
          unitType: UnitType.pieces,
          inputType: FieldInputType.slider,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 100.0,
          step: 1.0,
          iconName: 'toggle_on',
          group: 'options',
          required: false,
          order: 4,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.engineering.raboty_dolzhen_vypolnyat_kvalifitsirovannyy'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.engineering.ispolzuyte_kabel_secheniem_ne'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.engineering.ustanovite_uzo_dlya_zaschity'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.engineering.proverte_vse_soedineniya_pered'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.engineering.raboty_dolzhen_vypolnyat_kvalifitsirovannyy'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.engineering.ispolzuyte_kabel_secheniem_ne'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.engineering.ustanovite_uzo_dlya_zaschity'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.engineering.proverte_vse_soedineniya_pered'),
      ],
      useCase: CalculateElectrics(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'engineering_electrics',
        'engineering',
        'tag.inzhenernye_raboty',
        'tag.elektrika',
        'electrics',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'engineering_heating',
      titleKey: 'calculator.engineering_heating.title',
      descriptionKey: 'calculator.engineering_heating.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.heating',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.slider,
          defaultValue: 50.0,
          minValue: 10.0,
          maxValue: 1000.0,
          step: 1.0,
          iconName: 'square_foot',
          group: 'dimensions',
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'rooms',
          labelKey: 'input.rooms',
          unitType: UnitType.pieces,
          inputType: FieldInputType.slider,
          defaultValue: 1.0,
          minValue: 1.0,
          maxValue: 50.0,
          step: 1.0,
          iconName: 'meeting_room',
          group: 'dimensions',
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'ceilingHeight',
          labelKey: 'input.ceilingHeight',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 2.5,
          minValue: 2.2,
          maxValue: 5.0,
          step: 1.0,
          iconName: 'height',
          group: 'dimensions',
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.engineering.raschet_moschnosti_100_vt'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.engineering.ustanovite_termoregulyatory_dlya_ekonomii'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.engineering.ispolzuyte_balansirovochnye_krany'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.engineering.raboty_dolzhen_vypolnyat_kvalifitsirovannyy_2'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.engineering.raschet_moschnosti_100_vt'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.engineering.ustanovite_termoregulyatory_dlya_ekonomii'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.engineering.ispolzuyte_balansirovochnye_krany'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.engineering.raboty_dolzhen_vypolnyat_kvalifitsirovannyy_2'),
      ],
      useCase: CalculateHeating(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'heating',
        'tag.otoplenie',
        'engineering',
        'engineering_heating',
        'tag.inzhenernye_raboty',
      ],
    ),
  // engineering_plumbing удалён - слишком общий, не востребован
  CalculatorDefinitionV2(
      id: 'engineering_ventilation',
      titleKey: 'calculator.engineering_ventilation.title',
      descriptionKey: 'calculator.engineering_ventilation.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.ventilation',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.slider,
          defaultValue: 50.0,
          minValue: 5.0,
          maxValue: 500.0,
          step: 1.0,
          iconName: 'square_foot',
          group: 'dimensions',
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'rooms',
          labelKey: 'input.rooms',
          unitType: UnitType.pieces,
          inputType: FieldInputType.slider,
          defaultValue: 1.0,
          minValue: 1.0,
          maxValue: 30.0,
          step: 1.0,
          iconName: 'meeting_room',
          group: 'dimensions',
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'ceilingHeight',
          labelKey: 'input.ceilingHeight',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 2.5,
          minValue: 2.2,
          maxValue: 5.0,
          step: 1.0,
          iconName: 'height',
          group: 'dimensions',
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.engineering.vozduhoobmen_minimum_3_m'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.engineering.ustanavlivayte_reshetki_vverhu_dlya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.engineering.proverte_tyagu_pered_montazhom'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.engineering.vozduhoobmen_minimum_3_m'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.engineering.ustanavlivayte_reshetki_vverhu_dlya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.engineering.proverte_tyagu_pered_montazhom'),
      ],
      useCase: CalculateVentilation(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'ventilation',
        'engineering',
        'tag.inzhenernye_raboty',
        'tag.ventilyatsiya',
        'engineering_ventilation',
      ],
    ),
];