// GENERATED FILE - do not edit by hand.
// CalculatorDefinitionV2 entries used by the app.

import '../../../core/enums/calculator_category.dart';
import '../../../core/enums/field_input_type.dart';
import '../../../core/enums/unit_type.dart';
import '../../models/calculator_definition_v2.dart';
import '../../models/calculator_field.dart';
import '../../models/calculator_hint.dart';
import '../calculator_constants.dart';
import '../../usecases/canonical_bridge.dart';
import '../../usecases/electric_canonical_adapter.dart';
// heating_canonical_adapter.dart — больше не используется (engineering_heating удалён)
// calculate_plumbing.dart — удалён (engineering_plumbing не востребован)
import '../../usecases/ventilation_canonical_adapter.dart';

final List<CalculatorDefinitionV2> engineeringCalculators = [
  const CalculatorDefinitionV2(
    id: 'engineering_electrics',
    titleKey: 'calculator.engineering_electrics.title',
    descriptionKey: 'calculator.engineering_electrics.description',
    category: CalculatorCategory.interior,
    subCategoryKey: 'subcategory.electrics',
    fields: [
      CalculatorField(
        key: 'apartmentArea',
        labelKey: 'input.apartmentArea',
        unitType: UnitType.squareMeters,
        inputType: FieldInputType.slider,
        defaultValue: 60.0,
        minValue: 20.0,
        maxValue: 500.0,
        step: 5.0,
        iconName: 'square_foot',
        group: 'dimensions',
        required: true,
        order: 1,
      ),
      CalculatorField(
        key: 'roomsCount',
        labelKey: 'input.roomsCount',
        unitType: UnitType.pieces,
        inputType: FieldInputType.slider,
        defaultValue: 3.0,
        minValue: 1.0,
        maxValue: 10.0,
        step: 1.0,
        iconName: 'meeting_room',
        group: 'dimensions',
        required: true,
        order: 2,
      ),
      CalculatorField(
        key: 'ceilingHeight',
        labelKey: 'input.ceilingHeight',
        unitType: UnitType.meters,
        inputType: FieldInputType.slider,
        defaultValue: 2.7,
        minValue: 2.4,
        maxValue: 4.0,
        step: 0.1,
        iconName: 'height',
        group: 'dimensions',
        required: true,
        order: 3,
      ),
      CalculatorField(
        key: 'wiringType',
        labelKey: 'input.wiringType',
        unitType: UnitType.pieces,
        inputType: FieldInputType.select,
        defaultValue: 0.0,
        minValue: 0.0,
        maxValue: 1.0,
        iconName: 'cable',
        group: 'options',
        required: true,
        order: 4,
        options: [
          FieldOption(value: 0, labelKey: 'electrical.wiring.hidden'),
          FieldOption(value: 1, labelKey: 'electrical.wiring.open'),
        ],
      ),
      CalculatorField(
        key: 'hasKitchen',
        labelKey: 'input.hasKitchen',
        unitType: UnitType.pieces,
        inputType: FieldInputType.switch_,
        defaultValue: 1.0,
        minValue: 0.0,
        maxValue: 1.0,
        iconName: 'electric_bolt',
        group: 'options',
        required: false,
        order: 5,
      ),
      CalculatorField(
        key: 'cablePurchaseMode',
        labelKey: 'input.cablePurchaseMode',
        hintKey: 'input.cablePurchaseModeHint',
        unitType: UnitType.pieces,
        inputType: FieldInputType.select,
        defaultValue: 0.0,
        minValue: 0.0,
        maxValue: 1.0,
        iconName: 'inventory_2',
        group: 'options',
        required: true,
        order: 6,
        options: [
          FieldOption(value: 0, labelKey: 'input.cablePurchasePerMeter'),
          FieldOption(value: 1, labelKey: 'input.cablePurchaseSpool50m'),
        ],
      ),
      CalculatorField(
        key: 'reserve',
        labelKey: 'input.reserve',
        hintKey: 'input.electricReserveHint',
        unitType: UnitType.percent,
        inputType: FieldInputType.slider,
        defaultValue: 15.0,
        minValue: 5.0,
        maxValue: 30.0,
        step: 5.0,
        iconName: 'add_chart',
        group: 'options',
        required: true,
        order: 7,
      ),
    ],
    beforeHints: [
      CalculatorHint(
        type: HintType.tip,
        messageKey:
            'hint.engineering.raboty_dolzhen_vypolnyat_kvalifitsirovannyy',
      ),
      CalculatorHint(
        type: HintType.tip,
        messageKey: 'hint.engineering.ispolzuyte_kabel_secheniem_ne',
      ),
      CalculatorHint(
        type: HintType.tip,
        messageKey: 'hint.engineering.ustanovite_uzo_dlya_zaschity',
      ),
      CalculatorHint(
        type: HintType.tip,
        messageKey: 'hint.engineering.proverte_vse_soedineniya_pered',
      ),
    ],
    afterHints: [
      CalculatorHint(
        type: HintType.tip,
        messageKey:
            'hint.engineering.raboty_dolzhen_vypolnyat_kvalifitsirovannyy',
      ),
      CalculatorHint(
        type: HintType.tip,
        messageKey: 'hint.engineering.ispolzuyte_kabel_secheniem_ne',
      ),
      CalculatorHint(
        type: HintType.tip,
        messageKey: 'hint.engineering.ustanovite_uzo_dlya_zaschity',
      ),
      CalculatorHint(
        type: HintType.tip,
        messageKey: 'hint.engineering.proverte_vse_soedineniya_pered',
      ),
    ],
    useCase: CanonicalBridgeUseCase(calculateCanonicalElectric),
    accentColor: kCalculatorAccentColor,
    complexity: 2,
    popularity: 10,
    tags: [
      'engineering_electrics',
      'engineering',
      'tag.inzhenernye_raboty',
      'tag.elektrika',
      'electrics',
    ],
  ),
  // engineering_heating удалён — дубль floors_warm (тёплый пол)
  // engineering_plumbing удалён — слишком общий, не востребован
  const CalculatorDefinitionV2(
    id: 'engineering_ventilation',
    titleKey: 'calculator.engineering_ventilation.title',
    descriptionKey: 'calculator.engineering_ventilation.description',
    category: CalculatorCategory.interior,
    subCategoryKey: 'subcategory.ventilation',
    fields: [
      CalculatorField(
        key: 'calculationMode',
        labelKey: 'input.ventilation.calculationMode',
        hintKey: 'input.ventilation.calculationMode.hint',
        unitType: UnitType.pieces,
        inputType: FieldInputType.radio,
        defaultValue: 0,
        minValue: 0,
        maxValue: 1,
        iconName: 'air',
        group: 'ventilation_airflow',
        required: true,
        order: 1,
        options: [
          FieldOption(
            value: 0,
            labelKey: 'input.ventilation.calculationMode.residential',
          ),
          FieldOption(
            value: 1,
            labelKey: 'input.ventilation.calculationMode.project',
          ),
        ],
      ),
      CalculatorField(
        key: 'totalArea',
        labelKey: 'input.ventilation.totalArea',
        hintKey: 'input.ventilation.totalArea.hint',
        unitType: UnitType.squareMeters,
        defaultValue: 80,
        minValue: 10,
        maxValue: 1000,
        step: 0.1,
        iconName: 'square_foot',
        group: 'ventilation_airflow',
        required: true,
        order: 2,
        dependency: FieldDependency(
          fieldKey: 'calculationMode',
          condition: DependencyCondition.equals,
          value: 0,
        ),
      ),
      CalculatorField(
        key: 'ceilingHeight',
        labelKey: 'input.ventilation.ceilingHeight',
        hintKey: 'input.ventilation.ceilingHeight.hint',
        unitType: UnitType.meters,
        defaultValue: 2.7,
        minValue: 2.2,
        maxValue: 5,
        step: 0.05,
        iconName: 'height',
        group: 'ventilation_airflow',
        required: true,
        order: 3,
        dependency: FieldDependency(
          fieldKey: 'calculationMode',
          condition: DependencyCondition.equals,
          value: 0,
        ),
      ),
      CalculatorField(
        key: 'peopleCount',
        labelKey: 'input.ventilation.peopleCount',
        unitType: UnitType.pieces,
        defaultValue: 3,
        minValue: 1,
        maxValue: 50,
        step: 1,
        iconName: 'people',
        group: 'ventilation_airflow',
        required: true,
        order: 4,
        dependency: FieldDependency(
          fieldKey: 'calculationMode',
          condition: DependencyCondition.equals,
          value: 0,
        ),
      ),
      CalculatorField(
        key: 'projectAirflowM3h',
        labelKey: 'input.ventilation.projectAirflowM3h',
        hintKey: 'input.ventilation.projectAirflowM3h.hint',
        unitType: UnitType.cubicMetersPerHour,
        defaultValue: 300,
        minValue: 1,
        maxValue: 100000,
        step: 10,
        iconName: 'speed',
        group: 'ventilation_airflow',
        required: true,
        order: 5,
        dependency: FieldDependency(
          fieldKey: 'calculationMode',
          condition: DependencyCondition.equals,
          value: 1,
        ),
      ),
      CalculatorField(
        key: 'ductShape',
        labelKey: 'input.ventilation.ductShape',
        unitType: UnitType.pieces,
        inputType: FieldInputType.radio,
        defaultValue: 0,
        minValue: 0,
        maxValue: 1,
        iconName: 'view_in_ar',
        group: 'ventilation_duct',
        required: true,
        order: 6,
        options: [
          FieldOption(value: 0, labelKey: 'input.ventilation.ductShape.round'),
          FieldOption(value: 1, labelKey: 'input.ventilation.ductShape.rect'),
        ],
      ),
      CalculatorField(
        key: 'roundDiameterMm',
        labelKey: 'input.ventilation.roundDiameterMm',
        unitType: UnitType.millimeters,
        defaultValue: 200,
        minValue: 80,
        maxValue: 2000,
        step: 5,
        iconName: 'circle_outlined',
        group: 'ventilation_duct',
        required: true,
        order: 7,
        dependency: FieldDependency(
          fieldKey: 'ductShape',
          condition: DependencyCondition.equals,
          value: 0,
        ),
      ),
      CalculatorField(
        key: 'rectWidthMm',
        labelKey: 'input.ventilation.rectWidthMm',
        unitType: UnitType.millimeters,
        defaultValue: 300,
        minValue: 100,
        maxValue: 3000,
        step: 10,
        iconName: 'width_normal',
        group: 'ventilation_duct',
        required: true,
        order: 8,
        dependency: FieldDependency(
          fieldKey: 'ductShape',
          condition: DependencyCondition.equals,
          value: 1,
        ),
      ),
      CalculatorField(
        key: 'rectHeightMm',
        labelKey: 'input.ventilation.rectHeightMm',
        unitType: UnitType.millimeters,
        defaultValue: 200,
        minValue: 50,
        maxValue: 3000,
        step: 10,
        iconName: 'height',
        group: 'ventilation_duct',
        required: true,
        order: 9,
        dependency: FieldDependency(
          fieldKey: 'ductShape',
          condition: DependencyCondition.equals,
          value: 1,
        ),
      ),
      CalculatorField(
        key: 'targetVelocityMps',
        labelKey: 'input.ventilation.targetVelocityMps',
        hintKey: 'input.ventilation.targetVelocityMps.hint',
        unitType: UnitType.metersPerSecond,
        defaultValue: 3,
        minValue: 0.5,
        maxValue: 15,
        step: 0.1,
        iconName: 'speed',
        group: 'ventilation_duct',
        required: true,
        order: 10,
      ),
      CalculatorField(
        key: 'selectedFanCapacityM3h',
        labelKey: 'input.ventilation.selectedFanCapacityM3h',
        hintKey: 'input.ventilation.selectedFanCapacityM3h.hint',
        unitType: UnitType.cubicMetersPerHour,
        defaultValue: 0,
        minValue: 0,
        maxValue: 100000,
        step: 10,
        iconName: 'mode_fan_off',
        group: 'ventilation_duct',
        required: false,
        order: 11,
      ),
      CalculatorField(
        key: 'ductLengthM',
        labelKey: 'input.ventilation.ductLengthM',
        hintKey: 'input.ventilation.ductLengthM.hint',
        unitType: UnitType.meters,
        defaultValue: 0,
        minValue: 0,
        maxValue: 10000,
        step: 0.1,
        iconName: 'straighten',
        group: 'ventilation_purchase',
        required: false,
        order: 12,
      ),
      CalculatorField(
        key: 'stockLengthM',
        labelKey: 'input.ventilation.stockLengthM',
        unitType: UnitType.meters,
        defaultValue: 3,
        minValue: 0.1,
        maxValue: 50,
        step: 0.1,
        iconName: 'inventory_2',
        group: 'ventilation_purchase',
        required: true,
        order: 13,
      ),
      CalculatorField(
        key: 'ductReservePercent',
        labelKey: 'input.ventilation.ductReservePercent',
        hintKey: 'input.ventilation.ductReservePercent.hint',
        unitType: UnitType.percent,
        defaultValue: 10,
        minValue: 0,
        maxValue: 30,
        step: 1,
        iconName: 'add_chart',
        group: 'ventilation_purchase',
        required: true,
        order: 14,
      ),
      CalculatorField(
        key: 'fittingCount',
        labelKey: 'input.ventilation.fittingCount',
        unitType: UnitType.pieces,
        defaultValue: 0,
        minValue: 0,
        maxValue: 10000,
        step: 1,
        iconName: 'turn_right',
        group: 'ventilation_purchase',
        required: false,
        order: 15,
      ),
      CalculatorField(
        key: 'airTerminalCount',
        labelKey: 'input.ventilation.airTerminalCount',
        unitType: UnitType.pieces,
        defaultValue: 0,
        minValue: 0,
        maxValue: 10000,
        step: 1,
        iconName: 'grid_view',
        group: 'ventilation_purchase',
        required: false,
        order: 16,
      ),
      CalculatorField(
        key: 'clampCount',
        labelKey: 'input.ventilation.clampCount',
        unitType: UnitType.pieces,
        defaultValue: 0,
        minValue: 0,
        maxValue: 50000,
        step: 1,
        iconName: 'hardware',
        group: 'ventilation_purchase',
        required: false,
        order: 17,
      ),
    ],
    useCase: CanonicalBridgeUseCase(calculateCanonicalVentilation),
    accentColor: kCalculatorAccentColor,
    complexity: 3,
    popularity: 10,
    tags: [
      'ventilation',
      'engineering',
      'tag.inzhenernye_raboty',
      'tag.ventilyatsiya',
      'engineering_ventilation',
    ],
  ),
];
