// GENERATED FILE - do not edit by hand.
// CalculatorDefinitionV2 entries used by the app.

import '../../../core/enums/calculator_category.dart';
import '../../../core/enums/field_input_type.dart';
import '../../../core/enums/unit_type.dart';
import '../../models/calculator_definition_v2.dart';
import '../../models/calculator_field.dart';
import '../../models/calculator_hint.dart';
import '../calculator_constants.dart';
import '../../usecases/calculate_brick_facing.dart';
import '../../usecases/calculate_facade_panels.dart';
import '../../usecases/calculate_fence_v2.dart';
import '../../usecases/calculate_stairs.dart';
import '../../usecases/calculate_terrace.dart';
import '../../usecases/calculate_insulation_mineral_wool.dart';

final List<CalculatorDefinitionV2> facadeCalculators = [
  CalculatorDefinitionV2(
      id: 'exterior_brick',
      titleKey: 'calculator.exterior_brick.title',
      descriptionKey: 'calculator.exterior_brick.description',
      category: CalculatorCategory.exterior,
      subCategoryKey: 'subcategory.brick_facing',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.slider,
          defaultValue: 50.0,
          minValue: 5.0,
          maxValue: 1000.0,
          step: 1.0,
          iconName: 'square_foot',
          group: 'dimensions',
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'thickness',
          labelKey: 'input.thickness',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 0.5,
          minValue: 0.5,
          maxValue: 1.0,
          step: 1.0,
          iconName: 'width_normal',
          group: 'material',
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'windowsArea',
          labelKey: 'input.windowsArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.slider,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 200.0,
          step: 1.0,
          iconName: 'window',
          group: 'openings',
          required: false,
          order: 3,
        ),
        const CalculatorField(
          key: 'doorsArea',
          labelKey: 'input.doorsArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.slider,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 50.0,
          step: 1.0,
          iconName: 'door_front',
          group: 'openings',
          required: false,
          order: 4,
        ),
        const CalculatorField(
          key: 'perimeter',
          labelKey: 'input.perimeter',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 20.0,
          minValue: 4.0,
          maxValue: 200.0,
          step: 1.0,
          iconName: 'crop_square',
          group: 'dimensions',
          required: true,
          order: 5,
        ),
        const CalculatorField(
          key: 'wallHeight',
          labelKey: 'input.wallHeight',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 2.5,
          minValue: 2.0,
          maxValue: 15.0,
          step: 1.0,
          iconName: 'height',
          group: 'dimensions',
          required: true,
          order: 6,
        ),
        const CalculatorField(
          key: 'workingConditions',
          labelKey: 'input.workingConditions',
          unitType: UnitType.pieces,
          inputType: FieldInputType.select,
          defaultValue: 1.0,
          iconName: 'thermostat',
          group: 'conditions',
          required: false,
          order: 10,
          options: [
            FieldOption(value: 1.0, labelKey: 'input.workingConditions.normal'),
            FieldOption(value: 2.0, labelKey: 'input.workingConditions.windy'),
            FieldOption(value: 3.0, labelKey: 'input.workingConditions.cold'),
            FieldOption(value: 4.0, labelKey: 'input.workingConditions.hot'),
          ],
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ispolzuyte_oblitsovochnyy_kirpich_s'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.armiruyte_cherez_kazhdye_5'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.proveryayte_vertikalnost_kazhdogo_ryada'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.zaschitite_kladku_ot_dozhdya'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ispolzuyte_oblitsovochnyy_kirpich_s'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.armiruyte_cherez_kazhdye_5'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.proveryayte_vertikalnost_kazhdogo_ryada'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.zaschitite_kladku_ot_dozhdya'),
        const CalculatorHint(
          type: HintType.warning,
          messageKey: 'hint.brick.cold_weather_warning',
          condition: HintCondition(
            type: HintConditionType.equals,
            fieldKey: 'workingConditions',
            value: 3,
          ),
        ),
      ],
      useCase: CalculateBrickFacing(),
      accentColor: kCalculatorAccentColor,
      complexity: 3,
      popularity: 10,
      tags: [
        'tag.oblitsovochnyy_kirpich',
        'exterior',
        'exterior_brick',
        'tag.naruzhnaya_otdelka',
        'brick',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'exterior_facade_panels',
      titleKey: 'calculator.exterior_facade_panels.title',
      descriptionKey: 'calculator.exterior_facade_panels.description',
      category: CalculatorCategory.exterior,
      subCategoryKey: 'subcategory.facade_panels',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.slider,
          defaultValue: 50.0,
          minValue: 5.0,
          maxValue: 1000.0,
          step: 1.0,
          iconName: 'square_foot',
          group: 'dimensions',
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'panelWidth',
          labelKey: 'input.panelWidth',
          unitType: UnitType.centimeters,
          inputType: FieldInputType.slider,
          defaultValue: 50.0,
          minValue: 10.0,
          maxValue: 150.0,
          step: 5.0,
          iconName: 'width_normal',
          group: 'material',
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'panelHeight',
          labelKey: 'input.panelHeight',
          unitType: UnitType.centimeters,
          inputType: FieldInputType.slider,
          defaultValue: 100.0,
          minValue: 20.0,
          maxValue: 200.0,
          step: 5.0,
          iconName: 'height',
          group: 'material',
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'perimeter',
          labelKey: 'input.perimeter',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 20.0,
          minValue: 4.0,
          maxValue: 200.0,
          step: 1.0,
          iconName: 'crop_square',
          group: 'dimensions',
          required: true,
          order: 4,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.fasadnye_paneli_dolgovechny_i'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ispolzuyte_kachestvennye_krepleniya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ostavlyayte_zazor_dlya_temperaturnogo'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.fasadnye_paneli_dolgovechny_i'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ispolzuyte_kachestvennye_krepleniya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ostavlyayte_zazor_dlya_temperaturnogo'),
      ],
      useCase: CalculateFacadePanels(),
      accentColor: kCalculatorAccentColor,
      complexity: 3,
      popularity: 10,
      tags: [
        'tag.fasadnye_paneli',
        'exterior',
        'facade',
        'exterior_facade_panels',
        'panels',
        'tag.naruzhnaya_otdelka',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'fence',
      titleKey: 'calculator.fence.title',
      descriptionKey: 'calculator.fence.description',
      category: CalculatorCategory.exterior,
      subCategoryKey: 'subcategory.fences',
      fields: [
        const CalculatorField(
          key: 'fenceLength',
          labelKey: 'input.length',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 50.0,
          minValue: 1.0,
          maxValue: 1000.0,
          step: 1.0,
          iconName: 'straighten',
          group: 'dimensions',
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'fenceHeight',
          labelKey: 'input.height',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 2.0,
          minValue: 1.0,
          maxValue: 3.0,
          step: 0.1,
          iconName: 'height',
          group: 'dimensions',
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'postSpacing',
          labelKey: 'input.postSpacing',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 2.5,
          minValue: 2.0,
          maxValue: 3.5,
          step: 0.1,
          iconName: 'fence',
          group: 'dimensions',
          required: false,
          order: 3,
        ),
        const CalculatorField(
          key: 'fenceType',
          labelKey: 'input.fenceType',
          unitType: UnitType.pieces,
          inputType: FieldInputType.select,
          defaultValue: 0.0,
          iconName: 'category',
          group: 'material',
          required: true,
          order: 4,
          options: [
            FieldOption(value: 0.0, labelKey: 'input.fenceType.profsheet'),
            FieldOption(value: 1.0, labelKey: 'input.fenceType.picket'),
            FieldOption(value: 2.0, labelKey: 'input.fenceType.chainlink'),
          ],
        ),
        const CalculatorField(
          key: 'gates',
          labelKey: 'input.gates',
          unitType: UnitType.pieces,
          inputType: FieldInputType.slider,
          defaultValue: 1.0,
          minValue: 0.0,
          maxValue: 5.0,
          step: 1.0,
          iconName: 'door_sliding',
          group: 'options',
          required: false,
          order: 4,
        ),
        const CalculatorField(
          key: 'wickets',
          labelKey: 'input.wickets',
          unitType: UnitType.pieces,
          inputType: FieldInputType.slider,
          defaultValue: 1.0,
          minValue: 0.0,
          maxValue: 5.0,
          step: 1.0,
          iconName: 'door_front',
          group: 'options',
          required: false,
          order: 5,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.stolby_ustanavlivayutsya_na_glubinu'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.dlya_proflista_ispolzuyte_otsinkovannye'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.derevyannyy_zabor_trebuet_obrabotki'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.kirpichnyy_zabor_nuzhdaetsya_v'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.rasstoyanie_mezhdu_stolbami_2'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.vorota_i_kalitki_dolzhny'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.stolby_ustanavlivayutsya_na_glubinu'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.dlya_proflista_ispolzuyte_otsinkovannye'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.derevyannyy_zabor_trebuet_obrabotki'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.kirpichnyy_zabor_nuzhdaetsya_v'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.rasstoyanie_mezhdu_stolbami_2'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.vorota_i_kalitki_dolzhny'),
      ],
      useCase: CalculateFenceV2(),
      accentColor: kCalculatorAccentColor,
      complexity: 3,
      popularity: 10,
      tags: [
        'tag.konstruktsii',
        'tag.zabory',
        'fence',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'stairs',
      titleKey: 'calculator.stairs.title',
      descriptionKey: 'calculator.stairs.description',
      category: CalculatorCategory.exterior,
      subCategoryKey: 'subcategory.stairs',
      fields: [
        const CalculatorField(
          key: 'floorHeight',
          labelKey: 'input.floorHeight',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 3.0,
          minValue: 2.0,
          maxValue: 6.0,
          step: 1.0,
          iconName: 'height',
          group: 'dimensions',
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'stepHeight',
          labelKey: 'input.stepHeight',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 0.18,
          minValue: 0.1,
          maxValue: 0.3,
          step: 0.01,
          iconName: 'height',
          group: 'dimensions',
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'stepWidth',
          labelKey: 'input.stepWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 0.28,
          minValue: 0.2,
          maxValue: 0.4,
          step: 0.01,
          iconName: 'width_normal',
          group: 'dimensions',
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'stepCount',
          labelKey: 'input.stepCount',
          unitType: UnitType.pieces,
          inputType: FieldInputType.slider,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 50.0,
          step: 1.0,
          iconName: 'format_list_numbered',
          group: 'dimensions',
          required: false,
          order: 4,
        ),
        const CalculatorField(
          key: 'width',
          labelKey: 'input.width',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 1.0,
          minValue: 0.6,
          maxValue: 2.0,
          step: 1.0,
          iconName: 'straighten',
          group: 'dimensions',
          required: true,
          order: 5,
        ),
        const CalculatorField(
          key: 'materialType',
          labelKey: 'input.type',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          minValue: 1.0,
          maxValue: 3.0,
          iconName: 'category',
          group: 'material',
          required: true,
          order: 6,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.vysota_stupeni_dolzhna_byt'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.shirina_prostupi_stupeni_dolzhna'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.shirina_lestnitsy_dlya_zhilyh'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.dlya_derevyannoy_lestnitsy_ispolzuyte'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.betonnaya_lestnitsa_trebuet_armirovaniya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.perila_dolzhny_byt_na'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.balyasiny_ustanavlivayutsya_s_shagom'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.vysota_stupeni_dolzhna_byt'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.shirina_prostupi_stupeni_dolzhna'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.shirina_lestnitsy_dlya_zhilyh'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.dlya_derevyannoy_lestnitsy_ispolzuyte'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.betonnaya_lestnitsa_trebuet_armirovaniya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.perila_dolzhny_byt_na'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.balyasiny_ustanavlivayutsya_s_shagom'),
      ],
      useCase: CalculateStairs(),
      accentColor: kCalculatorAccentColor,
      complexity: 3,
      popularity: 10,
      tags: [
        'tag.konstruktsii',
        'stairs',
        'tag.lestnitsy',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'terrace',
      titleKey: 'calculator.terrace.title',
      descriptionKey: 'calculator.terrace.description',
      category: CalculatorCategory.exterior,
      subCategoryKey: 'subcategory.terrace_veranda',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.slider,
          defaultValue: 20.0,
          minValue: 2.0,
          maxValue: 200.0,
          step: 1.0,
          iconName: 'square_foot',
          group: 'dimensions',
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'floorType',
          labelKey: 'input.floorType',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          minValue: 1.0,
          maxValue: 3.0,
          iconName: 'category',
          group: 'material',
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'railing',
          labelKey: 'input.railing',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 1.0,
          minValue: 0.0,
          maxValue: 50.0,
          step: 1.0,
          iconName: 'fence',
          group: 'options',
          required: false,
          order: 3,
        ),
        const CalculatorField(
          key: 'roof',
          labelKey: 'input.roof',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 200.0,
          step: 1.0,
          iconName: 'roofing',
          group: 'options',
          required: false,
          order: 4,
        ),
        const CalculatorField(
          key: 'roofType',
          labelKey: 'input.roofType',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          minValue: 1.0,
          maxValue: 3.0,
          iconName: 'category',
          group: 'options',
          required: false,
          order: 5,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.terrasnaya_doska_deking_ustoychiva'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.plitka_dlya_terrasy_dolzhna'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ograzhdenie_obespechivaet_bezopasnost_osobenno'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.krovlya_zaschischaet_ot_dozhdya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.polikarbonat_propuskaet_svet_i'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.stolby_dlya_krovli_dolzhny'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.terrasnaya_doska_deking_ustoychiva'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.plitka_dlya_terrasy_dolzhna'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ograzhdenie_obespechivaet_bezopasnost_osobenno'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.krovlya_zaschischaet_ot_dozhdya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.polikarbonat_propuskaet_svet_i'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.stolby_dlya_krovli_dolzhny'),
      ],
      useCase: CalculateTerrace(),
      accentColor: kCalculatorAccentColor,
      complexity: 3,
      popularity: 10,
      tags: [
        'terrace',
        'tag.konstruktsii',
        'tag.terrasa_veranda',
      ],
    ),
  // Утеплитель минеральная вата
  CalculatorDefinitionV2(
      id: 'insulation_mineral_wool',
      titleKey: 'calculator.insulation_mineral_wool.title',
      descriptionKey: 'calculator.insulation_mineral_wool.description',
      category: CalculatorCategory.exterior,
      subCategoryKey: 'subcategory.insulation',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.slider,
          defaultValue: 20.0,
          minValue: 1.0,
          maxValue: 500.0,
          step: 1.0,
          iconName: 'square_foot',
          group: 'dimensions',
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'thickness',
          labelKey: 'input.thickness',
          unitType: UnitType.millimeters,
          inputType: FieldInputType.slider,
          defaultValue: 100.0,
          minValue: 50.0,
          maxValue: 300.0,
          step: 10.0,
          iconName: 'height',
          group: 'material',
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'density',
          labelKey: 'input.density',
          unitType: UnitType.kilograms,
          inputType: FieldInputType.slider,
          defaultValue: 50.0,
          minValue: 30.0,
          maxValue: 200.0,
          step: 5.0,
          iconName: 'density_medium',
          group: 'material',
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'applicationSurface',
          labelKey: 'input.applicationSurface',
          unitType: UnitType.pieces,
          inputType: FieldInputType.select,
          defaultValue: 1.0,
          iconName: 'wall',
          group: 'conditions',
          required: true,
          order: 4,
          options: [
            FieldOption(value: 1.0, labelKey: 'input.applicationSurface.wall'),
            FieldOption(value: 2.0, labelKey: 'input.applicationSurface.floor'),
            FieldOption(value: 3.0, labelKey: 'input.applicationSurface.ceiling'),
            FieldOption(value: 4.0, labelKey: 'input.applicationSurface.roofSlope'),
          ],
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.insulation.vapor_barrier_inside'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.insulation.wind_barrier_outside'),
      ],
      afterHints: [
        const CalculatorHint(
          type: HintType.warning,
          messageKey: 'hint.insulation.thin_exterior_warning',
          condition: HintCondition(
            type: HintConditionType.lessThan,
            resultKey: 'thickness',
            value: 100,
          ),
        ),
      ],
      useCase: CalculateInsulationMineralWool(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 8,
      tags: [
        'tag.naruzhnaya_otdelka',
        'insulation',
        'mineral_wool',
        'insulation_mineral_wool',
      ],
    ),
];