// GENERATED FILE - do not edit by hand.
// CalculatorDefinitionV2 entries used by the app.

import '../../../core/enums/calculator_category.dart';
import '../../../core/enums/field_input_type.dart';
import '../../../core/enums/unit_type.dart';
import '../../models/calculator_definition_v2.dart';
import '../../models/calculator_field.dart';
import '../../models/calculator_hint.dart';
import '../calculator_constants.dart';
import '../../usecases/calculate_brick_facing.dart';
import '../../usecases/calculate_facade_panels.dart';
import '../../usecases/calculate_fence.dart';
import '../../usecases/calculate_siding.dart';
import '../../usecases/calculate_stairs.dart';
import '../../usecases/calculate_terrace.dart';
import '../../usecases/calculate_wet_facade.dart';
import '../../usecases/calculate_wood_facade.dart';

final List<CalculatorDefinitionV2> facadeCalculators = [
  CalculatorDefinitionV2(
      id: 'exterior_brick',
      titleKey: 'calculator.exterior_brick.title',
      descriptionKey: 'calculator.exterior_brick.description',
      category: CalculatorCategory.exterior,
      subCategoryKey: 'subcategory.brick_facing',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'thickness',
          labelKey: 'input.thickness',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.5,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'windowsArea',
          labelKey: 'input.windowsArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'doorsArea',
          labelKey: 'input.doorsArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 4,
        ),
        const CalculatorField(
          key: 'perimeter',
          labelKey: 'input.perimeter',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 5,
        ),
        const CalculatorField(
          key: 'wallHeight',
          labelKey: 'input.wallHeight',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 2.5,
          required: true,
          order: 6,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ispolzuyte_oblitsovochnyy_kirpich_s'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.armiruyte_cherez_kazhdye_5'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.proveryayte_vertikalnost_kazhdogo_ryada'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.zaschitite_kladku_ot_dozhdya'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ispolzuyte_oblitsovochnyy_kirpich_s'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.armiruyte_cherez_kazhdye_5'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.proveryayte_vertikalnost_kazhdogo_ryada'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.zaschitite_kladku_ot_dozhdya'),
      ],
      useCase: CalculateBrickFacing(),
      accentColor: kCalculatorAccentColor,
      complexity: 3,
      popularity: 10,
      tags: [
        'tag.oblitsovochnyy_kirpich',
        'exterior',
        'exterior_brick',
        'tag.naruzhnaya_otdelka',
        'brick',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'exterior_facade_panels',
      titleKey: 'calculator.exterior_facade_panels.title',
      descriptionKey: 'calculator.exterior_facade_panels.description',
      category: CalculatorCategory.exterior,
      subCategoryKey: 'subcategory.facade_panels',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'panelWidth',
          labelKey: 'input.panelWidth',
          unitType: UnitType.centimeters,
          inputType: FieldInputType.number,
          defaultValue: 50.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'panelHeight',
          labelKey: 'input.panelHeight',
          unitType: UnitType.centimeters,
          inputType: FieldInputType.number,
          defaultValue: 100.0,
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'perimeter',
          labelKey: 'input.perimeter',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 4,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.fasadnye_paneli_dolgovechny_i'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ispolzuyte_kachestvennye_krepleniya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ostavlyayte_zazor_dlya_temperaturnogo'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.fasadnye_paneli_dolgovechny_i'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ispolzuyte_kachestvennye_krepleniya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ostavlyayte_zazor_dlya_temperaturnogo'),
      ],
      useCase: CalculateFacadePanels(),
      accentColor: kCalculatorAccentColor,
      complexity: 3,
      popularity: 10,
      tags: [
        'tag.fasadnye_paneli',
        'exterior',
        'facade',
        'exterior_facade_panels',
        'panels',
        'tag.naruzhnaya_otdelka',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'exterior_siding',
      titleKey: 'calculator.exterior_siding.title',
      descriptionKey: 'calculator.exterior_siding.description',
      category: CalculatorCategory.exterior,
      subCategoryKey: 'subcategory.siding',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 10.0,
          maxValue: 1000.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'panelWidth',
          labelKey: 'input.panelWidth',
          unitType: UnitType.centimeters,
          inputType: FieldInputType.number,
          defaultValue: 20.0,
          minValue: 10.0,
          maxValue: 50.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'panelLength',
          labelKey: 'input.panelLength',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 300.0,
          minValue: 200.0,
          maxValue: 600.0,
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'perimeter',
          labelKey: 'input.perimeter',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 200.0,
          required: false,
          order: 4,
        ),
        const CalculatorField(
          key: 'corners',
          labelKey: 'input.corners',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 4.0,
          minValue: 4.0,
          maxValue: 20.0,
          required: true,
          order: 5,
        ),
        const CalculatorField(
          key: 'soffitLength',
          labelKey: 'input.soffitLength',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 100.0,
          required: false,
          order: 6,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ne_zabudte_j_profil'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ostavlyayte_temperaturnye_zazory_5'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.montiruyte_sayding_snizu_vverh'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ispolzuyte_samorezy_s_press'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ne_zabudte_j_profil'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ostavlyayte_temperaturnye_zazory_5'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.montiruyte_sayding_snizu_vverh'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ispolzuyte_samorezy_s_press'),
      ],
      useCase: CalculateSiding(),
      accentColor: kCalculatorAccentColor,
      complexity: 3,
      popularity: 10,
      tags: [
        'exterior_siding',
        'siding',
        'tag.sayding',
        'tag.naruzhnaya_otdelka',
        'exterior',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'exterior_wet_facade',
      titleKey: 'calculator.exterior_wet_facade.title',
      descriptionKey: 'calculator.exterior_wet_facade.description',
      category: CalculatorCategory.exterior,
      subCategoryKey: 'subcategory.wet_facade',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'insulationThickness',
          labelKey: 'input.insulationThickness',
          unitType: UnitType.millimeters,
          inputType: FieldInputType.number,
          defaultValue: 100.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'insulationType',
          labelKey: 'input.insulationType',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 2.0,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.raboty_vypolnyayte_pri_temperature'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ispolzuyte_armiruyuschuyu_setku_dlya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.nanosite_shtukaturku_v_dva'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.zaschitite_fasad_ot_dozhdya'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.raboty_vypolnyayte_pri_temperature'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ispolzuyte_armiruyuschuyu_setku_dlya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.nanosite_shtukaturku_v_dva'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.zaschitite_fasad_ot_dozhdya'),
      ],
      useCase: CalculateWetFacade(),
      accentColor: kCalculatorAccentColor,
      complexity: 3,
      popularity: 10,
      tags: [
        'exterior_wet_facade',
        'wet',
        'facade',
        'tag.naruzhnaya_otdelka',
        'tag.mokryy_fasad',
        'exterior',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'exterior_wood',
      titleKey: 'calculator.exterior_wood.title',
      descriptionKey: 'calculator.exterior_wood.description',
      category: CalculatorCategory.exterior,
      subCategoryKey: 'subcategory.wood',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'boardWidth',
          labelKey: 'input.boardWidth',
          unitType: UnitType.centimeters,
          inputType: FieldInputType.number,
          defaultValue: 14.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'boardLength',
          labelKey: 'input.boardLength',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 3.0,
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'perimeter',
          labelKey: 'input.perimeter',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 4,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ispolzuyte_zaschitnye_sostavy_dlya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.obrabatyvayte_tortsy_dosok'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ostavlyayte_zazor_dlya_ventilyatsii'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ispolzuyte_zaschitnye_sostavy_dlya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.obrabatyvayte_tortsy_dosok'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ostavlyayte_zazor_dlya_ventilyatsii'),
      ],
      useCase: CalculateWoodFacade(),
      accentColor: kCalculatorAccentColor,
      complexity: 3,
      popularity: 10,
      tags: [
        'wood',
        'exterior_wood',
        'tag.derevo',
        'tag.naruzhnaya_otdelka',
        'exterior',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'fence',
      titleKey: 'calculator.fence.title',
      descriptionKey: 'calculator.fence.description',
      category: CalculatorCategory.exterior,
      subCategoryKey: 'subcategory.fences',
      fields: [
        const CalculatorField(
          key: 'length',
          labelKey: 'input.length',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'height',
          labelKey: 'input.height',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 2.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'materialType',
          labelKey: 'input.type',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'gates',
          labelKey: 'input.gates',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: false,
          order: 4,
        ),
        const CalculatorField(
          key: 'wickets',
          labelKey: 'input.wickets',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: false,
          order: 5,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.stolby_ustanavlivayutsya_na_glubinu'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.dlya_proflista_ispolzuyte_otsinkovannye'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.derevyannyy_zabor_trebuet_obrabotki'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.kirpichnyy_zabor_nuzhdaetsya_v'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.rasstoyanie_mezhdu_stolbami_2'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.vorota_i_kalitki_dolzhny'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.stolby_ustanavlivayutsya_na_glubinu'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.dlya_proflista_ispolzuyte_otsinkovannye'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.derevyannyy_zabor_trebuet_obrabotki'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.kirpichnyy_zabor_nuzhdaetsya_v'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.rasstoyanie_mezhdu_stolbami_2'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.vorota_i_kalitki_dolzhny'),
      ],
      useCase: CalculateFence(),
      accentColor: kCalculatorAccentColor,
      complexity: 3,
      popularity: 10,
      tags: [
        'tag.konstruktsii',
        'tag.zabory',
        'fence',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'stairs',
      titleKey: 'calculator.stairs.title',
      descriptionKey: 'calculator.stairs.description',
      category: CalculatorCategory.exterior,
      subCategoryKey: 'subcategory.stairs',
      fields: [
        const CalculatorField(
          key: 'floorHeight',
          labelKey: 'input.floorHeight',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'stepHeight',
          labelKey: 'input.stepHeight',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.18,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'stepWidth',
          labelKey: 'input.stepWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.28,
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'stepCount',
          labelKey: 'input.stepCount',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: false,
          order: 4,
        ),
        const CalculatorField(
          key: 'width',
          labelKey: 'input.width',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: true,
          order: 5,
        ),
        const CalculatorField(
          key: 'materialType',
          labelKey: 'input.type',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: true,
          order: 6,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.vysota_stupeni_dolzhna_byt'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.shirina_prostupi_stupeni_dolzhna'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.shirina_lestnitsy_dlya_zhilyh'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.dlya_derevyannoy_lestnitsy_ispolzuyte'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.betonnaya_lestnitsa_trebuet_armirovaniya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.perila_dolzhny_byt_na'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.balyasiny_ustanavlivayutsya_s_shagom'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.vysota_stupeni_dolzhna_byt'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.shirina_prostupi_stupeni_dolzhna'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.shirina_lestnitsy_dlya_zhilyh'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.dlya_derevyannoy_lestnitsy_ispolzuyte'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.betonnaya_lestnitsa_trebuet_armirovaniya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.perila_dolzhny_byt_na'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.balyasiny_ustanavlivayutsya_s_shagom'),
      ],
      useCase: CalculateStairs(),
      accentColor: kCalculatorAccentColor,
      complexity: 3,
      popularity: 10,
      tags: [
        'tag.konstruktsii',
        'stairs',
        'tag.lestnitsy',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'terrace',
      titleKey: 'calculator.terrace.title',
      descriptionKey: 'calculator.terrace.description',
      category: CalculatorCategory.exterior,
      subCategoryKey: 'subcategory.terrace_veranda',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'floorType',
          labelKey: 'input.floorType',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'railing',
          labelKey: 'input.railing',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: false,
          order: 3,
        ),
        const CalculatorField(
          key: 'roof',
          labelKey: 'input.roof',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: false,
          order: 4,
        ),
        const CalculatorField(
          key: 'roofType',
          labelKey: 'input.roofType',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: false,
          order: 5,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.terrasnaya_doska_deking_ustoychiva'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.plitka_dlya_terrasy_dolzhna'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ograzhdenie_obespechivaet_bezopasnost_osobenno'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.krovlya_zaschischaet_ot_dozhdya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.polikarbonat_propuskaet_svet_i'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.stolby_dlya_krovli_dolzhny'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.terrasnaya_doska_deking_ustoychiva'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.plitka_dlya_terrasy_dolzhna'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.ograzhdenie_obespechivaet_bezopasnost_osobenno'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.krovlya_zaschischaet_ot_dozhdya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.polikarbonat_propuskaet_svet_i'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.facade.stolby_dlya_krovli_dolzhny'),
      ],
      useCase: CalculateTerrace(),
      accentColor: kCalculatorAccentColor,
      complexity: 3,
      popularity: 10,
      tags: [
        'terrace',
        'tag.konstruktsii',
        'tag.terrasa_veranda',
      ],
    ),
];