// GENERATED FILE - do not edit by hand.
// CalculatorDefinitionV2 entries used by the app.

import '../../../core/enums/calculator_category.dart';
import '../../../core/enums/field_input_type.dart';
import '../../../core/enums/unit_type.dart';
import '../../models/calculator_definition_v2.dart';
import '../../models/calculator_field.dart';
import '../../models/calculator_hint.dart';
import '../calculator_constants.dart';
import '../../usecases/calculate_carpet.dart';
import '../../usecases/calculate_floor_insulation.dart';
import '../../usecases/calculate_laminate.dart';
import '../../usecases/calculate_linoleum.dart';
import '../../usecases/calculate_parquet.dart';
import '../../usecases/calculate_screed.dart';
import '../../usecases/calculate_self_leveling_floor.dart';
import '../../usecases/calculate_tile.dart';
import '../../usecases/calculate_warm_floor.dart';

final List<CalculatorDefinitionV2> flooringCalculators = [
  CalculatorDefinitionV2(
      id: 'floors_carpet',
      titleKey: 'calculator.floors_carpet.title',
      descriptionKey: 'calculator.floors_carpet.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.floors',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.floorArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'rollWidth',
          labelKey: 'input.rollWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 4.0,
          required: true,
          order: 2,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Ковролин должен отлежаться в помещении 24 часа.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Для больших площадей используйте клей.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'На маленьких площадях можно использовать скотч.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Укладывайте в одном направлении ворса.'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Ковролин должен отлежаться в помещении 24 часа.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Для больших площадей используйте клей.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'На маленьких площадях можно использовать скотч.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Укладывайте в одном направлении ворса.'),
      ],
      useCase: CalculateCarpet(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'floors',
        'Внутренняя отделка',
        'Полы',
        'carpet',
        'floors_carpet',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'floors_insulation',
      titleKey: 'calculator.floors_insulation.title',
      descriptionKey: 'calculator.floors_insulation.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.floors',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.floorArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'insulationThickness',
          labelKey: 'input.insulationThickness',
          unitType: UnitType.millimeters,
          inputType: FieldInputType.number,
          defaultValue: 100.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'insulationType',
          labelKey: 'input.insulationType',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Утепление пола особенно важно для первого этажа и над неотапливаемыми помещениями.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Для минваты обязательна гидроизоляция снизу.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Пароизоляция укладывается сверху утеплителя (со стороны тёплого помещения).'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Пенопласт и ЭППС не требуют гидроизоляции, но нужна пароизоляция.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Оставляйте зазор 2-3 см между утеплителем и финишным покрытием для вентиляции.'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Утепление пола особенно важно для первого этажа и над неотапливаемыми помещениями.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Для минваты обязательна гидроизоляция снизу.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Пароизоляция укладывается сверху утеплителя (со стороны тёплого помещения).'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Пенопласт и ЭППС не требуют гидроизоляции, но нужна пароизоляция.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Оставляйте зазор 2-3 см между утеплителем и финишным покрытием для вентиляции.'),
      ],
      useCase: CalculateFloorInsulation(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'floors',
        'floors_insulation',
        'Внутренняя отделка',
        'Полы',
        'insulation',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'floors_laminate',
      titleKey: 'calculator.floors_laminate.title',
      descriptionKey: 'calculator.floors_laminate.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.floors',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 1.0,
          maxValue: 500.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'packArea',
          labelKey: 'input.packArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 2.0,
          minValue: 1.0,
          maxValue: 5.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'underlayThickness',
          labelKey: 'input.underlayThickness',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 3.0,
          minValue: 2.0,
          maxValue: 10.0,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Возьмите клинья для компенсационного зазора 10 мм.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Подложку выбирайте толщиной 2–3 мм.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Крестики не нужны, но контрольные клинья пригодятся.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Проверьте ровность основания — перепад более 3 мм нежелателен.'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Возьмите клинья для компенсационного зазора 10 мм.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Подложку выбирайте толщиной 2–3 мм.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Крестики не нужны, но контрольные клинья пригодятся.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Проверьте ровность основания — перепад более 3 мм нежелателен.'),
      ],
      useCase: CalculateLaminate(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'floors',
        'Внутренняя отделка',
        'Полы',
        'laminate',
        'floors_laminate',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'floors_linoleum',
      titleKey: 'calculator.floors_linoleum.title',
      descriptionKey: 'calculator.floors_linoleum.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.floors',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'rollWidth',
          labelKey: 'input.rollWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 3.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'rollLength',
          labelKey: 'input.rollLength',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 30.0,
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'overlap',
          labelKey: 'input.overlap',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 5.0,
          required: true,
          order: 4,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Раскатайте линолеум и дайте ему отлежаться 24 часа.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Обрежьте излишки после укладки.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте двухсторонний скотч для фиксации.'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Раскатайте линолеум и дайте ему отлежаться 24 часа.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Обрежьте излишки после укладки.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте двухсторонний скотч для фиксации.'),
      ],
      useCase: CalculateLinoleum(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'Внутренняя отделка',
        'Полы',
        'floors',
        'floors_linoleum',
        'linoleum',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'floors_parquet',
      titleKey: 'calculator.floors_parquet.title',
      descriptionKey: 'calculator.floors_parquet.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.floors',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'plankWidth',
          labelKey: 'input.plankWidth',
          unitType: UnitType.centimeters,
          inputType: FieldInputType.number,
          defaultValue: 7.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'plankLength',
          labelKey: 'input.plankLength',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 40.0,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Паркет требует акклиматизации 48 часов перед укладкой.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте подложку для звукоизоляции.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Лак наносите в 3 слоя с промежуточной шлифовкой.'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Паркет требует акклиматизации 48 часов перед укладкой.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте подложку для звукоизоляции.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Лак наносите в 3 слоя с промежуточной шлифовкой.'),
      ],
      useCase: CalculateParquet(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'floors',
        'Внутренняя отделка',
        'Полы',
        'floors_parquet',
        'parquet',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'floors_screed',
      titleKey: 'calculator.floors_screed.title',
      descriptionKey: 'calculator.floors_screed.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.floors',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 1.0,
          maxValue: 1000.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'thickness',
          labelKey: 'input.thickness',
          unitType: UnitType.millimeters,
          inputType: FieldInputType.number,
          defaultValue: 50.0,
          minValue: 20.0,
          maxValue: 200.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'cementGrade',
          labelKey: 'input.cementGrade',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 400.0,
          minValue: 300.0,
          maxValue: 600.0,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Перед заливкой проверьте уровень основания.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте маяки для контроля толщины стяжки.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Выдержите стяжку не менее 7 дней перед укладкой покрытия.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'При толщине более 50 мм используйте армирующую сетку.'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Перед заливкой проверьте уровень основания.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте маяки для контроля толщины стяжки.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Выдержите стяжку не менее 7 дней перед укладкой покрытия.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'При толщине более 50 мм используйте армирующую сетку.'),
      ],
      useCase: CalculateScreed(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'screed',
        'Внутренняя отделка',
        'Полы',
        'floors',
        'floors_screed',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'floors_self_leveling',
      titleKey: 'calculator.floors_self_leveling.title',
      descriptionKey: 'calculator.floors_self_leveling.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.floors',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'thickness',
          labelKey: 'input.thickness',
          unitType: UnitType.millimeters,
          inputType: FieldInputType.number,
          defaultValue: 5.0,
          required: true,
          order: 2,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Основание должно быть чистым и сухим.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте грунтовку для улучшения адгезии.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Раскатывайте смесь игольчатым валиком сразу после заливки.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Не ходите по полу 24 часа после заливки.'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Основание должно быть чистым и сухим.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте грунтовку для улучшения адгезии.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Раскатывайте смесь игольчатым валиком сразу после заливки.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Не ходите по полу 24 часа после заливки.'),
      ],
      useCase: CalculateSelfLevelingFloor(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'leveling',
        'floors',
        'self',
        'Внутренняя отделка',
        'Полы',
        'floors_self_leveling',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'floors_tile',
      titleKey: 'calculator.floors_tile.title',
      descriptionKey: 'calculator.floors_tile.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.floors',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 0.5,
          maxValue: 500.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'tileWidth',
          labelKey: 'input.tileWidth',
          unitType: UnitType.centimeters,
          inputType: FieldInputType.number,
          defaultValue: 30.0,
          minValue: 10.0,
          maxValue: 120.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'tileHeight',
          labelKey: 'input.tileHeight',
          unitType: UnitType.centimeters,
          inputType: FieldInputType.number,
          defaultValue: 30.0,
          minValue: 10.0,
          maxValue: 120.0,
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'jointWidth',
          labelKey: 'input.jointWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 3.0,
          minValue: 1.0,
          maxValue: 10.0,
          required: true,
          order: 4,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте крестики для равномерного шва.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Проверьте ровность основания — перепад не более 3 мм.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Затирку выбирайте по цвету плитки.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Клей наносите зубчатым шпателем.'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте крестики для равномерного шва.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Проверьте ровность основания — перепад не более 3 мм.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Затирку выбирайте по цвету плитки.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Клей наносите зубчатым шпателем.'),
      ],
      useCase: CalculateTile(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'Внутренняя отделка',
        'Полы',
        'floors',
        'tile',
        'floors_tile',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'floors_warm',
      titleKey: 'calculator.floors_warm.title',
      descriptionKey: 'calculator.floors_warm.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.floors',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 1.0,
          maxValue: 200.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'power',
          labelKey: 'input.power',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 150.0,
          minValue: 80.0,
          maxValue: 250.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'type',
          labelKey: 'input.type',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 2.0,
          minValue: 1.0,
          maxValue: 2.0,
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'thermostats',
          labelKey: 'input.thermostats',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          minValue: 1.0,
          maxValue: 10.0,
          required: true,
          order: 4,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Не укладывайте под мебелью и стационарной техникой.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте теплоизоляцию для повышения эффективности.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Подключение должен выполнять квалифицированный электрик.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Перед укладкой покрытия проверьте работоспособность системы.'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Не укладывайте под мебелью и стационарной техникой.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте теплоизоляцию для повышения эффективности.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Подключение должен выполнять квалифицированный электрик.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Перед укладкой покрытия проверьте работоспособность системы.'),
      ],
      useCase: CalculateWarmFloor(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'Внутренняя отделка',
        'Полы',
        'floors',
        'warm',
        'floors_warm',
      ],
    ),
];
