// GENERATED FILE - do not edit by hand.
// CalculatorDefinitionV2 entries used by the app.

import '../../../core/enums/calculator_category.dart';
import '../../../core/enums/field_input_type.dart';
import '../../../core/enums/unit_type.dart';
import '../../models/calculator_definition_v2.dart';
import '../../models/calculator_field.dart';
import '../../models/calculator_hint.dart';
import '../calculator_constants.dart';
import '../../usecases/calculate_carpet.dart';
import '../../usecases/calculate_floor_insulation.dart';
import '../../usecases/calculate_laminate.dart';
import '../../usecases/calculate_linoleum.dart';
import '../../usecases/calculate_parquet.dart';
import '../../usecases/calculate_screed.dart';
import '../../usecases/calculate_self_leveling_floor.dart';
import '../../usecases/calculate_tile.dart';
import '../../usecases/calculate_warm_floor.dart';

final List<CalculatorDefinitionV2> flooringCalculators = [
  CalculatorDefinitionV2(
      id: 'floors_carpet',
      titleKey: 'calculator.floors_carpet.title',
      descriptionKey: 'calculator.floors_carpet.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.floors',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.floorArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'rollWidth',
          labelKey: 'input.rollWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 4.0,
          required: true,
          order: 2,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.kovrolin_dolzhen_otlezhatsya_v'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.dlya_bolshih_ploschadey_ispolzuyte'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.na_malenkih_ploschadyah_mozhno'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ukladyvayte_v_odnom_napravlenii'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.kovrolin_dolzhen_otlezhatsya_v'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.dlya_bolshih_ploschadey_ispolzuyte'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.na_malenkih_ploschadyah_mozhno'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ukladyvayte_v_odnom_napravlenii'),
      ],
      useCase: CalculateCarpet(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'floors',
        'tag.vnutrennyaya_otdelka',
        'tag.poly',
        'carpet',
        'floors_carpet',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'floors_insulation',
      titleKey: 'calculator.floors_insulation.title',
      descriptionKey: 'calculator.floors_insulation.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.floors',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.floorArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'insulationThickness',
          labelKey: 'input.insulationThickness',
          unitType: UnitType.millimeters,
          inputType: FieldInputType.number,
          defaultValue: 100.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'insulationType',
          labelKey: 'input.insulationType',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.uteplenie_pola_osobenno_vazhno'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.dlya_minvaty_obyazatelna_gidroizolyatsiya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.paroizolyatsiya_ukladyvaetsya_sverhu_uteplitelya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.penoplast_i_epps_ne'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ostavlyayte_zazor_2_3'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.uteplenie_pola_osobenno_vazhno'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.dlya_minvaty_obyazatelna_gidroizolyatsiya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.paroizolyatsiya_ukladyvaetsya_sverhu_uteplitelya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.penoplast_i_epps_ne'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ostavlyayte_zazor_2_3'),
      ],
      useCase: CalculateFloorInsulation(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'floors',
        'floors_insulation',
        'tag.vnutrennyaya_otdelka',
        'tag.poly',
        'insulation',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'floors_laminate',
      titleKey: 'calculator.floors_laminate.title',
      descriptionKey: 'calculator.floors_laminate.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.floors',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 1.0,
          maxValue: 500.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'packArea',
          labelKey: 'input.packArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 2.0,
          minValue: 1.0,
          maxValue: 5.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'underlayThickness',
          labelKey: 'input.underlayThickness',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 3.0,
          minValue: 2.0,
          maxValue: 10.0,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.vozmite_klinya_dlya_kompensatsionnogo'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.podlozhku_vybirayte_tolschinoy_2'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.krestiki_ne_nuzhny_no'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.proverte_rovnost_osnovaniya_perepad'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.vozmite_klinya_dlya_kompensatsionnogo'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.podlozhku_vybirayte_tolschinoy_2'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.krestiki_ne_nuzhny_no'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.proverte_rovnost_osnovaniya_perepad'),
      ],
      useCase: CalculateLaminate(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'floors',
        'tag.vnutrennyaya_otdelka',
        'tag.poly',
        'laminate',
        'floors_laminate',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'floors_linoleum',
      titleKey: 'calculator.floors_linoleum.title',
      descriptionKey: 'calculator.floors_linoleum.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.floors',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'rollWidth',
          labelKey: 'input.rollWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 3.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'rollLength',
          labelKey: 'input.rollLength',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 30.0,
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'overlap',
          labelKey: 'input.overlap',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 5.0,
          required: true,
          order: 4,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.raskatayte_linoleum_i_dayte'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.obrezhte_izlishki_posle_ukladki'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ispolzuyte_dvuhstoronniy_skotch_dlya'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.raskatayte_linoleum_i_dayte'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.obrezhte_izlishki_posle_ukladki'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ispolzuyte_dvuhstoronniy_skotch_dlya'),
      ],
      useCase: CalculateLinoleum(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'tag.poly',
        'floors',
        'floors_linoleum',
        'linoleum',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'floors_parquet',
      titleKey: 'calculator.floors_parquet.title',
      descriptionKey: 'calculator.floors_parquet.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.floors',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'plankWidth',
          labelKey: 'input.plankWidth',
          unitType: UnitType.centimeters,
          inputType: FieldInputType.number,
          defaultValue: 7.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'plankLength',
          labelKey: 'input.plankLength',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 40.0,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.parket_trebuet_akklimatizatsii_48'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ispolzuyte_podlozhku_dlya_zvukoizolyatsii'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.lak_nanosite_v_3'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.parket_trebuet_akklimatizatsii_48'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ispolzuyte_podlozhku_dlya_zvukoizolyatsii'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.lak_nanosite_v_3'),
      ],
      useCase: CalculateParquet(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'floors',
        'tag.vnutrennyaya_otdelka',
        'tag.poly',
        'floors_parquet',
        'parquet',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'floors_screed',
      titleKey: 'calculator.floors_screed.title',
      descriptionKey: 'calculator.floors_screed.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.floors',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 1.0,
          maxValue: 1000.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'thickness',
          labelKey: 'input.thickness',
          unitType: UnitType.millimeters,
          inputType: FieldInputType.number,
          defaultValue: 50.0,
          minValue: 20.0,
          maxValue: 200.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'cementGrade',
          labelKey: 'input.cementGrade',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 400.0,
          minValue: 300.0,
          maxValue: 600.0,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.pered_zalivkoy_proverte_uroven'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ispolzuyte_mayaki_dlya_kontrolya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.vyderzhite_styazhku_ne_menee'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.pri_tolschine_bolee_50'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.pered_zalivkoy_proverte_uroven'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ispolzuyte_mayaki_dlya_kontrolya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.vyderzhite_styazhku_ne_menee'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.pri_tolschine_bolee_50'),
      ],
      useCase: CalculateScreed(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'screed',
        'tag.vnutrennyaya_otdelka',
        'tag.poly',
        'floors',
        'floors_screed',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'floors_self_leveling',
      titleKey: 'calculator.floors_self_leveling.title',
      descriptionKey: 'calculator.floors_self_leveling.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.floors',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'thickness',
          labelKey: 'input.thickness',
          unitType: UnitType.millimeters,
          inputType: FieldInputType.number,
          defaultValue: 5.0,
          required: true,
          order: 2,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.osnovanie_dolzhno_byt_chistym'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ispolzuyte_gruntovku_dlya_uluchsheniya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.raskatyvayte_smes_igolchatym_valikom'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ne_hodite_po_polu'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.osnovanie_dolzhno_byt_chistym'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ispolzuyte_gruntovku_dlya_uluchsheniya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.raskatyvayte_smes_igolchatym_valikom'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ne_hodite_po_polu'),
      ],
      useCase: CalculateSelfLevelingFloor(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'leveling',
        'floors',
        'self',
        'tag.vnutrennyaya_otdelka',
        'tag.poly',
        'floors_self_leveling',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'floors_tile',
      titleKey: 'calculator.floors_tile.title',
      descriptionKey: 'calculator.floors_tile.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.floors',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 0.5,
          maxValue: 500.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'tileWidth',
          labelKey: 'input.tileWidth',
          unitType: UnitType.centimeters,
          inputType: FieldInputType.number,
          defaultValue: 30.0,
          minValue: 10.0,
          maxValue: 120.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'tileHeight',
          labelKey: 'input.tileHeight',
          unitType: UnitType.centimeters,
          inputType: FieldInputType.number,
          defaultValue: 30.0,
          minValue: 10.0,
          maxValue: 120.0,
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'jointWidth',
          labelKey: 'input.jointWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 3.0,
          minValue: 1.0,
          maxValue: 10.0,
          required: true,
          order: 4,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ispolzuyte_krestiki_dlya_ravnomernogo'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.proverte_rovnost_osnovaniya_perepad_2'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.zatirku_vybirayte_po_tsvetu'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.kley_nanosite_zubchatym_shpatelem'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ispolzuyte_krestiki_dlya_ravnomernogo'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.proverte_rovnost_osnovaniya_perepad_2'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.zatirku_vybirayte_po_tsvetu'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.kley_nanosite_zubchatym_shpatelem'),
      ],
      useCase: CalculateTile(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'tag.poly',
        'floors',
        'tile',
        'floors_tile',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'floors_warm',
      titleKey: 'calculator.floors_warm.title',
      descriptionKey: 'calculator.floors_warm.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.floors',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 1.0,
          maxValue: 200.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'power',
          labelKey: 'input.power',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 150.0,
          minValue: 80.0,
          maxValue: 250.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'type',
          labelKey: 'input.type',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 2.0,
          minValue: 1.0,
          maxValue: 2.0,
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'thermostats',
          labelKey: 'input.thermostats',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          minValue: 1.0,
          maxValue: 10.0,
          required: true,
          order: 4,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ne_ukladyvayte_pod_mebelyu'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ispolzuyte_teploizolyatsiyu_dlya_povysheniya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.podklyuchenie_dolzhen_vypolnyat_kvalifitsirovannyy'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.pered_ukladkoy_pokrytiya_proverte'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ne_ukladyvayte_pod_mebelyu'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ispolzuyte_teploizolyatsiyu_dlya_povysheniya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.podklyuchenie_dolzhen_vypolnyat_kvalifitsirovannyy'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.pered_ukladkoy_pokrytiya_proverte'),
      ],
      useCase: CalculateWarmFloor(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'tag.poly',
        'floors',
        'warm',
        'floors_warm',
      ],
    ),
];