// GENERATED FILE - do not edit by hand.
// CalculatorDefinitionV2 entries used by the app.

import '../../../core/enums/calculator_category.dart';
import '../../../core/enums/field_input_type.dart';
import '../../../core/enums/unit_type.dart';
import '../../models/calculator_definition_v2.dart';
import '../../models/calculator_field.dart';
import '../../models/calculator_hint.dart';
import '../calculator_constants.dart';
import '../../usecases/calculate_laminate.dart';
import '../../usecases/calculate_linoleum.dart';
import '../../usecases/calculate_parquet.dart';
// calculate_screed.dart - не используется, калькулятор в screed_calculator_v2.dart
import '../../usecases/calculate_self_leveling_floor.dart';
// calculate_tile.dart - не используется, калькулятор в tile_calculator_v2.dart
import '../../usecases/calculate_warm_floor.dart';
import '../../usecases/calculate_carpet.dart';
import '../../usecases/calculate_floor_insulation.dart';

final List<CalculatorDefinitionV2> flooringCalculators = [
  CalculatorDefinitionV2(
      id: 'floors_laminate',
      titleKey: 'calculator.floors_laminate.title',
      descriptionKey: 'calculator.floors_laminate.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.floors',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 1.0,
          maxValue: 500.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'packArea',
          labelKey: 'input.packArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 2.0,
          minValue: 1.0,
          maxValue: 5.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'underlayThickness',
          labelKey: 'input.underlayThickness',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 3.0,
          minValue: 2.0,
          maxValue: 10.0,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.vozmite_klinya_dlya_kompensatsionnogo'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.podlozhku_vybirayte_tolschinoy_2'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.krestiki_ne_nuzhny_no'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.proverte_rovnost_osnovaniya_perepad'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.vozmite_klinya_dlya_kompensatsionnogo'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.podlozhku_vybirayte_tolschinoy_2'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.krestiki_ne_nuzhny_no'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.proverte_rovnost_osnovaniya_perepad'),
      ],
      useCase: CalculateLaminate(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'floors',
        'tag.vnutrennyaya_otdelka',
        'tag.poly',
        'laminate',
        'floors_laminate',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'floors_linoleum',
      titleKey: 'calculator.floors_linoleum.title',
      descriptionKey: 'calculator.floors_linoleum.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.floors',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'rollWidth',
          labelKey: 'input.rollWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 3.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'rollLength',
          labelKey: 'input.rollLength',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 30.0,
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'overlap',
          labelKey: 'input.overlap',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 5.0,
          required: true,
          order: 4,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.raskatayte_linoleum_i_dayte'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.obrezhte_izlishki_posle_ukladki'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ispolzuyte_dvuhstoronniy_skotch_dlya'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.raskatayte_linoleum_i_dayte'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.obrezhte_izlishki_posle_ukladki'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ispolzuyte_dvuhstoronniy_skotch_dlya'),
      ],
      useCase: CalculateLinoleum(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'tag.poly',
        'floors',
        'floors_linoleum',
        'linoleum',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'floors_parquet',
      titleKey: 'calculator.floors_parquet.title',
      descriptionKey: 'calculator.floors_parquet.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.floors',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'plankWidth',
          labelKey: 'input.plankWidth',
          unitType: UnitType.centimeters,
          inputType: FieldInputType.number,
          defaultValue: 7.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'plankLength',
          labelKey: 'input.plankLength',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 40.0,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.parket_trebuet_akklimatizatsii_48'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ispolzuyte_podlozhku_dlya_zvukoizolyatsii'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.lak_nanosite_v_3'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.parket_trebuet_akklimatizatsii_48'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ispolzuyte_podlozhku_dlya_zvukoizolyatsii'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.lak_nanosite_v_3'),
      ],
      useCase: CalculateParquet(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'floors',
        'tag.vnutrennyaya_otdelka',
        'tag.poly',
        'floors_parquet',
        'parquet',
      ],
    ),
  // Дубликат floors_screed удалён - используется screed_calculator_v2.dart
  CalculatorDefinitionV2(
      id: 'floors_self_leveling',
      titleKey: 'calculator.floors_self_leveling.title',
      descriptionKey: 'calculator.floors_self_leveling.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.floors',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'thickness',
          labelKey: 'input.thickness',
          unitType: UnitType.millimeters,
          inputType: FieldInputType.number,
          defaultValue: 5.0,
          required: true,
          order: 2,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.osnovanie_dolzhno_byt_chistym'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ispolzuyte_gruntovku_dlya_uluchsheniya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.raskatyvayte_smes_igolchatym_valikom'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ne_hodite_po_polu'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.osnovanie_dolzhno_byt_chistym'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ispolzuyte_gruntovku_dlya_uluchsheniya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.raskatyvayte_smes_igolchatym_valikom'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ne_hodite_po_polu'),
      ],
      useCase: CalculateSelfLevelingFloor(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'leveling',
        'floors',
        'self',
        'tag.vnutrennyaya_otdelka',
        'tag.poly',
        'floors_self_leveling',
      ],
    ),
  // Дубликат floors_tile удалён - используется tile_calculator_v2.dart
  CalculatorDefinitionV2(
      id: 'floors_warm',
      titleKey: 'calculator.floors_warm.title',
      descriptionKey: 'calculator.floors_warm.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.floors',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 1.0,
          maxValue: 200.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'power',
          labelKey: 'input.power',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 150.0,
          minValue: 80.0,
          maxValue: 250.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'type',
          labelKey: 'input.type',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 2.0,
          minValue: 1.0,
          maxValue: 2.0,
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'thermostats',
          labelKey: 'input.thermostats',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          minValue: 1.0,
          maxValue: 10.0,
          required: true,
          order: 4,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ne_ukladyvayte_pod_mebelyu'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ispolzuyte_teploizolyatsiyu_dlya_povysheniya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.podklyuchenie_dolzhen_vypolnyat_kvalifitsirovannyy'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.pered_ukladkoy_pokrytiya_proverte'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ne_ukladyvayte_pod_mebelyu'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ispolzuyte_teploizolyatsiyu_dlya_povysheniya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.podklyuchenie_dolzhen_vypolnyat_kvalifitsirovannyy'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.pered_ukladkoy_pokrytiya_proverte'),
      ],
      useCase: CalculateWarmFloor(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'tag.poly',
        'floors',
        'warm',
        'floors_warm',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'floors_carpet',
      titleKey: 'calculator.floors_carpet.title',
      descriptionKey: 'calculator.floors_carpet.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.floors',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 1.0,
          maxValue: 500.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'rollWidth',
          labelKey: 'input.rollWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 4.0,
          minValue: 2.0,
          maxValue: 5.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'rollLength',
          labelKey: 'input.rollLength',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 25.0,
          minValue: 10.0,
          maxValue: 50.0,
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'perimeter',
          labelKey: 'input.perimeter',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 200.0,
          required: false,
          order: 4,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.kovrolin_trebuet_akklimatizatsii'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ispolzuyte_podlozhku_dlya_komforta'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.rezite_s_zapasom_na_styky'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.zakreplyayte_plintusami_ili_gripperami'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ispolzuyte_skotch_dlya_stykov'),
      ],
      useCase: CalculateCarpet(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 8,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'tag.poly',
        'floors',
        'carpet',
        'floors_carpet',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'floors_insulation',
      titleKey: 'calculator.floors_insulation.title',
      descriptionKey: 'calculator.floors_insulation.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.floors',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 1.0,
          maxValue: 500.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'insulationThickness',
          labelKey: 'input.insulationThickness',
          unitType: UnitType.millimeters,
          inputType: FieldInputType.number,
          defaultValue: 100.0,
          minValue: 20.0,
          maxValue: 200.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'insulationType',
          labelKey: 'input.insulationType',
          unitType: UnitType.pieces,
          inputType: FieldInputType.select,
          defaultValue: 1.0,
          required: true,
          order: 3,
          options: [
            FieldOption(value: 1.0, labelKey: 'input.insulationType.mineral_wool'),
            FieldOption(value: 2.0, labelKey: 'input.insulationType.foam'),
            FieldOption(value: 3.0, labelKey: 'input.insulationType.xps'),
          ],
        ),
        const CalculatorField(
          key: 'perimeter',
          labelKey: 'input.perimeter',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 200.0,
          required: false,
          order: 4,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.uteplenie_pola_snizhaet_teplopoteri'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ispolzuyte_paroizolyatsiyu'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.tolschina_zavisit_ot_klimata'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.ne_ostavlyayte_schelei_mezhdu_plitami'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.flooring.zakroyte_styazhkoy_ili_nastilom'),
      ],
      useCase: CalculateFloorInsulation(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 8,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'tag.poly',
        'floors',
        'insulation',
        'floors_insulation',
      ],
    ),
];