// GENERATED FILE - do not edit by hand.
// CalculatorDefinitionV2 entries used by the app.

import '../../../core/enums/calculator_category.dart';
import '../../../core/enums/field_input_type.dart';
import '../../../core/enums/unit_type.dart';
import '../../models/calculator_definition_v2.dart';
import '../../models/calculator_field.dart';
import '../../models/calculator_hint.dart';
import '../calculator_constants.dart';
import '../../usecases/calculate_basement.dart';
import '../../usecases/calculate_blind_area.dart';
import '../../usecases/calculate_slab.dart';

final List<CalculatorDefinitionV2> foundationCalculators = [
  CalculatorDefinitionV2(
      id: 'foundation_basement',
      titleKey: 'calculator.foundation_basement.title',
      descriptionKey: 'calculator.foundation_basement.description',
      category: CalculatorCategory.exterior,
      subCategoryKey: 'subcategory.basement',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 50.0,
          minValue: 10.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'height',
          labelKey: 'input.height',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 2.5,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'wallThickness',
          labelKey: 'input.wallThickness',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.4,
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'floorThickness',
          labelKey: 'input.floorThickness',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.15,
          required: true,
          order: 4,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Гидроизоляция по всей площади контакта с грунтом.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Утепление наружное (ЭППС) минимум 100 мм.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Армирование стен вертикальными и горизонтальными сетками.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Вентиляция обязательна для предотвращения сырости.'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Гидроизоляция по всей площади контакта с грунтом.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Утепление наружное (ЭППС) минимум 100 мм.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Армирование стен вертикальными и горизонтальными сетками.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Вентиляция обязательна для предотвращения сырости.'),
      ],
      useCase: CalculateBasement(),
      accentColor: kCalculatorAccentColor,
      complexity: 3,
      popularity: 10,
      tags: [
        'Фундамент',
        'foundation',
        'Цокольный этаж',
        'basement',
        'foundation_basement',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'foundation_blind_area',
      titleKey: 'calculator.foundation_blind_area.title',
      descriptionKey: 'calculator.foundation_blind_area.description',
      category: CalculatorCategory.exterior,
      subCategoryKey: 'subcategory.blind_area',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 100.0,
          minValue: 10.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'width',
          labelKey: 'input.width',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'thickness',
          labelKey: 'input.thickness',
          unitType: UnitType.millimeters,
          inputType: FieldInputType.number,
          defaultValue: 100.0,
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'materialType',
          labelKey: 'input.materialType',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          minValue: 1.0,
          maxValue: 3.0,
          required: false,
          order: 4,
        ),
        const CalculatorField(
          key: 'insulation',
          labelKey: 'input.insulation',
          unitType: UnitType.meters,
          inputType: FieldInputType.switch_,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 1.0,
          required: false,
          order: 5,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Минимальная ширина 60 см, рекомендуемая 1 м.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Уклон от дома 1-2 см на метр.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Песчано-гравийная подушка 15-20 см.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Компенсационный шов между отмосткой и цоколем.'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Минимальная ширина 60 см, рекомендуемая 1 м.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Уклон от дома 1-2 см на метр.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Песчано-гравийная подушка 15-20 см.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Компенсационный шов между отмосткой и цоколем.'),
      ],
      useCase: CalculateBlindArea(),
      accentColor: kCalculatorAccentColor,
      complexity: 3,
      popularity: 10,
      tags: [
        'blind',
        'area',
        'foundation_blind_area',
        'Фундамент',
        'foundation',
        'Отмостка',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'foundation_slab',
      titleKey: 'calculator.foundation_slab.title',
      descriptionKey: 'calculator.foundation_slab.description',
      category: CalculatorCategory.exterior,
      subCategoryKey: 'subcategory.slab',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'thickness',
          labelKey: 'input.thickness',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.2,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'insulation',
          labelKey: 'input.insulationThickness',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Плита толщиной минимум 200 мм для жилого дома.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Обязательна песчано-гравийная подготовка.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Гидроизоляция снизу и по периметру.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Армирование двумя сетками в верхней и нижней зонах.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Утеплитель (ЭППС) под плитой для теплого пола.'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Плита толщиной минимум 200 мм для жилого дома.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Обязательна песчано-гравийная подготовка.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Гидроизоляция снизу и по периметру.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Армирование двумя сетками в верхней и нижней зонах.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Утеплитель (ЭППС) под плитой для теплого пола.'),
      ],
      useCase: CalculateSlab(),
      accentColor: kCalculatorAccentColor,
      complexity: 3,
      popularity: 10,
      tags: [
        'foundation_slab',
        'Фундамент',
        'foundation',
        'Монолитная плита',
        'slab',
      ],
    ),
];
