// GENERATED FILE - do not edit by hand.
// CalculatorDefinitionV2 entries used by the app.

import '../../../core/enums/calculator_category.dart';
import '../../../core/enums/field_input_type.dart';
import '../../../core/enums/unit_type.dart';
import '../../models/calculator_definition_v2.dart';
import '../../models/calculator_field.dart';
import '../../models/calculator_hint.dart';
import '../calculator_constants.dart';
import '../../usecases/canonical_bridge.dart';
import '../../usecases/attic_canonical_adapter.dart';
import '../../usecases/balcony_canonical_adapter.dart';
import '../../usecases/doors_canonical_adapter.dart';
import '../../usecases/slopes_canonical_adapter.dart';
import '../../usecases/sound_insulation_canonical_adapter.dart';
import '../../usecases/waterproofing_canonical_adapter.dart';
import '../../usecases/windows_canonical_adapter.dart';

final List<CalculatorDefinitionV2> interiorCalculators = [
  const CalculatorDefinitionV2(
      id: 'attic',
      titleKey: 'calculator.attic.title',
      descriptionKey: 'calculator.attic.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.attic',
      fields: [
        CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.slider,
          defaultValue: 30.0,
          minValue: 10.0,
          maxValue: 200.0,
          step: 1.0,
          iconName: 'square_foot',
          group: 'dimensions',
          required: true,
          order: 1,
        ),
        CalculatorField(
          key: 'roofArea',
          labelKey: 'input.roofArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.slider,
          defaultValue: 40.0,
          minValue: 10.0,
          maxValue: 300.0,
          step: 1.0,
          iconName: 'roofing',
          group: 'dimensions',
          required: true,
          order: 2,
        ),
        CalculatorField(
          key: 'wallArea',
          labelKey: 'input.wallArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.slider,
          defaultValue: 20.0,
          minValue: 0.0,
          maxValue: 200.0,
          step: 1.0,
          iconName: 'square_foot',
          group: 'dimensions',
          required: true,
          order: 3,
        ),
        CalculatorField(
          key: 'floorArea',
          labelKey: 'input.floorArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.slider,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 200.0,
          step: 1.0,
          iconName: 'square_foot',
          group: 'dimensions',
          required: false,
          order: 4,
        ),
        CalculatorField(
          key: 'windows',
          labelKey: 'input.windows',
          unitType: UnitType.pieces,
          inputType: FieldInputType.slider,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 10.0,
          step: 1.0,
          iconName: 'window',
          group: 'openings',
          required: false,
          order: 5,
        ),
        CalculatorField(
          key: 'insulation',
          labelKey: 'input.insulation',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 1.0,
          minValue: 0.0,
          maxValue: 3.0,
          step: 1.0,
          iconName: 'layers',
          group: 'material',
          required: false,
          order: 6,
        ),
        CalculatorField(
          key: 'wallFinish',
          labelKey: 'input.wallFinish',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          minValue: 0.0,
          maxValue: 3.0,
          iconName: 'format_paint',
          group: 'options',
          required: true,
          order: 7,
        ),
        CalculatorField(
          key: 'floorType',
          labelKey: 'input.floorType',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          minValue: 1.0,
          maxValue: 3.0,
          iconName: 'category',
          group: 'options',
          required: true,
          order: 8,
        ),
      ],
      beforeHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.uteplenie_mansardy_obyazatelno_dlya'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.tolschina_uteplitelya_dolzhna_byt'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.paroizolyatsiya_zaschischaet_uteplitel_ot'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.mansardnye_okna_obespechivayut_estestvennoe'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.vagonka_sozdaet_uyutnuyu_atmosferu'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.proverte_nesuschuyu_sposobnost_perekrytiya'),
      ],
      afterHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.uteplenie_mansardy_obyazatelno_dlya'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.tolschina_uteplitelya_dolzhna_byt'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.paroizolyatsiya_zaschischaet_uteplitel_ot'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.mansardnye_okna_obespechivayut_estestvennoe'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.vagonka_sozdaet_uyutnuyu_atmosferu'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.proverte_nesuschuyu_sposobnost_perekrytiya'),
      ],
      useCase: CanonicalBridgeUseCase(calculateCanonicalAttic),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'attic',
        'tag.vnutrennyaya_otdelka',
        'tag.mansarda',
      ],
    ),
  const CalculatorDefinitionV2(
      id: 'balcony',
      titleKey: 'calculator.balcony.title',
      descriptionKey: 'calculator.balcony.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.balcony',
      fields: [
        CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.slider,
          defaultValue: 6.0,
          minValue: 1.0,
          maxValue: 20.0,
          step: 1.0,
          iconName: 'square_foot',
          group: 'dimensions',
          required: true,
          order: 1,
        ),
        CalculatorField(
          key: 'height',
          labelKey: 'input.height',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 1.1,
          minValue: 0.5,
          maxValue: 3.0,
          step: 1.0,
          iconName: 'height',
          group: 'dimensions',
          required: true,
          order: 2,
        ),
        CalculatorField(
          key: 'glazing',
          labelKey: 'input.glazing',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 3.0,
          step: 1.0,
          iconName: 'window',
          group: 'options',
          required: false,
          order: 3,
        ),
        CalculatorField(
          key: 'insulation',
          labelKey: 'input.insulation',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 3.0,
          step: 1.0,
          iconName: 'layers',
          group: 'options',
          required: false,
          order: 4,
        ),
        CalculatorField(
          key: 'floorType',
          labelKey: 'input.floorType',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          minValue: 1.0,
          maxValue: 3.0,
          iconName: 'category',
          group: 'material',
          required: true,
          order: 5,
        ),
        CalculatorField(
          key: 'wallFinish',
          labelKey: 'input.wallFinish',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 1.0,
          minValue: 0.0,
          maxValue: 3.0,
          step: 1.0,
          iconName: 'format_paint',
          group: 'options',
          required: true,
          order: 6,
        ),
      ],
      beforeHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.osteklenie_balkona_znachitelno_uvelichivaet'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.teploe_osteklenie_pozvolyaet_ispolzovat'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.uteplenie_obyazatelno_dlya_teplogo'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.paroizolyatsiya_zaschischaet_uteplitel_ot_2'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.dlya_pola_na_otkrytom'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.terrasnaya_doska_podhodit_dlya'),
      ],
      afterHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.osteklenie_balkona_znachitelno_uvelichivaet'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.teploe_osteklenie_pozvolyaet_ispolzovat'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.uteplenie_obyazatelno_dlya_teplogo'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.paroizolyatsiya_zaschischaet_uteplitel_ot_2'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.dlya_pola_na_otkrytom'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.terrasnaya_doska_podhodit_dlya'),
      ],
      useCase: CanonicalBridgeUseCase(calculateCanonicalBalcony),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'balcony',
        'tag.balkon_lodzhiya',
      ],
    ),
  const CalculatorDefinitionV2(
      id: 'bathroom_waterproof',
      titleKey: 'calculator.bathroom_waterproof.title',
      descriptionKey: 'calculator.bathroom_waterproof.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.bathroom',
      fields: [
        CalculatorField(
          key: 'floorArea',
          labelKey: 'input.floorArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.slider,
          defaultValue: 5.0,
          minValue: 1.0,
          maxValue: 30.0,
          step: 1.0,
          iconName: 'square_foot',
          group: 'dimensions',
          required: true,
          order: 1,
        ),
        CalculatorField(
          key: 'wallHeight',
          labelKey: 'input.wallHeight',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 1.2,
          minValue: 0.2,
          maxValue: 3.0,
          step: 0.1,
          iconName: 'height',
          group: 'dimensions',
          hintKey: 'input.waterproof_wallHeight.hint',
          required: true,
          order: 2,
        ),
      ],
      beforeHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.gidroizolyatsiya_obyazatelna_dlya_pola_2'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ispolzuyte_armiruyuschuyu_lentu_dlya'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.nanosite_material_v_dva'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.proverte_tselostnost_pokrytiya_pered'),
      ],
      afterHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.gidroizolyatsiya_obyazatelna_dlya_pola_2'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ispolzuyte_armiruyuschuyu_lentu_dlya'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.nanosite_material_v_dva'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.proverte_tselostnost_pokrytiya_pered'),
      ],
      useCase: CanonicalBridgeUseCase(calculateCanonicalWaterproofing),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'waterproof',
        'bathroom',
        'tag.vnutrennyaya_otdelka',
        'bathroom_waterproof',
        'tag.vannaya_tualet',
      ],
    ),
  const CalculatorDefinitionV2(
      id: 'doors_install',
      titleKey: 'calculator.doors_install.title',
      descriptionKey: 'calculator.doors_install.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.windows_doors',
      fields: [
        CalculatorField(
          key: 'doors',
          labelKey: 'input.doors',
          unitType: UnitType.pieces,
          inputType: FieldInputType.slider,
          defaultValue: 1.0,
          minValue: 1.0,
          maxValue: 20.0,
          step: 1.0,
          iconName: 'door_front',
          group: 'dimensions',
          required: true,
          order: 1,
        ),
        CalculatorField(
          key: 'doorWidth',
          labelKey: 'input.doorWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 0.9,
          minValue: 0.6,
          maxValue: 1.5,
          step: 1.0,
          iconName: 'width_normal',
          group: 'dimensions',
          required: true,
          order: 2,
        ),
        CalculatorField(
          key: 'doorHeight',
          labelKey: 'input.doorHeight',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 2.1,
          minValue: 1.8,
          maxValue: 2.5,
          step: 1.0,
          iconName: 'height',
          group: 'dimensions',
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.proverte_vertikalnost_dvernoy_korobki'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ispolzuyte_montazhnuyu_penu_dlya'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ustanovite_nalichniki_dlya_zaversheniya'),
      ],
      afterHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.proverte_vertikalnost_dvernoy_korobki'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ispolzuyte_montazhnuyu_penu_dlya'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ustanovite_nalichniki_dlya_zaversheniya'),
      ],
      useCase: CanonicalBridgeUseCase(calculateCanonicalDoors),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'install',
        'tag.vnutrennyaya_otdelka',
        'doors_install',
        'doors',
        'tag.okna_dveri',
      ],
    ),
  const CalculatorDefinitionV2(
      id: 'insulation_sound',
      titleKey: 'calculator.insulation_sound.title',
      descriptionKey: 'calculator.insulation_sound.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.soundproofing',
      fields: [
        CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.slider,
          defaultValue: 20.0,
          minValue: 1.0,
          maxValue: 500.0,
          step: 1.0,
          iconName: 'square_foot',
          group: 'dimensions',
          required: true,
          order: 1,
        ),
        CalculatorField(
          key: 'thickness',
          labelKey: 'input.thickness',
          unitType: UnitType.millimeters,
          inputType: FieldInputType.slider,
          defaultValue: 50.0,
          minValue: 20.0,
          maxValue: 200.0,
          step: 10.0,
          iconName: 'height',
          group: 'material',
          required: true,
          order: 2,
        ),
        CalculatorField(
          key: 'insulationType',
          labelKey: 'input.insulationType',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          minValue: 1.0,
          maxValue: 3.0,
          iconName: 'category',
          group: 'material',
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.shumoizolyatsiya_osobenno_vazhna_dlya'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ispolzuyte_materialy_s_vysokim'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.obespechte_germetichnost_stykov'),
      ],
      afterHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.shumoizolyatsiya_osobenno_vazhna_dlya'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ispolzuyte_materialy_s_vysokim'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.obespechte_germetichnost_stykov'),
      ],
      useCase: CanonicalBridgeUseCase(calculateCanonicalSoundInsulation),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'sound',
        'insulation',
        'tag.shumoizolyatsiya',
        'insulation_sound',
      ],
    ),
  const CalculatorDefinitionV2(
      id: 'slopes_finishing',
      titleKey: 'calculator.slopes_finishing.title',
      descriptionKey: 'calculator.slopes_finishing.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.windows_doors',
      fields: [
        CalculatorField(
          key: 'windows',
          labelKey: 'input.windows',
          unitType: UnitType.pieces,
          inputType: FieldInputType.slider,
          defaultValue: 1.0,
          minValue: 1.0,
          maxValue: 20.0,
          step: 1.0,
          iconName: 'window',
          group: 'dimensions',
          required: true,
          order: 1,
        ),
        CalculatorField(
          key: 'windowWidth',
          labelKey: 'input.windowWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 1.5,
          minValue: 0.5,
          maxValue: 3.0,
          step: 1.0,
          iconName: 'width_normal',
          group: 'dimensions',
          required: true,
          order: 2,
        ),
        CalculatorField(
          key: 'windowHeight',
          labelKey: 'input.windowHeight',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 1.4,
          minValue: 0.5,
          maxValue: 3.0,
          step: 1.0,
          iconName: 'height',
          group: 'dimensions',
          required: true,
          order: 3,
        ),
        CalculatorField(
          key: 'slopeWidth',
          labelKey: 'input.slopeWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 0.3,
          minValue: 0.1,
          maxValue: 0.5,
          step: 0.05,
          iconName: 'straighten',
          group: 'dimensions',
          required: true,
          order: 4,
        ),
      ],
      beforeHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ispolzuyte_ugolki_dlya_rovnyh'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.shpaklevku_nanosite_tonkim_sloem'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.kraste_v_2_sloya'),
      ],
      afterHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ispolzuyte_ugolki_dlya_rovnyh'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.shpaklevku_nanosite_tonkim_sloem'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.kraste_v_2_sloya'),
      ],
      useCase: CanonicalBridgeUseCase(calculateCanonicalSlopes),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'slopes',
        'slopes_finishing',
        'tag.okna_dveri',
        'finishing',
      ],
    ),
  const CalculatorDefinitionV2(
      id: 'windows_install',
      titleKey: 'calculator.windows_install.title',
      descriptionKey: 'calculator.windows_install.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.windows_doors',
      fields: [
        CalculatorField(
          key: 'windows',
          labelKey: 'input.windows',
          unitType: UnitType.pieces,
          inputType: FieldInputType.slider,
          defaultValue: 1.0,
          minValue: 1.0,
          maxValue: 20.0,
          step: 1.0,
          iconName: 'window',
          group: 'dimensions',
          required: true,
          order: 1,
        ),
        CalculatorField(
          key: 'windowWidth',
          labelKey: 'input.windowWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 1.5,
          minValue: 0.5,
          maxValue: 3.0,
          step: 1.0,
          iconName: 'width_normal',
          group: 'dimensions',
          required: true,
          order: 2,
        ),
        CalculatorField(
          key: 'windowHeight',
          labelKey: 'input.windowHeight',
          unitType: UnitType.meters,
          inputType: FieldInputType.slider,
          defaultValue: 1.4,
          minValue: 0.5,
          maxValue: 3.0,
          step: 1.0,
          iconName: 'height',
          group: 'dimensions',
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ispolzuyte_montazhnuyu_penu_dlya_2'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ustanovite_otlivy_dlya_zaschity'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.proverte_vertikalnost_i_gorizontalnost'),
      ],
      afterHints: [
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ispolzuyte_montazhnuyu_penu_dlya_2'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ustanovite_otlivy_dlya_zaschity'),
        CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.proverte_vertikalnost_i_gorizontalnost'),
      ],
      useCase: CanonicalBridgeUseCase(calculateCanonicalWindows),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'install',
        'tag.vnutrennyaya_otdelka',
        'windows_install',
        'tag.okna_dveri',
        'windows',
      ],
    ),
];