// GENERATED FILE - do not edit by hand.
// CalculatorDefinitionV2 entries used by the app.

import '../../../core/enums/calculator_category.dart';
import '../../../core/enums/field_input_type.dart';
import '../../../core/enums/unit_type.dart';
import '../../models/calculator_definition_v2.dart';
import '../../models/calculator_field.dart';
import '../../models/calculator_hint.dart';
import '../calculator_constants.dart';
import '../../usecases/calculate_attic.dart';
import '../../usecases/calculate_balcony.dart';
import '../../usecases/calculate_door_installation.dart';
import '../../usecases/calculate_slopes.dart';
import '../../usecases/calculate_sound_insulation.dart';
import '../../usecases/calculate_waterproofing.dart';
import '../../usecases/calculate_window_installation.dart';

final List<CalculatorDefinitionV2> interiorCalculators = [
  CalculatorDefinitionV2(
      id: 'attic',
      titleKey: 'calculator.attic.title',
      descriptionKey: 'calculator.attic.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.attic',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'roofArea',
          labelKey: 'input.roofArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'wallArea',
          labelKey: 'input.wallArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'floorArea',
          labelKey: 'input.floorArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: false,
          order: 4,
        ),
        const CalculatorField(
          key: 'windows',
          labelKey: 'input.windows',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: false,
          order: 5,
        ),
        const CalculatorField(
          key: 'insulation',
          labelKey: 'input.insulation',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: false,
          order: 6,
        ),
        const CalculatorField(
          key: 'wallFinish',
          labelKey: 'input.wallFinish',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: true,
          order: 7,
        ),
        const CalculatorField(
          key: 'floorType',
          labelKey: 'input.floorType',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: true,
          order: 8,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.uteplenie_mansardy_obyazatelno_dlya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.tolschina_uteplitelya_dolzhna_byt'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.paroizolyatsiya_zaschischaet_uteplitel_ot'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.mansardnye_okna_obespechivayut_estestvennoe'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.vagonka_sozdaet_uyutnuyu_atmosferu'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.proverte_nesuschuyu_sposobnost_perekrytiya'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.uteplenie_mansardy_obyazatelno_dlya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.tolschina_uteplitelya_dolzhna_byt'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.paroizolyatsiya_zaschischaet_uteplitel_ot'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.mansardnye_okna_obespechivayut_estestvennoe'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.vagonka_sozdaet_uyutnuyu_atmosferu'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.proverte_nesuschuyu_sposobnost_perekrytiya'),
      ],
      useCase: CalculateAttic(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'attic',
        'tag.vnutrennyaya_otdelka',
        'tag.mansarda',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'balcony',
      titleKey: 'calculator.balcony.title',
      descriptionKey: 'calculator.balcony.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.balcony',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'height',
          labelKey: 'input.height',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 1.1,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'glazing',
          labelKey: 'input.glazing',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: false,
          order: 3,
        ),
        const CalculatorField(
          key: 'insulation',
          labelKey: 'input.insulation',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: false,
          order: 4,
        ),
        const CalculatorField(
          key: 'floorType',
          labelKey: 'input.floorType',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: true,
          order: 5,
        ),
        const CalculatorField(
          key: 'wallFinish',
          labelKey: 'input.wallFinish',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: true,
          order: 6,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.osteklenie_balkona_znachitelno_uvelichivaet'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.teploe_osteklenie_pozvolyaet_ispolzovat'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.uteplenie_obyazatelno_dlya_teplogo'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.paroizolyatsiya_zaschischaet_uteplitel_ot_2'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.dlya_pola_na_otkrytom'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.terrasnaya_doska_podhodit_dlya'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.osteklenie_balkona_znachitelno_uvelichivaet'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.teploe_osteklenie_pozvolyaet_ispolzovat'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.uteplenie_obyazatelno_dlya_teplogo'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.paroizolyatsiya_zaschischaet_uteplitel_ot_2'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.dlya_pola_na_otkrytom'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.terrasnaya_doska_podhodit_dlya'),
      ],
      useCase: CalculateBalcony(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'balcony',
        'tag.balkon_lodzhiya',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'bathroom_waterproof',
      titleKey: 'calculator.bathroom_waterproof.title',
      descriptionKey: 'calculator.bathroom_waterproof.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.bathroom',
      fields: [
        const CalculatorField(
          key: 'floorArea',
          labelKey: 'input.floorArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'wallHeight',
          labelKey: 'input.wallHeight',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.3,
          required: true,
          order: 2,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.gidroizolyatsiya_obyazatelna_dlya_pola_2'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ispolzuyte_armiruyuschuyu_lentu_dlya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.nanosite_material_v_dva'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.proverte_tselostnost_pokrytiya_pered'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.gidroizolyatsiya_obyazatelna_dlya_pola_2'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ispolzuyte_armiruyuschuyu_lentu_dlya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.nanosite_material_v_dva'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.proverte_tselostnost_pokrytiya_pered'),
      ],
      useCase: CalculateWaterproofing(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'waterproof',
        'bathroom',
        'tag.vnutrennyaya_otdelka',
        'bathroom_waterproof',
        'tag.vannaya_tualet',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'doors_install',
      titleKey: 'calculator.doors_install.title',
      descriptionKey: 'calculator.doors_install.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.windows_doors',
      fields: [
        const CalculatorField(
          key: 'doors',
          labelKey: 'input.doors',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'doorWidth',
          labelKey: 'input.doorWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.9,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'doorHeight',
          labelKey: 'input.doorHeight',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 2.1,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.proverte_vertikalnost_dvernoy_korobki'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ispolzuyte_montazhnuyu_penu_dlya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ustanovite_nalichniki_dlya_zaversheniya'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.proverte_vertikalnost_dvernoy_korobki'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ispolzuyte_montazhnuyu_penu_dlya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ustanovite_nalichniki_dlya_zaversheniya'),
      ],
      useCase: CalculateDoorInstallation(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'install',
        'tag.vnutrennyaya_otdelka',
        'doors_install',
        'doors',
        'tag.okna_dveri',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'insulation_sound',
      titleKey: 'calculator.insulation_sound.title',
      descriptionKey: 'calculator.insulation_sound.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.soundproofing',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'thickness',
          labelKey: 'input.thickness',
          unitType: UnitType.millimeters,
          inputType: FieldInputType.number,
          defaultValue: 50.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'insulationType',
          labelKey: 'input.insulationType',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.shumoizolyatsiya_osobenno_vazhna_dlya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ispolzuyte_materialy_s_vysokim'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.obespechte_germetichnost_stykov'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.shumoizolyatsiya_osobenno_vazhna_dlya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ispolzuyte_materialy_s_vysokim'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.obespechte_germetichnost_stykov'),
      ],
      useCase: CalculateSoundInsulation(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'sound',
        'insulation',
        'tag.shumoizolyatsiya',
        'insulation_sound',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'slopes_finishing',
      titleKey: 'calculator.slopes_finishing.title',
      descriptionKey: 'calculator.slopes_finishing.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.windows_doors',
      fields: [
        const CalculatorField(
          key: 'windows',
          labelKey: 'input.windows',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'windowWidth',
          labelKey: 'input.windowWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 1.5,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'windowHeight',
          labelKey: 'input.windowHeight',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 1.4,
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'slopeWidth',
          labelKey: 'input.slopeWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.3,
          required: true,
          order: 4,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ispolzuyte_ugolki_dlya_rovnyh'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.shpaklevku_nanosite_tonkim_sloem'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.kraste_v_2_sloya'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ispolzuyte_ugolki_dlya_rovnyh'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.shpaklevku_nanosite_tonkim_sloem'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.kraste_v_2_sloya'),
      ],
      useCase: CalculateSlopes(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'slopes',
        'slopes_finishing',
        'tag.okna_dveri',
        'finishing',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'windows_install',
      titleKey: 'calculator.windows_install.title',
      descriptionKey: 'calculator.windows_install.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.windows_doors',
      fields: [
        const CalculatorField(
          key: 'windows',
          labelKey: 'input.windows',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'windowWidth',
          labelKey: 'input.windowWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 1.5,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'windowHeight',
          labelKey: 'input.windowHeight',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 1.4,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ispolzuyte_montazhnuyu_penu_dlya_2'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ustanovite_otlivy_dlya_zaschity'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.proverte_vertikalnost_i_gorizontalnost'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ispolzuyte_montazhnuyu_penu_dlya_2'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.ustanovite_otlivy_dlya_zaschity'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.interior.proverte_vertikalnost_i_gorizontalnost'),
      ],
      useCase: CalculateWindowInstallation(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'install',
        'tag.vnutrennyaya_otdelka',
        'windows_install',
        'tag.okna_dveri',
        'windows',
      ],
    ),
];