// Калькуляторы участка и наружных инженерных систем (canonical V2).

import '../../../core/enums/calculator_category.dart';
import '../../../core/enums/field_input_type.dart';
import '../../../core/enums/unit_type.dart';
import '../../models/calculator_definition_v2.dart';
import '../../models/calculator_field.dart';
import '../calculator_constants.dart';
import '../../usecases/canonical_bridge.dart';
import '../../usecases/drainage_canonical_adapter.dart';
import '../../usecases/greenhouse_canonical_adapter.dart';
import '../../usecases/lawn_canonical_adapter.dart';
import '../../usecases/paving_tiles_canonical_adapter.dart';
import '../../usecases/septic_rings_canonical_adapter.dart';

final List<CalculatorDefinitionV2> landscapeCalculators = [
  CalculatorDefinitionV2(
    id: 'lawn',
    titleKey: calculatorTitleKey('lawn'),
    descriptionKey: calculatorDescriptionKey('lawn'),
    category: CalculatorCategory.exterior,
    subCategoryKey: 'subcategory.landscape',
    fields: [
      const CalculatorField(
        key: 'area',
        labelKey: 'input.area',
        unitType: UnitType.squareMeters,
        inputType: FieldInputType.slider,
        defaultValue: 50,
        minValue: 5,
        maxValue: 2000,
        step: 5,
        required: true,
        order: 1,
      ),
      const CalculatorField(
        key: 'lawnType',
        labelKey: 'input.lawnType',
        unitType: UnitType.pieces,
        inputType: FieldInputType.radio,
        defaultValue: 0,
        options: [
          FieldOption(value: 0, labelKey: 'input.lawnType.seed'),
          FieldOption(value: 1, labelKey: 'input.lawnType.rolls'),
        ],
        required: true,
        order: 2,
      ),
      const CalculatorField(
        key: 'soilThickness',
        labelKey: 'input.soilThickness',
        unitType: UnitType.millimeters,
        inputType: FieldInputType.slider,
        defaultValue: 12,
        minValue: 8,
        maxValue: 25,
        step: 1,
        required: true,
        order: 3,
      ),
    ],
    useCase: const CanonicalBridgeUseCase(calculateCanonicalLawn),
    iconName: 'grass',
    accentColor: kCalculatorAccentColor,
    complexity: 2,
    popularity: 45,
    tags: ['газон', 'участок', 'ландшафт'],
  ),
  CalculatorDefinitionV2(
    id: 'drainage',
    titleKey: calculatorTitleKey('drainage'),
    descriptionKey: calculatorDescriptionKey('drainage'),
    category: CalculatorCategory.exterior,
    subCategoryKey: 'subcategory.landscape',
    fields: [
      const CalculatorField(
        key: 'length',
        labelKey: 'input.drainageLength',
        unitType: UnitType.meters,
        inputType: FieldInputType.number,
        defaultValue: 40,
        minValue: 5,
        maxValue: 500,
        step: 1,
        required: true,
        order: 1,
      ),
      const CalculatorField(
        key: 'pipeDiameter',
        labelKey: 'input.pipeDiameter',
        unitType: UnitType.millimeters,
        inputType: FieldInputType.select,
        defaultValue: 110,
        options: [
          FieldOption(value: 110, labelKey: 'input.pipeDiameter.110'),
          FieldOption(value: 160, labelKey: 'input.pipeDiameter.160'),
        ],
        required: true,
        order: 2,
      ),
    ],
    useCase: const CanonicalBridgeUseCase(calculateCanonicalDrainage),
    iconName: 'water_drop',
    accentColor: kCalculatorAccentColor,
    complexity: 3,
    popularity: 40,
    tags: ['дренаж', 'участок', 'вода'],
  ),
  CalculatorDefinitionV2(
    id: 'greenhouse',
    titleKey: calculatorTitleKey('greenhouse'),
    descriptionKey: calculatorDescriptionKey('greenhouse'),
    category: CalculatorCategory.exterior,
    subCategoryKey: 'subcategory.landscape',
    fields: [
      const CalculatorField(
        key: 'length',
        labelKey: 'input.length',
        unitType: UnitType.meters,
        defaultValue: 6,
        minValue: 2,
        maxValue: 20,
        step: 0.1,
        required: true,
        order: 1,
      ),
      const CalculatorField(
        key: 'width',
        labelKey: 'input.width',
        unitType: UnitType.meters,
        defaultValue: 3,
        minValue: 2,
        maxValue: 10,
        step: 0.1,
        required: true,
        order: 2,
      ),
      const CalculatorField(
        key: 'height',
        labelKey: 'input.height',
        unitType: UnitType.meters,
        defaultValue: 2.1,
        minValue: 1.8,
        maxValue: 3.5,
        step: 0.1,
        required: true,
        order: 3,
      ),
    ],
    useCase: const CanonicalBridgeUseCase(calculateCanonicalGreenhouse),
    iconName: 'deck',
    accentColor: kCalculatorAccentColor,
    complexity: 3,
    popularity: 35,
    tags: ['теплица', 'поликарбонат', 'участок'],
  ),
  CalculatorDefinitionV2(
    id: 'paving_tiles',
    titleKey: calculatorTitleKey('paving_tiles'),
    descriptionKey: calculatorDescriptionKey('paving_tiles'),
    category: CalculatorCategory.exterior,
    subCategoryKey: 'subcategory.landscape',
    fields: [
      const CalculatorField(
        key: 'area',
        labelKey: 'input.area',
        unitType: UnitType.squareMeters,
        inputType: FieldInputType.slider,
        defaultValue: 50,
        minValue: 5,
        maxValue: 500,
        step: 1,
        required: true,
        order: 1,
      ),
      const CalculatorField(
        key: 'perimeter',
        labelKey: 'input.perimeter',
        unitType: UnitType.meters,
        inputType: FieldInputType.number,
        defaultValue: 30,
        minValue: 0,
        maxValue: 300,
        step: 1,
        required: true,
        order: 2,
      ),
    ],
    useCase: const CanonicalBridgeUseCase(calculateCanonicalPavingTiles),
    iconName: 'grid_view',
    accentColor: kCalculatorAccentColor,
    complexity: 2,
    popularity: 50,
    tags: ['тротуарная плитка', 'брусчатка', 'двор'],
  ),
  CalculatorDefinitionV2(
    id: 'septic_rings',
    titleKey: calculatorTitleKey('septic_rings'),
    descriptionKey: calculatorDescriptionKey('septic_rings'),
    category: CalculatorCategory.exterior,
    subCategoryKey: 'subcategory.sewage',
    fields: [
      const CalculatorField(
        key: 'residents',
        labelKey: 'input.residents',
        unitType: UnitType.pieces,
        inputType: FieldInputType.slider,
        defaultValue: 4,
        minValue: 1,
        maxValue: 12,
        step: 1,
        required: true,
        order: 1,
      ),
      const CalculatorField(
        key: 'chambersCount',
        labelKey: 'input.chambersCount',
        unitType: UnitType.pieces,
        inputType: FieldInputType.slider,
        defaultValue: 3,
        minValue: 1,
        maxValue: 5,
        step: 1,
        required: true,
        order: 2,
      ),
      const CalculatorField(
        key: 'ringDiameter',
        labelKey: 'input.ringDiameter',
        unitType: UnitType.millimeters,
        inputType: FieldInputType.select,
        defaultValue: 1000,
        options: [
          FieldOption(value: 1000, labelKey: 'input.ringDiameter.1000'),
          FieldOption(value: 1500, labelKey: 'input.ringDiameter.1500'),
        ],
        required: true,
        order: 3,
      ),
    ],
    useCase: const CanonicalBridgeUseCase(calculateCanonicalSepticRings),
    iconName: 'plumbing',
    accentColor: kCalculatorAccentColor,
    complexity: 3,
    popularity: 55,
    tags: ['септик', 'кольца', 'канализация'],
  ),
];
