// GENERATED FILE - do not edit by hand.
// CalculatorDefinitionV2 entries used by the app.

import '../../../core/enums/calculator_category.dart';
import '../../../core/enums/field_input_type.dart';
import '../../../core/enums/unit_type.dart';
import '../../models/calculator_definition_v2.dart';
import '../../models/calculator_field.dart';
import '../../models/calculator_hint.dart';
import '../calculator_constants.dart';
import '../../usecases/calculate_gutters.dart';
import '../../usecases/calculate_roofing_metal.dart';
import '../../usecases/calculate_soft_roofing.dart';

final List<CalculatorDefinitionV2> roofingCalculators = [
  CalculatorDefinitionV2(
      id: 'roofing_gutters',
      titleKey: 'calculator.roofing_gutters.title',
      descriptionKey: 'calculator.roofing_gutters.description',
      category: CalculatorCategory.exterior,
      subCategoryKey: 'subcategory.roofing',
      fields: [
        const CalculatorField(
          key: 'roofLength',
          labelKey: 'input.roofLength',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'roofArea',
          labelKey: 'input.roofArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'gutterLength',
          labelKey: 'input.gutterLength',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 3.0,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Устанавливайте желоба с уклоном 3-5 мм на 1 м.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Кронштейны монтируются через каждые 50-60 см.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'На каждые 10 м² крыши — 1 водосточная труба.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте герметик для соединений.'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Устанавливайте желоба с уклоном 3-5 мм на 1 м.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Кронштейны монтируются через каждые 50-60 см.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'На каждые 10 м² крыши — 1 водосточная труба.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте герметик для соединений.'),
      ],
      useCase: CalculateGutters(),
      accentColor: kCalculatorAccentColor,
      complexity: 3,
      popularity: 10,
      tags: [
        'roofing',
        'roofing_gutters',
        'Кровля',
        'gutters',
        'Наружная отделка',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'roofing_metal',
      titleKey: 'calculator.roofing_metal.title',
      descriptionKey: 'calculator.roofing_metal.description',
      category: CalculatorCategory.exterior,
      subCategoryKey: 'subcategory.roofing',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 10.0,
          maxValue: 1000.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'slope',
          labelKey: 'input.slope',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 30.0,
          minValue: 5.0,
          maxValue: 60.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'sheetWidth',
          labelKey: 'input.sheetWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 1.18,
          minValue: 0.5,
          maxValue: 2.0,
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'sheetLength',
          labelKey: 'input.sheetLength',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 2.5,
          minValue: 1.0,
          maxValue: 8.0,
          required: true,
          order: 4,
        ),
        const CalculatorField(
          key: 'ridgeLength',
          labelKey: 'input.ridgeLength',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 100.0,
          required: false,
          order: 5,
        ),
        const CalculatorField(
          key: 'valleyLength',
          labelKey: 'input.valleyLength',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 100.0,
          required: false,
          order: 6,
        ),
        const CalculatorField(
          key: 'endLength',
          labelKey: 'input.endLength',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 100.0,
          required: false,
          order: 7,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Учитывайте уклон крыши при расчёте площади.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте специальные саморезы с уплотнителями.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Укладывайте листы с нахлёстом 15-20 см.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Не забудьте про гидроизоляцию под кровлей.'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Учитывайте уклон крыши при расчёте площади.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Используйте специальные саморезы с уплотнителями.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Укладывайте листы с нахлёстом 15-20 см.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Не забудьте про гидроизоляцию под кровлей.'),
      ],
      useCase: CalculateRoofingMetal(),
      accentColor: kCalculatorAccentColor,
      complexity: 3,
      popularity: 10,
      tags: [
        'roofing',
        'roofing_metal',
        'metal',
        'Кровля',
        'Наружная отделка',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'roofing_soft',
      titleKey: 'calculator.roofing_soft.title',
      descriptionKey: 'calculator.roofing_soft.description',
      category: CalculatorCategory.exterior,
      subCategoryKey: 'subcategory.roofing',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'slope',
          labelKey: 'input.slope',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 30.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'ridgeLength',
          labelKey: 'input.ridgeLength',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'valleyLength',
          labelKey: 'input.valleyLength',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 4,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Битумная черепица подходит для крыш с уклоном от 12°.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Обязательно используйте подкладочный ковёр.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Монтаж при температуре выше +5°C.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Укладывайте снизу вверх с перекрытием.'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'Битумная черепица подходит для крыш с уклоном от 12°.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Обязательно используйте подкладочный ковёр.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Монтаж при температуре выше +5°C.'),
        const CalculatorHint(type: HintType.tip, messageKey: 'Укладывайте снизу вверх с перекрытием.'),
      ],
      useCase: CalculateSoftRoofing(),
      accentColor: kCalculatorAccentColor,
      complexity: 3,
      popularity: 10,
      tags: [
        'roofing',
        'soft',
        'roofing_soft',
        'Кровля',
        'Наружная отделка',
      ],
    ),
];
