// GENERATED FILE - do not edit by hand.
// CalculatorDefinitionV2 entries used by the app.

import '../../../core/enums/calculator_category.dart';
import '../../../core/enums/field_input_type.dart';
import '../../../core/enums/unit_type.dart';
import '../../models/calculator_definition_v2.dart';
import '../../models/calculator_field.dart';
import '../../models/calculator_hint.dart';
import '../calculator_constants.dart';
import '../../usecases/calculate_3d_panels.dart';
import '../../usecases/calculate_brick_partition.dart';
import '../../usecases/calculate_decorative_plaster.dart';
import '../../usecases/calculate_decorative_stone.dart';
import '../../usecases/calculate_gasblock_partition.dart';
import '../../usecases/calculate_gvl_wall.dart';
import '../../usecases/calculate_gypsum.dart';
import '../../usecases/calculate_mdf_panels.dart';
import '../../usecases/calculate_plaster.dart';
import '../../usecases/calculate_primer.dart';
import '../../usecases/calculate_putty.dart';
import '../../usecases/calculate_pvc_panels.dart';
import '../../usecases/calculate_tile_glue.dart';
import '../../usecases/calculate_wall_tile.dart';
import '../../usecases/calculate_wallpaper.dart';
import '../../usecases/calculate_wood_wall.dart';

final List<CalculatorDefinitionV2> wallsCalculators = [
  CalculatorDefinitionV2(
      id: 'mixes_plaster',
      titleKey: 'calculator.mixes_plaster.title',
      descriptionKey: 'calculator.mixes_plaster.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.leveling_mix',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.wallArea',
          hintKey: 'input.wallArea.hint',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 1.0,
          maxValue: 1000.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'thickness',
          labelKey: 'input.plaster_thickness',
          hintKey: 'input.plaster_thickness.hint',
          unitType: UnitType.millimeters,
          inputType: FieldInputType.number,
          defaultValue: 10.0,
          minValue: 5.0,
          maxValue: 50.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'type',
          labelKey: 'input.plaster_type',
          unitType: UnitType.pieces,
          inputType: FieldInputType.select,
          defaultValue: 1.0,
          required: true,
          order: 3,
          options: [
            FieldOption(value: 1.0, labelKey: 'input.plaster_type.gypsum'),
            FieldOption(value: 2.0, labelKey: 'input.plaster_type.cement'),
          ],
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.plaster.measure_walls'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.plaster.gypsum_for_interior'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.plaster.cement_for_wet'),
      ],
      afterHints: [],
      useCase: CalculatePlaster(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      showToolsSection: false,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'tag.rovniteli_smesi',
        'plaster',
        'mixes',
        'mixes_plaster',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'mixes_primer',
      titleKey: 'calculator.mixes_primer.title',
      descriptionKey: 'calculator.mixes_primer.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.leveling_mix',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'layers',
          labelKey: 'input.layers',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'type',
          labelKey: 'input.type',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.gruntovka_uluchshaet_adgeziyu_materialov'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.gruntovka_glubokogo_proniknoveniya_dlya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.nanosite_ravnomernym_sloem'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.gruntovka_uluchshaet_adgeziyu_materialov'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.gruntovka_glubokogo_proniknoveniya_dlya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.nanosite_ravnomernym_sloem'),
      ],
      useCase: CalculatePrimer(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'mixes_primer',
        'tag.rovniteli_smesi',
        'mixes',
        'primer',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'mixes_putty',
      titleKey: 'calculator.mixes_putty.title',
      descriptionKey: 'calculator.mixes_putty.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.leveling_mix',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'layers',
          labelKey: 'input.layers',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 2.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'type',
          labelKey: 'input.putty_type',
          unitType: UnitType.pieces,
          inputType: FieldInputType.select,
          defaultValue: 1.0,
          required: true,
          order: 3,
          options: [
            FieldOption(value: 1.0, labelKey: 'input.putty_type.start'),
            FieldOption(value: 2.0, labelKey: 'input.putty_type.finish'),
          ],
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.startovaya_shpaklevka_dlya_vyravnivaniya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.nanosite_tonkimi_sloyami'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.shlifuyte_mezhdu_sloyami'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.startovaya_shpaklevka_dlya_vyravnivaniya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.nanosite_tonkimi_sloyami'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.shlifuyte_mezhdu_sloyami'),
      ],
      useCase: CalculatePutty(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'tag.rovniteli_smesi',
        'putty',
        'mixes',
        'mixes_putty',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'mixes_tile_glue',
      titleKey: 'calculator.mixes_tile_glue.title',
      descriptionKey: 'calculator.mixes_tile_glue.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.leveling_mix',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'tileSize',
          labelKey: 'input.tileSize',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 30.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'layerThickness',
          labelKey: 'input.layerThickness',
          unitType: UnitType.millimeters,
          inputType: FieldInputType.number,
          defaultValue: 5.0,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.rashod_zavisit_ot_razmera'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_zubchatyy_shpatel'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.nanosite_kley_na_osnovanie'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.rashod_zavisit_ot_razmera'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_zubchatyy_shpatel'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.nanosite_kley_na_osnovanie'),
      ],
      useCase: CalculateTileGlue(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'tile',
        'tag.rovniteli_smesi',
        'mixes_tile_glue',
        'mixes',
        'glue',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'partitions_blocks',
      titleKey: 'calculator.partitions_blocks.title',
      descriptionKey: 'calculator.partitions_blocks.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.partitions',
      fields: [
        const CalculatorField(
          key: 'length',
          labelKey: 'input.length',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'height',
          labelKey: 'input.height',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 2.7,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'thickness',
          labelKey: 'input.thickness',
          unitType: UnitType.millimeters,
          inputType: FieldInputType.number,
          defaultValue: 100.0,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_spetsialnyy_kley_dlya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.armiruyte_kazhdyy_3_4'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.pervyy_ryad_ukladyvayte_na'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.proveryayte_geometriyu_urovnem'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_spetsialnyy_kley_dlya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.armiruyte_kazhdyy_3_4'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.pervyy_ryad_ukladyvayte_na'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.proveryayte_geometriyu_urovnem'),
      ],
      useCase: CalculateGasblockPartition(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'tag.peregorodki',
        'partitions',
        'blocks',
        'partitions_blocks',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'partitions_gkl',
      titleKey: 'calculator.partitions_gkl.title',
      descriptionKey: 'calculator.partitions_gkl.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.partitions',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 20.0,
          minValue: 1.0,
          maxValue: 1000.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'layers',
          labelKey: 'input.layers',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          minValue: 1.0,
          maxValue: 2.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'gkl_type',
          labelKey: 'input.gkl_type',
          unitType: UnitType.pieces,
          inputType: FieldInputType.select,
          defaultValue: 1.0,
          required: true,
          order: 3,
          options: [
            FieldOption(value: 1.0, labelKey: 'input.gkl_type.standard'),
            FieldOption(value: 2.0, labelKey: 'input.gkl_type.moisture'),
            FieldOption(value: 3.0, labelKey: 'input.gkl_type.fire'),
          ],
        ),
        const CalculatorField(
          key: 'use_insulation',
          labelKey: 'input.use_insulation',
          unitType: UnitType.pieces,
          inputType: FieldInputType.checkbox,
          defaultValue: 0.0,
          required: false,
          order: 4,
        ),
        const CalculatorField(
          key: 'construction_type',
          labelKey: 'input.construction_type',
          unitType: UnitType.pieces,
          inputType: FieldInputType.select,
          defaultValue: 2.0,
          required: true,
          order: 5,
          options: [
            FieldOption(value: 2.0, labelKey: 'input.construction_type.partition'),
          ],
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.gypsum.choose_gklv_for_wet'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.gypsum.step_profiles_60cm'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.gypsum.use_sealing_tape'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.gypsum.screw_depth_1mm'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.gypsum.joints_offset'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.gypsum.gap_from_floor'),
      ],
      useCase: CalculateGypsum(),
      accentColor: kCalculatorAccentColor,
      complexity: 3,
      popularity: 9,
      showToolsSection: false,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'tag.peregorodki',
        'gkl',
        'gypsum',
        'partitions',
        'partitions_gkl',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'partitions_brick',
      titleKey: 'calculator.partitions_brick.title',
      descriptionKey: 'calculator.partitions_brick.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.partitions',
      fields: [
        const CalculatorField(
          key: 'length',
          labelKey: 'input.length',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'height',
          labelKey: 'input.height',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 2.7,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'brickType',
          labelKey: 'input.type',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 0.5,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.kladku_v_polkirpicha_armiruyte'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_tsementno_peschanyy_rastvor'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.proveryayte_vertikalnost_otvesom'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.svyazyvayte_s_nesuschimi_stenami'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.kladku_v_polkirpicha_armiruyte'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_tsementno_peschanyy_rastvor'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.proveryayte_vertikalnost_otvesom'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.svyazyvayte_s_nesuschimi_stenami'),
      ],
      useCase: CalculateBrickPartition(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'tag.peregorodki',
        'partitions',
        'partitions_brick',
        'brick',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'gypsum_board',
      titleKey: 'calculator.gypsum_board.title',
      descriptionKey: 'calculator.gypsum_board.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.walls',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 20.0,
          minValue: 1.0,
          maxValue: 1000.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'construction_type',
          labelKey: 'input.construction_type',
          unitType: UnitType.pieces,
          inputType: FieldInputType.select,
          defaultValue: 1.0,
          required: true,
          order: 2,
          options: [
            FieldOption(value: 1.0, labelKey: 'input.construction_type.wall_lining'),
            FieldOption(value: 2.0, labelKey: 'input.construction_type.partition'),
            FieldOption(value: 3.0, labelKey: 'input.construction_type.ceiling'),
          ],
        ),
        const CalculatorField(
          key: 'layers',
          labelKey: 'input.layers',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          minValue: 1.0,
          maxValue: 2.0,
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'gkl_type',
          labelKey: 'input.gkl_type',
          unitType: UnitType.pieces,
          inputType: FieldInputType.select,
          defaultValue: 1.0,
          required: true,
          order: 4,
          options: [
            FieldOption(value: 1.0, labelKey: 'input.gkl_type.standard'),
            FieldOption(value: 2.0, labelKey: 'input.gkl_type.moisture'),
            FieldOption(value: 3.0, labelKey: 'input.gkl_type.fire'),
          ],
        ),
        const CalculatorField(
          key: 'use_insulation',
          labelKey: 'input.use_insulation',
          unitType: UnitType.pieces,
          inputType: FieldInputType.checkbox,
          defaultValue: 0.0,
          required: false,
          order: 5,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.gypsum.choose_gklv_for_wet'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.gypsum.step_profiles_60cm'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.gypsum.use_sealing_tape'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.gypsum.screw_depth_1mm'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.gypsum.joints_offset'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.gypsum.gap_from_floor'),
      ],
      useCase: CalculateGypsum(),
      accentColor: kCalculatorAccentColor,
      complexity: 3,
      popularity: 9,
      showToolsSection: false,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'tag.steny',
        'gypsum',
        'gkl',
        'drywall',
        'gypsum_board',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'walls_3d_panels',
      titleKey: 'calculator.walls_3d_panels.title',
      descriptionKey: 'calculator.walls_3d_panels.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.walls',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.wallArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'panelSize',
          labelKey: 'input.packArea',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.5,
          required: true,
          order: 2,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.proverte_rovnost_sten_pered'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_spetsialnyy_kley_dlya_2'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.nachinayte_montazh_ot_tsentra'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.proverte_rovnost_sten_pered'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_spetsialnyy_kley_dlya_2'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.nachinayte_montazh_ot_tsentra'),
      ],
      useCase: Calculate3dPanels(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'walls_3d_panels',
        'tag.vnutrennyaya_otdelka',
        'walls',
        'tag.steny',
        'panels',
        '3d',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'walls_decor_plaster',
      titleKey: 'calculator.walls_decor_plaster.title',
      descriptionKey: 'calculator.walls_decor_plaster.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.walls',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'thickness',
          labelKey: 'input.thickness',
          unitType: UnitType.millimeters,
          inputType: FieldInputType.number,
          defaultValue: 2.0,
          minValue: 0.5,
          maxValue: 10.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'windowsArea',
          labelKey: 'input.windowsArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'doorsArea',
          labelKey: 'input.doorsArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 4,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_gruntovku_glubokogo_proniknoveniya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.vozmite_shpateli_i_kelmy'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.dlya_venetsianskoy_shtukaturki_nuzhna'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_gruntovku_glubokogo_proniknoveniya'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.vozmite_shpateli_i_kelmy'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.dlya_venetsianskoy_shtukaturki_nuzhna'),
      ],
      useCase: CalculateDecorativePlaster(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'decor',
        'walls',
        'walls_decor_plaster',
        'plaster',
        'tag.steny',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'walls_decor_stone',
      titleKey: 'calculator.walls_decor_stone.title',
      descriptionKey: 'calculator.walls_decor_stone.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.walls',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.wallArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'thickness',
          labelKey: 'input.thickness',
          unitType: UnitType.millimeters,
          inputType: FieldInputType.number,
          defaultValue: 15.0,
          required: true,
          order: 2,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.dobavte_10_zapas_na'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_spetsialnyy_kley_dlya_3'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.obrabotayte_kamen_gidrofobizatorom'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.dobavte_10_zapas_na'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_spetsialnyy_kley_dlya_3'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.obrabotayte_kamen_gidrofobizatorom'),
      ],
      useCase: CalculateDecorativeStone(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'decor',
        'stone',
        'walls',
        'tag.steny',
        'walls_decor_stone',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'walls_gvl',
      titleKey: 'calculator.walls_gvl.title',
      descriptionKey: 'calculator.walls_gvl.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.walls',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.wallArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'layers',
          labelKey: 'input.layers',
          unitType: UnitType.pieces,
          inputType: FieldInputType.number,
          defaultValue: 1.0,
          required: true,
          order: 2,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.gvl_tyazhelee_gkl_usilte'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_samorezy_dlya_gvl'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.zazor_mezhdu_listami_5'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.gvl_tyazhelee_gkl_usilte'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_samorezy_dlya_gvl'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.zazor_mezhdu_listami_5'),
      ],
      useCase: CalculateGvlWall(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'gvl',
        'walls',
        'walls_gvl',
        'tag.steny',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'walls_mdf_panels',
      titleKey: 'calculator.walls_mdf_panels.title',
      descriptionKey: 'calculator.walls_mdf_panels.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.walls',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.wallArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'panelWidth',
          labelKey: 'input.panelWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.2,
          required: true,
          order: 2,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.mdf_ne_dlya_vlazhnyh'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.obreshetka_s_shagom_40'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.krepite_na_klyaymery_ili'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.mdf_ne_dlya_vlazhnyh'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.obreshetka_s_shagom_40'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.krepite_na_klyaymery_ili'),
      ],
      useCase: CalculateMdfPanels(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'walls_mdf_panels',
        'walls',
        'tag.steny',
        'mdf',
        'panels',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'walls_pvc_panels',
      titleKey: 'calculator.walls_pvc_panels.title',
      descriptionKey: 'calculator.walls_pvc_panels.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.walls',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.wallArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'panelWidth',
          labelKey: 'input.panelWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.25,
          required: true,
          order: 2,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.paneli_ukladyvayte_ot_ugla'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ostavlyayte_temperaturnyy_zazor_5'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_startovyy_i_finishnyy'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.paneli_ukladyvayte_ot_ugla'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ostavlyayte_temperaturnyy_zazor_5'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_startovyy_i_finishnyy'),
      ],
      useCase: CalculatePvcPanels(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'walls',
        'tag.steny',
        'walls_pvc_panels',
        'pvc',
        'panels',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'walls_tile',
      titleKey: 'calculator.walls_tile.title',
      descriptionKey: 'calculator.walls_tile.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.walls',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.wallArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'tileWidth',
          labelKey: 'input.tileWidth',
          unitType: UnitType.centimeters,
          inputType: FieldInputType.number,
          defaultValue: 30.0,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'tileHeight',
          labelKey: 'input.tileHeight',
          unitType: UnitType.centimeters,
          inputType: FieldInputType.number,
          defaultValue: 60.0,
          required: true,
          order: 3,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.dobavte_10_zapas_na_2'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_krestiki_dlya_rovnyh'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.nachinayte_so_vtorogo_ryada'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.dobavte_10_zapas_na_2'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.ispolzuyte_krestiki_dlya_rovnyh'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.nachinayte_so_vtorogo_ryada'),
      ],
      useCase: CalculateWallTile(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'walls_tile',
        'walls',
        'tag.steny',
        'tile',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'walls_wallpaper',
      titleKey: 'calculator.walls_wallpaper.title',
      descriptionKey: 'calculator.walls_wallpaper.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.walls',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.area',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 1.0,
          maxValue: 500.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'rollWidth',
          labelKey: 'input.rollWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.53,
          minValue: 0.5,
          maxValue: 1.2,
          required: true,
          order: 2,
        ),
        const CalculatorField(
          key: 'rollLength',
          labelKey: 'input.rollLength',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 10.05,
          minValue: 5.0,
          maxValue: 50.0,
          required: true,
          order: 3,
        ),
        const CalculatorField(
          key: 'rapport',
          labelKey: 'input.rapport',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 100.0,
          required: false,
          order: 4,
        ),
        const CalculatorField(
          key: 'wallHeight',
          labelKey: 'input.wallHeight',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 2.5,
          minValue: 2.0,
          maxValue: 5.0,
          required: true,
          order: 5,
        ),
        const CalculatorField(
          key: 'windowsArea',
          labelKey: 'input.windowsArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 100.0,
          required: false,
          order: 6,
        ),
        const CalculatorField(
          key: 'doorsArea',
          labelKey: 'input.doorsArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          minValue: 0.0,
          maxValue: 50.0,
          required: false,
          order: 7,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.wallpaper.check_batch_number'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.wallpaper.start_from_window'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.wallpaper.temperature_humidity'),
      ],
      useCase: CalculateWallpaper(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'wallpaper',
        'walls',
        'tag.steny',
        'walls_wallpaper',
      ],
    ),
  CalculatorDefinitionV2(
      id: 'walls_wood',
      titleKey: 'calculator.walls_wood.title',
      descriptionKey: 'calculator.walls_wood.description',
      category: CalculatorCategory.interior,
      subCategoryKey: 'subcategory.walls',
      fields: [
        const CalculatorField(
          key: 'area',
          labelKey: 'input.wallArea',
          unitType: UnitType.squareMeters,
          inputType: FieldInputType.number,
          defaultValue: 0.0,
          required: true,
          order: 1,
        ),
        const CalculatorField(
          key: 'boardWidth',
          labelKey: 'input.boardWidth',
          unitType: UnitType.meters,
          inputType: FieldInputType.number,
          defaultValue: 0.1,
          required: true,
          order: 2,
        ),
      ],
      beforeHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.dayte_vagonke_akklimatizirovatsya_48'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.obrabotayte_antiseptikom_pered_montazhom'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.krepite_na_klyaymery_dlya'),
      ],
      afterHints: [
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.dayte_vagonke_akklimatizirovatsya_48'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.obrabotayte_antiseptikom_pered_montazhom'),
        const CalculatorHint(type: HintType.tip, messageKey: 'hint.walls.krepite_na_klyaymery_dlya'),
      ],
      useCase: CalculateWoodWall(),
      accentColor: kCalculatorAccentColor,
      complexity: 2,
      popularity: 10,
      tags: [
        'tag.vnutrennyaya_otdelka',
        'wood',
        'walls',
        'walls_wood',
        'tag.steny',
      ],
    ),
];
