// ignore_for_file: avoid_print

/// Генератор типобезопасных ключей локализации.
///
/// Создаёт Dart-класс с константами для всех ключей из ru.json,
/// что позволяет использовать автодополнение и проверку на этапе компиляции.
///
/// Использование: dart run scripts/generate_localization_keys.dart
///
/// Результат: lib/core/localization/l10n_keys.dart
library;

import 'dart:convert';
import 'dart:io';

void main() {
  print('Generating localization keys...\n');

  // Загружаем JSON
  final jsonFile = File('assets/lang/ru.json');
  if (!jsonFile.existsSync()) {
    print('ERROR: ru.json not found!');
    exit(1);
  }

  final Map<String, dynamic> json = jsonDecode(jsonFile.readAsStringSync());

  // Генерируем код
  final buffer = StringBuffer();

  buffer.writeln('// GENERATED FILE - DO NOT EDIT');
  buffer.writeln('// Generated by: dart run scripts/generate_localization_keys.dart');
  buffer.writeln('//');
  buffer.writeln('// ignore_for_file: constant_identifier_names');
  buffer.writeln();
  buffer.writeln('/// Типобезопасные ключи локализации.');
  buffer.writeln('///');
  buffer.writeln('/// Использование:');
  buffer.writeln('/// ```dart');
  buffer.writeln('/// _loc.translate(L10nKeys.common_sqm)');
  buffer.writeln('/// ```');
  buffer.writeln('abstract final class L10nKeys {');

  final keys = flattenJson(json);
  final sortedKeys = keys.toList()..sort();

  // Отслеживаем использованные имена для избежания дубликатов
  final usedNames = <String>{};
  var skipped = 0;

  for (final key in sortedKeys) {
    // Пропускаем ключи с кириллицей (невалидные Dart-идентификаторы)
    if (RegExp(r'[а-яА-ЯёЁ]').hasMatch(key)) {
      skipped++;
      continue;
    }

    final constName = key.replaceAll('.', '_').replaceAll('-', '_');

    // Пропускаем если имя уже использовано (дубликат)
    if (usedNames.contains(constName)) {
      skipped++;
      continue;
    }

    usedNames.add(constName);
    buffer.writeln("  static const $constName = '$key';");
  }

  print('Skipped keys (cyrillic/duplicates): $skipped');

  buffer.writeln('}');

  // Записываем файл
  final outputDir = Directory('lib/core/localization');
  if (!outputDir.existsSync()) {
    outputDir.createSync(recursive: true);
  }

  final outputFile = File('lib/core/localization/l10n_keys.dart');
  outputFile.writeAsStringSync(buffer.toString());

  print('Generated ${keys.length} keys');
  print('Output: lib/core/localization/l10n_keys.dart');
  print('\nUsage example:');
  print('  _loc.translate(L10nKeys.common_sqm)');
}

/// Преобразует вложенный JSON в плоский список ключей
Set<String> flattenJson(Map<String, dynamic> json, [String prefix = '']) {
  final keys = <String>{};

  for (final entry in json.entries) {
    final key = prefix.isEmpty ? entry.key : '$prefix.${entry.key}';

    if (entry.value is Map<String, dynamic>) {
      keys.addAll(flattenJson(entry.value as Map<String, dynamic>, key));
    } else {
      keys.add(key);
    }
  }

  return keys;
}
